### PR TITLE
Diagonal Print Algorithm in 2D arrays (C, C++, Java, Python)

### PR DESCRIPTION
**Pull request by Dharnish38**
## 🛠️ Issue (#578)

Issue no #578 (C, C++, Java, Python)

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
@Kumar-laxmi, since I have asked you to assign this task. I have completed implementing it using the language C, C++, Java, Python.
So, I request you to once review, my PR, and then merge it.
Thank you!!! for letting me contribute to the repo.

## 📷 Screenshots
C :-
Diagnol_c
C++ :-
Diagnol_c++
Java :-
Diagnol_java
Python :-
Diagnol_python
I hope you will merge this PR, so that I can contribute to your other issues also 👍
Thank You !!!!!

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Just fix the typo in file name. It's diagonal !

**Comment by Dharnish38** [comment]
> Just fix the typo in file name. It's diagonal !
Sorry for the typo, I have changed the file name, please look into it @siddhi-244

**Review by siddhi-244 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Rancho2002 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Rishikavishnoi Kindly review this PR

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by Rishikavishnoi** [comment]
@Kumar-laxmi Done 👍

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
