### PR TITLE
Columnar Transposition Cipher

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## 🛠️ Issue (Number)

Issue no #986 

## 👨‍💻 Changes proposed

Added Columnar Transposition Cipher in C, C++, Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
**C Programming Implementation**

Screenshot 2023-06-15 at 18 58 21

**C++ Programming Implementation**

Screenshot 2023-06-15 at 19 05 56

**Python Programming Implementation**

Screenshot 2023-06-15 at 18 57 04

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please include the screen shot of your implementation in each language in the PR description

**Comment by Vidip-Ghosh** [comment]
> Please include the screen shot of your implementation in each language in the PR description

Yes I have included.

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Vidip-Ghosh Take input from user in program

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh Take input from user in program

Actually I am unable to add the add user defined input in Java since it gave me **Index OutOfBound Exception.**

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
When screen-shots are asked, it is meant by the screen-shots of your output not your code. You code is already visible in the code space of your PR.

**Comment by Kumar-laxmi** [comment]
@Arun9739 Kindly review this PR

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly resolve your **CodeFactor** warnings

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
