### PR TITLE
Added Binary Search on a 2d matrix in C, C++ and Python.

### PR DESCRIPTION
**Pull request by Arbtrage**
## 🛠️ Issue (Number)

Issue no #135 

## 👨‍💻 Changes proposed

Added Binary Search Algorithm to search an element in a 2D array in C++ language
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your algorithm

**Comment by Arbtrage** [comment]
Sorry I checked the java code there, it is not a Binary Search Algorithm, it's not even a searching algorithm. Giving multiple wrong answers. :)
How should I proceed ?

**Comment by Arbtrage** [comment]
I don't think that the Java code there follows Binary Search Algorithm.
-> Binary Search works on a sorted array (The example given there is not sorted)
-> The algorithm in that file does not follow Divide and Conquer approach and thus is not in Logarithmic time complexity,

How should I proceed then ?

**Comment by Arun9739** [comment]
> Sure, I would be happy to . But I think this question is already present in the Java folder with a different algorithm, so should I create another file there with this algorithm or should I just add another function in that file ?
> 
> This file: https://github.com/Kumar-laxmi/Algorithms/blob/main/Java/Searching/binary_search_2d.java

If your algorithm is different then create another program in Java

**Review by Arun9739 — APPROVED** [review]

**Comment by Arbtrage** [comment]
Ok sure, will do .

**Review by 072arushi — APPROVED** [review]

**Review by Rancho2002 — APPROVED** [review]
Perfect

**Comment by Arbtrage** [comment]
Thank you .

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by Arbtrage** [comment]
@Kumar-laxmi , Please Check this PR..

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove the ```Java``` file since it is already implemented, instead you can implement in ```C```

**Comment by Arbtrage** [comment]
Done , please review @Kumar-laxmi .

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
