### PR TITLE
Java program to calculate factors of a number

### PR DESCRIPTION
**Pull request by Hannibal404**

### CODE REVIEW

**Comment by Hannibal404** [comment]
Added cpp program to calculate factors of a number as well

**Comment by Kumar-laxmi** [comment]
@Hannibal404 Add C program for this also

**Comment by Hannibal404** [comment]
@Kumar-laxmi it would not be possible in C as this implementation uses vectors, which aren't there in the C library.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi it would not be possible in C as this implementation uses vectors, which aren't there in the C library.

@Hannibal404 This is where you need to apply your DSA knowledge.

**Comment by Kumar-laxmi** [comment]
And please push the python program in this PR as same logic can't be spammed in two PRs

**Comment by Hannibal404** [comment]
> 

It has been merged already in the previous PR. It cannot be added here now

**Comment by Kumar-laxmi** [comment]
I have reverted the PR, now please push the file in this PR

**Comment by Hannibal404** [comment]
@Kumar-laxmi Added

**Comment by Kumar-laxmi** [comment]
@Hannibal404 Please add the main() method in Java program

**Comment by Hannibal404** [comment]
Added

**Comment by Hannibal404** [comment]
@Kumar-laxmi added the main() function in the Java program

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
