### PR TITLE
Greedy Method -Activity Selection Problem

### PR DESCRIPTION
**Pull request by shailja2727**
## 🛠️ Issue (Number) #330

Issue no #330 

## 👨‍💻 Changes proposed

In Greedy-Algorithms Folder an activity selection problem added in C++,C,Java,Python

## ✔️ Check List (Check all the applicable boxes) 

- [✅] My code follows the code style of this project.
- [✅] This PR does not contain plagiarized content.
- [✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I have added Activity Selection Problem in Greedy-Algorithms Folder in all the languages(C,C++,Java,Python)

## 📷 Screenshots
->Number of processes is the activities which is given dynamically by user.
->Start and finish time is taken by the user for each activity.
->According to the algorithm the output is given as the activities which will be selected.

image

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Comment by shailja2727** [comment]
> Add comments to explain your approach

I have added the comments to explain the approach just now. If there is a problem in the code then please tell .

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please include the issue number of Matrix Chain

**Comment by shailja2727** [comment]
> Please include the issue number of Matrix Chain

It is issue number #189 and implemented in #329

**Comment by shailja2727** [comment]
I have added the python,C++ as well as Java Code

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
If you have removed the code of Matrix Chain Multiplication, then remove the issue number from description

**Comment by shailja2727** [comment]
> If you have removed the code of Matrix Chain Multiplication, then remove the issue number from description

yes removed

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
code of matrix multiplication not removed yet

**Comment by shailja2727** [comment]
> code of matrix multiplication not removed yet

Removed .Please check

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@shailja2727 Please add a output screenshots to depict the result.

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
You can try adding the code for C too.

**Review by zugzwang03 — APPROVED** [review]

**Comment by shailja2727** [comment]
> @shailja2727 Please add a output screenshots to depict the result.

Added with steps. Please check the topmost comment where i've added a screenshot and respond is any changes needed

**Comment by shailja2727** [comment]
> You can try adding the code for C too.

Just added the code in C too. Please Check

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by shailja2727** [comment]
Done with all changes requested, @Kumar-laxmi @Arun9739 Please review it

**Review by Arun9739 — APPROVED** [review]
Nice ! Approved !

**Comment by shailja2727** [comment]
> If you have removed the code of Matrix Chain Multiplication, then remove the issue number from description

Sir I've done all the changes and my branch is updated to upstream .Please review @Kumar-laxmi

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
