### PR TITLE
Added AVL Tree Implementation and Doubly Linked List Implementation in C language 

### PR DESCRIPTION
**Pull request by Sowham-3098**
## 🛠️ Issue (Number)

Issue no #11 
Issue no #51 _

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (235)
Screenshot (236)
Screenshot (237)
Screenshot (238)

### CODE REVIEW

**Comment by Sowham-3098** [comment]
@Kumar-laxmi Actually I can't resolve conflicts of Previous PR #495, so created this PR with no conflicts. Please consider.

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Add some comments in doubly linked list code to explain

**Review by Rancho2002 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by Sowham-3098** [comment]
> @Sowham-3098 Add screenshots of the output in the PR description.

@Sanjanabharadwaj25  I added screenshots , please check

**Review by Arun9739 — APPROVED** [review]

**Comment by Sowham-3098** [comment]
@Sanjanabharadwaj25 ,please check it.

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Sowham-3098 Please resolve the **CodeFactor** issue

**Comment by Sowham-3098** [comment]
Can anyone help me with this issue ? I changed the code but it gives the same issue.

**Comment by Arun9739** [comment]
> Can anyone help me with this issue ? I changed the code but it gives the same issue.

Check the description of codefactor issue below. There you can get the idea why it is showing a problem.

**Comment by Sowham-3098** [comment]
Screenshot_2023-02-19-20-53-33-52_40deb401b9ffe8e1df2f1cc5ba480b12
Codefactor show this . Don't understand what to change.

**Comment by Arun9739** [comment]
@Sowham-3098 It is saying method is complex. Try with differnt form of same method

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Place the file ```AVL_Tree.c``` in Tree folder and remove the ```AVL Tree``` folder

**Comment by Sowham-3098** [comment]
> Place the file ```AVL_Tree.c``` in Tree folder and remove the ```AVL Tree``` folder

Okk

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
