### PR TITLE
#Issue854 : Prefix-Postfix-Infix interconversion algorithm in C & Java

### PR DESCRIPTION
**Pull request by AnubhaSharma2709**
## 🛠️ Issue 854
#854 
## I was given the reference of the following GithHb Repository.
https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Maths/Infix_Postfix_Prefix_Interconversion.cpp
https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Maths/prefix_infix_postfix_interconversion.py

## Based on the above code:
1. I have implemented a Menu Driven Program for the interconversion of Prefix-Postfix-Infix Expressions.

## Kindly Review my Code.

JAVA IMPLEMTATION
output-1
output-2

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Give same name to both program files

**Comment by Kumar-laxmi** [comment]
@AnubhaSharma2709 Kindly make the required changes ASAP

**Review by zugzwang03 — APPROVED** [review]
The code quality looks fine, just give same name to both the files.

**Comment by AnubhaSharma2709** [comment]
Sorry for the delay
I have changed the file name
and added the screenshots

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Pull request closed without merging**
