### PR TITLE
 Reverse Integer & Cocktail Sort issues resolved

### PR DESCRIPTION
**Pull request by swastik-akhil**
## 🛠️ Issue (#693 & #694)

 Reverse Integer & Cocktail Sort

## 👨‍💻 Changes proposed

1. Code in Python was added for Cocktail sort.
2. Code in Java was added for Cocktail Sort and Reverse Integer
3. Code in C was added for Cocktail Sort and Reverse Integer

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by swastik-akhil** [comment]
I request @zugzwang03 and @Arun9739 to kindly review the PR.

**Review by zugzwang03 — APPROVED** [review]

**Comment by swastik-akhil** [comment]
The PR is **_approved_** by @zugzwang03, hence I would like to draw the attention of @Kumar-laxmi to kindly **_merge_** this PR.

**Comment by Kumar-laxmi** [comment]
Please close this PR & open one PR per issue for easy evaluation and grading

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@swastik-akhil Add output screenshot

**Comment by Kumar-laxmi** [comment]
@swastik-akhil Please open two separate PR for two separate issue for easy evaluation

**Comment by swastik-akhil** [comment]
@Kumar-laxmi earlier there were two separate pr but some issue occurred so I merged that two. It would be very kind to me if you merge this pr. I'll take care of this in future.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi earlier there were two separate pr but some issue occurred so I merged that two. It would be very kind to me if you merge this pr. I'll take care of this in future.

This would be allowed this time only

**Comment by swastik-akhil** [comment]
Thanks for being nice @Kumar-laxmi

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by swastik-akhil** [comment]
Since all the reviews are approved, hence I request @Kumar-laxmi to kindly merge the PR

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
