### PR TITLE
Sieve of eratosthenes algorithm in Python

### PR DESCRIPTION
**Pull request by vijay-kumar-yadav**
## 🛠️ Issue (#173)

Issue no #173

## 👨‍💻 Changes proposed
1. Sieve of eratosthenes algorithm in python added
2. Readme updated for the same

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi please review it

**Comment by zugzwang03** [comment]
> @Kumar-laxmi please review it

Gentle request to add a few comment lines explaining your approach to the problem

**Comment by vijay-kumar-yadav** [comment]
> > > @Kumar-laxmi please review it
> > 
> > 
> > Gentle request to add a few comment lines explaining your approach to the problem
> 
> Okay I will add.

@zugzwang03 I have added comment please review it

**Review by zugzwang03 — APPROVED** [review]
Looks fine to me!

**Review by 072arushi — APPROVED** [review]
Approved

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
