### PR TITLE
Create Permutation_of_string.cpp

### PR DESCRIPTION
**Pull request by dv8081**
Permutation of a string in C++

## 🛠️ Issue (Number)

Issue no #

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@dv8081 Please mention the issue number for this PR.

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Link your PR with the issue

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add a screenshot of program result and mention the issue number

**Comment by Kumar-laxmi** [comment]
Inactive PR

**Pull request closed without merging**
