### PR TITLE
feat: Added fractional_knapsack.c in ->C/Greedy-Algorithm

### PR DESCRIPTION
**Pull request by mayyyur**
Contributed fractional knapsack( Greedy algorithm ) program in C language.

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@mayyyur Kindly get all checks successful

**Comment by mayyyur** [comment]
i am working on it need to reduce the lines of code.

**Review by mayyyur — COMMENTED** [review]
Updated the program in the file

**Comment by Kumar-laxmi** [comment]
@mayyyur It is clearly visible that you have **plagiarised** from the following website: https://www.sanfoundry.com/c-program-solve-fractional-knapsack-problem/

**Pull request closed without merging**
