### PR TITLE
KNN algo in c++

### PR DESCRIPTION
**Pull request by Srishtihere**
#

## 🛠️ Issue (#444 )

Issue no #444 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by Srishtihere** [comment]
removed them

**Review by 072arushi — APPROVED** [review]
Add comments to explain your algorithm

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
please write the full form of KNN as the name of the file

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add a screenshot of output

**Comment by Srishtihere** [comment]
Screenshot (17)

screenshot of the output

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly put this file in ```Machine-Learning``` folder

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
