### PR TITLE
SVM algorithm implementation in C++ and Python

### PR DESCRIPTION
**Pull request by ayan-joshi**
## issue number #931 

Issue no #

## 👨‍💻 Changes proposed

Added the implementation of SVM algorithm in C++ and Python without using ML libraries , 
also added the readme file with proper explanation of the implementation. 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Python output :- 
Screenshot 2023-04-22 135853

C++ output :- 
Screenshot (180)

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- Remove the ```.vscode``` folder
- Please do not create a separate folder for SVM 
- Direct put the program file in ```Machine-Learning``` folder
- Do not create a separate README.md, instead put the README.md content in the program file as comments

**Comment by ayan-joshi** [comment]
@Kumar-laxmi okay will do the changes

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@ayan-joshi Add output screenshot

**Comment by ayan-joshi** [comment]
@Arun9739 updated the comment with output sir

**Comment by ayan-joshi** [comment]
@Kumar-laxmi please merge the request

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
image

Does it mean your code doesn't follow any of these?

**Comment by ayan-joshi** [comment]
> image
> 
> Does it mean your code doesn't follow any of these?

sorry for mistake I updated it now

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by ayan-joshi** [comment]
@Kumar-laxmi got all approvals please merge the request

**Pull request closed without merging**
