### PR TITLE
Added Fractional Knapsack (Greedy-Algorithm) implementation in Python

### LINKED ISSUE #73: Fractional Knapsack - Greedy approach
Fractional Knapsack is available in the following languages:
- C
- C++
- Java
- Python

### Kindly include this project in **Greedy Programming** folder

### PR DESCRIPTION
**Pull request by stiwari-ds**
## 🛠️ Issue (Number)

Issue no #73 

## 👨‍💻 Changes proposed

1. Added fractional knapsack implementation in Python
2. Added README file with usage example

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Code:
code1
code2
code3

Output:
output

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Nice implementation. Approved

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
@stiwari-ds Don't create a seperate folder for this algorithm & the README.md could be updated in the README of ```Greedy-Algorithms``` folder

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Ok, I will do that. Just wanted to include some usage instructions and examples so I added the separate README.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi I have made the requested changes. Let me know if anything else is required.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi May I know what else is needed to have this PR merged?

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
