### PR TITLE
Updated Edmonds-Karp Algorithm in Graphs DSA (C++ and Python)

### PR DESCRIPTION
**Pull request by neeraj542**
## 🛠️ Issue (Number)

Issue no #718

## 👨‍💻 Changes proposed
This pull request aims to enhance the efficiency of the Edmonds-Karp algorithm implementation and broaden its applicability by adding support for the Python programming language. The proposed changes include optimized C++ code for improved performance, the addition of Python code for greater versatility, and enhanced documentation to aid developers. These updates aim to provide developers with an efficient and accessible solution for maximum flow problems in both C++ and Python environments. Please review the changes and consider merging them into the main repository.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
In the pseudocode, 'V' represents the number of vertices in the graph, 'residualGraph' refers to the residual capacities of the graph, and the graph represents the original 'graph' with capacities.

Thank you for reviewing this pull request. The changes include optimizations to the Edmonds-Karp algorithm implementation and the addition of Python code for improved versatility. Your feedback and suggestions are valuable to us, and we welcome any recommendations to enhance the algorithm further. We appreciate your time and collaboration in making this implementation more efficient and scalable.

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
Please don't include same files in two different PRs, to avoid it you can create two separate branch which raise two separate PRs and each having different files

**Comment by neeraj542** [comment]
@Kumar-laxmi, Please provide more specific details about the context in which you wish to merge, such as the nature of the entity or project you are referring to.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi, Please provide more specific details about the context in which you wish to merge, such as the nature of the entity or project you are referring to.

So basically you are providing same set of files in two different PR

**Comment by neeraj542** [comment]
Please give me just stepped process, so that I can do it fast>

**Comment by Kumar-laxmi** [comment]
1. Create a new branch: Start by creating a new branch from the main branch of your repository. This branch will contain the changes for one of the pull requests.
```
git checkout -b branch1
```

2. Make the changes for the first pull request: In the new branch (branch1), make all the necessary changes, including adding, modifying, or deleting files.

3. Commit your changes: Once you have made the changes for the first pull request, commit them in the branch.
```
git add .
git commit -m "First pull request changes"
```
4. Push the branch: Push the branch to your remote repository.
```
git push origin branch1
```
5. Create the first pull request: Go to your repository's online platform (e.g., GitHub, Bitbucket) and create a new pull request. Select the branch1 branch as the source branch and the main branch as the target branch. Provide a descriptive title and description for the pull request and submit it.
6. Create a new branch for the second pull request: Now, create another new branch from the main branch to work on the changes for the second pull request.
```
git checkout -b branch2
```
7. Make the changes for the second pull request: In the branch2, make the necessary changes for the second pull request, which should not include any duplication with the first pull request.
8. Commit your changes: Once you have made the changes for the second pull request, commit them in the branch.
```
git add .
git commit -m "Second pull request changes"
```
9. Push the branch: Push the branch to your remote repository.
```
git push origin branch2
```
10. Create the second pull request: Go to your repository's online platform and create a new pull request. Select the branch2 branch as the source branch and the main branch as the target branch. Provide a descriptive title and description for the pull request and submit it.

**Comment by Kumar-laxmi** [comment]
I hope this might help you

**Comment by Kumar-laxmi** [comment]
Better close these two PRs and create two fresh PRs from two newly created branches

**Comment by neeraj542** [comment]
Ok sure, But if this time another person will create the PR then it will be more complex for me.

**Comment by Kumar-laxmi** [comment]
> Ok sure, But if in this time another person will create the PR then it will be more complex for me.

You just need to synchronize them

**Comment by neeraj542** [comment]
Ok will comeback soon

**Comment by Kumar-laxmi** [comment]
First upstream your main branch which is pointing to this repository's main branch and then upstream child branches which is pointing to your main branch

**Comment by neeraj542** [comment]
image


Should I delete these branches from here and then I will create new one

**Comment by Kumar-laxmi** [comment]
First save your code somewhere, then delete the old child branch and then create two new child branches (from main branch).

**Comment by Kumar-laxmi** [comment]
Branch name could be the algo. name (It is easy to identify the branch)

**Comment by neeraj542** [comment]
After making all these changes, will I need to create an issue again?

**Comment by Kumar-laxmi** [comment]
> After making all these changes, will I need to create an issue again?

No

**Comment by Kumar-laxmi** [comment]
But do tag those issue in your new PR

**Comment by neeraj542** [comment]
ok

**Comment by neeraj542** [comment]
I have created a pull request again for Added Ford-Fulkerson_Algorithm Successfully #924. Please check

**Pull request closed without merging**
