### PR TITLE
Added Modular Exponentiation in C++

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

Issue no #568 

## 👨‍💻 Changes proposed

Hey, @Kumar-laxmi I have added the Modular Exponentiation in C++ in the Maths folder. Please review my pr and merge it. Thank you!

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot (620)

### CODE REVIEW

**Review by Sanjanabharadwaj25 — APPROVED** [review]
@sumitkr2000, include the complete checklist in the PR description.

**Comment by sumitkr2000** [comment]
Done @Sanjanabharadwaj25 . Approve my pr now.

**Comment by sumitkr2000** [comment]
hello @Rishikavishnoi  @Arun9739 @siddhi-244 are you all sleeping?? this pr is open from 2 weeks now.

**Review by siddhi-244 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
@siddhi-244 sure mam :)

**Review by Arun9739 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Rishikavishnoi Kindly review this PR

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by sumitkr2000** [comment]
@Kumar-laxmi please merge this pr now

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
