### PR TITLE
Made the Prime Checker

### PR DESCRIPTION
**Pull request by Tirtharaj-Talukdar**
I wrote the C++ code I will try to implement the C and Python code soon. Please accept my pull request.

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
> I wrote the C++ code I will try to implement the C and Python code soon. Please accept my pull request.

@Tirtharaj-Talukdar  I can only merge this PR after the algorithm has been implemented in all four languages.

**Comment by Tirtharaj-Talukdar** [comment]
Is there anything available only for C++

**Comment by Kumar-laxmi** [comment]
> Is there anything available only for C++

No

**Comment by Tirtharaj-Talukdar** [comment]
> I wrote the C++ code I will try to implement the C and Python code soon. Please accept my pull request.

>Wrote the code for the other 4 languages.  Please accept my PR

**Comment by Tirtharaj-Talukdar** [comment]
Hey please check out my new commits. Thank You.

**Comment by Kumar-laxmi** [comment]
@Tirtharaj-Talukdar Just wait for some time till the PR is checked! 😁, Thanks for contributing

**Comment by Kumar-laxmi** [comment]
@Tirtharaj-Talukdar Kindly ⭐️ this PR

**Comment by Tirtharaj-Talukdar** [comment]
Thanks a Lot

**Pull request merged**
