### PR TITLE
Binary Exponentiation in Java

### PR DESCRIPTION
**Pull request by Mrudula1205**
Java code to find the exponent of a decimal and/or binary number in Java through the method of recursion.

## 🛠️ Issue Binary Exponentiation in Java

Issue no #1337 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Your PR is missing the program in C, C++ & Python

**Comment by Mrudula1205** [comment]
The program in C, C++ and Python is already there in the respective repositories.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Mrudula1205 Add output screenshots

**Comment by Mrudula1205** [comment]
@Arun9739 @Kumar-laxmi I have added screenshots of the output below.

image
image
image

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
