### PR TITLE
Create Reverse Integer

### PR DESCRIPTION
**Pull request by swastik-akhil**
## 🛠️ Issue (Reverse Integer)

Issue no #693 

## ✔️ Check List

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 👨‍💻Author

**Akhil Agrawal
   GitHub : @swastik-akhil**

### CODE REVIEW

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add comments explaining your approach

**Review by swastik-akhil — COMMENTED** [review]
This code is working well and has no issues.
Also the description of approach used is added.

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
How is this PR different from PR #963 ?

**Review by swastik-akhil — COMMENTED** [review]
I have reviewed on the codes, and have added comments describing its approach.

**Comment by swastik-akhil** [comment]
@zugzwang03 I am staring a new pull request and closing all these two #956 and #963.
I'm sorry for the inconvenience cause by multiple PR.
Thanks for your efforts.
🙂

**Pull request closed without merging**
