### PR TITLE
Create Rabinkarp_in_C.c

### PR DESCRIPTION
**Pull request by Swapnendu003**
This is the code of Rabin Karp algorithm in C language

## 🛠️ Issue (914)

Issue no #914 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes to be done:
- Place the C Program file in ```C/Pattern Matching``` folder
- Include the Java progam file
- Add screen shots of your output

**Comment by Kumar-laxmi** [comment]
@Swapnendu003 Kindly do the required changes withing next 2 days or else the PR would be closed as stale

**Comment by Swapnendu003** [comment]
> @Swapnendu003 Kindly do the required changes withing next 2 days or else the PR would be closed as stale

I have added the java file in another PR??
How to add the java file here itself.

**Comment by Kumar-laxmi** [comment]
You can do one thing:
- close all the PRs on Rabin Karp
- Save the C and Java code some where on your system
- Delete the additional branches created for rabin-karp
- Now fork a new branch from ```main``` branch
- In the new branch place both your programs
- Now open one single PR from this branch, instead of opening separate PR from separate branch containing separate programs

**Pull request closed without merging**
