### PR TITLE
Sieve of Eratosthenes in c added #173

### LINKED ISSUE #173: Sieve Eratosthenes Algorithm
**Algorithm:**  _The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million or so_

Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number. 

**Example:** 

**Input :** n =10
**Output :** 2 3 5 7 

**Input :** n = 20 
**Output:** 2 3 5 7 11 13 17 19

**Time Complexity:** O(n*log(log(n)))
**Auxiliary Space:** O(n)

@Kumar-laxmi  Please assign me this task to add this algorithm in java Maths directory

### PR DESCRIPTION
**Pull request by Sachittarway**
## 🛠️ Issue (Number):- 

Issue no #173 

## 👨‍💻 Changes proposed

 Added the Sieve of Eratosthenes Algorithm for finding prime numbers in c language.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million or so

Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number.

Example:

Input : n =10
Output : 2 3 5 7

Input : n = 20
Output: 2 3 5 7 11 13 17 19

Time Complexity: O(n*log(log(n)))
Auxiliary Space: O(n)

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Sachittarway** [comment]
@Kumar-laxmi please review it.

**Comment by zugzwang03** [comment]
> ## 🛠️ Issue (Number):-
> Issue no #173
> 
> ## 👨‍💻 Changes proposed
> Added the Sieve of Eratosthenes Algorithm for finding prime numbers in c language.
> ## ✔️ Check List (Check all the applicable boxes)
> * [✔️ ] My code follows the code style of this project.
> * [✔️ ] This PR does not contain plagiarized content.
> * [ ✔️] The title of my pull request is a short description of the requested changes.
> 
> ## 📄 Note to reviewers
> The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million or so
> 
> Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number.
> 
> Example:
> 
> Input : n =10 Output : 2 3 5 7
> 
> Input : n = 20 Output: 2 3 5 7 11 13 17 19
> 
> Time Complexity: O(n*log(log(n))) Auxiliary Space: O(n)
> 
> ## 📷 Screenshots
> image

It is advised to add few more comment lines explaining your approach towards the problem, although your code looks good, yet it is an algorithms repository, so it looks good if you explain your approach in a few comment lines as well.

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Kindly add in your approach in a few comment lines.

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by Sachittarway** [comment]
@zugzwang03 @Arun9739 @Kumar-laxmi please review and merge.

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Sachittarway Nice code, but remove the bbinary .exe file.
Rest all is fine

**Comment by Sachittarway** [comment]
@Arun9739 Done with the changes.
@Kumar-laxmi Please merge it.

**Review by Arun9739 — APPROVED** [review]
Approved !

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
