### PR TITLE
Kaprekar Number

### PR DESCRIPTION
**Pull request by pra9patil**
## 🛠️ Issue #1541 

Issue no #1541 

## 👨‍💻 Changes proposed
Added Kaprekar Number program files in c , c++ , python , java

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### C  Program Output
c_output

### CPP Program Output
cpp_output

### Java Program Output
java_output

### Python Program Output
python_output

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Rename all the files as ```Kaprekar_Number.<extension>```

**Review by pra9patil — COMMENTED** [review]
@Kumar-laxmi Sir I just updated changes , will you review please

**Review by Kumar-laxmi — COMMENTED** [review]
The code seems to be copied from https://www.geeksforgeeks.org/kaprekar-number/

Any explanation for this?

**Comment by pra9patil** [comment]
> The code seems to be copied from https://www.geeksforgeeks.org/kaprekar-number/
> 
> Any explanation for this?
@Kumar-laxmi 

No sir this is not copied code I have took the refrence of that article and done some of the changes according to my knowledge and perspective , I have used again two three resources like  Wikipedia , learningcode etc , this is my early stage of learning and making  a practical use of it . There's no any bad intention to gain a marks in wrong way and benifit me . I had a pure intention to learn new through this source and upskill my self at the beginning of my career , but sir please TRUST me I have note copied code as it is , to mentor my self I have just used the refrence , I request you to please check code one more time .

**Comment by Kumar-laxmi** [comment]
You should refer the algorithm and not the code, sorry @pra9patil but I have to close the PR since the code is exactly same

**Pull request closed without merging**
