### PR TITLE
Algo Edmonds-karp Added Successfully

### PR DESCRIPTION
**Pull request by neeraj542**
## 🛠 Issue (#718)

Issue no #718

## 👨‍💻 Changes proposed
This pull request aims to enhance the efficiency of the Edmonds-Karp algorithm implementation and broaden its applicability by adding support for the Python programming language. The proposed changes include optimized C++ code for improved performance, the addition of Python code for greater versatility, and enhanced documentation to aid developers. These updates aim to provide developers with an efficient and accessible solution for maximum flow problems in both C++ and Python environments. Please review the changes and consider merging them into the main repository.

## ✔ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
In the pseudocode, 'V' represents the number of vertices in the graph, 'residualGraph' refers to the residual capacities of the graph, and the graph represents the original 'graph' with capacities.

Thank you for reviewing this pull request. The changes include optimizations to the Edmonds-Karp algorithm implementation and the addition of Python code for improved versatility. Your feedback and suggestions are valuable to us, and we welcome any recommendations to enhance the algorithm further. We appreciate your time and collaboration in making this implementation more efficient and scalable.

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
image

Remove Ford-Fulkerson files

**Comment by neeraj542** [comment]
image

Unwanted files removed!

**Comment by neeraj542** [comment]
@Kumar-laxmi, Now you can check this repository. As per your instructions, I have removed both the files.

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Add C & Java program files too

**Comment by neeraj542** [comment]
All requested changes done @Kumar-laxmi @zugzwang03 @Arun9739

**Review by zugzwang03 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
@neeraj542 This PR would delete Ford-Fulkerson_Algorithm in C++ & Python
image

I would suggest closing this PR and deleting this branch, and in then create a new branch with only these 4 files from your side and then open a PR

**Review by 072arushi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
Kindly do the changes or else the issue would be re-assigned to some one else

**Comment by neeraj542** [comment]
@Kumar-laxmi Ok sure, I am updating it very soon.

**Pull request closed without merging**
