### PR TITLE
Dial’s Algorithm in C, C++, PYTHON, JAVA

### PR DESCRIPTION
**Pull request by anand-harsh**
## 🛠️ Issue (Number)

Issue no #1276

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Dial's algorithm is a variation of Dijkstra's algorithm that efficiently computes the shortest path in a graph with non-negative edge weights. It achieves this efficiency by using a bucket queue data structure and a technique called "dialing."

The main idea of Dial's algorithm is to process vertices based on their distance labels, starting from the smallest label. The algorithm iteratively selects the vertex with the smallest distance label from the non-empty buckets and updates the distances of its adjacent vertices if a shorter path is found. If the updated distance of a vertex changes its bucket, the vertex is moved to the corresponding bucket.

## 📷 Screenshots

dial_algorithm.c

image

dial_algorithm.cpp

image

dial_algorithm.py

image

dial_algorithm.java

image

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
It is clearly visible that the code has been plagarised from https://www.geeksforgeeks.org/dials-algorithm-optimized-dijkstra-for-small-range-weights/

Do you have any explaination for this

**Comment by anand-harsh** [comment]
> It is clearly visible that the code has been plagarised from https://www.geeksforgeeks.org/dials-algorithm-optimized-dijkstra-for-small-range-weights/
> 
> Do you have any explaination for this

I am really sorry sorry for this. Can you please reassign me these issue. I will push the non plagiarised codes please

**Comment by Kumar-laxmi** [comment]
No it is not required

**Comment by Kumar-laxmi** [comment]
But sorry @anand-harsh I have unassign you from all the issues you have been assigned

**Comment by anand-harsh** [comment]
> But sorry @anand-harsh I have unassign you from all the issues you have been assigned

Sorry Sir, I will surely replace the code with fresh ones.

**Comment by Kumar-laxmi** [comment]
Actually the scale of plagiarism is too high, something could be done if it was limited to one PR. Sorry but I need to revert all merged PRs and close all unmerged PRs.

**Comment by anand-harsh** [comment]
> Actually the scale of plagiarism is too high, something could be done if it was limited to one PR. Sorry but I need to revert all merged PRs and close all unmerged PRs.

Please Sir, I was just trying to learn
I will code the fresh ones and push.

**Comment by anand-harsh** [comment]
> Actually the scale of plagiarism is too high, something could be done if it was limited to one PR. Sorry but I need to revert all merged PRs and close all unmerged PRs.

can I create new issues for them and upload fresh codes?

**Comment by Kumar-laxmi** [comment]
> > Actually the scale of plagiarism is too high, something could be done if it was limited to one PR. Sorry but I need to revert all merged PRs and close all unmerged PRs.
> 
> can I create new issues for them and upload fresh codes?

not required

**Comment by anand-harsh** [comment]
> > > Actually the scale of plagiarism is too high, something could be done if it was limited to one PR. Sorry but I need to revert all merged PRs and close all unmerged PRs.
> > 
> > 
> > can I create new issues for them and upload fresh codes?
> 
> not required

can i create issue for other algorithms? new ones?

**Comment by Kumar-laxmi** [comment]
That you can

**Comment by Kumar-laxmi** [comment]
But on a condition that you won't repeat this in future, because such violation can lead to ban from this event

**Comment by anand-harsh** [comment]
> @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues

I promise this wont be repeated.
I am really sorry.

**Comment by Kumar-laxmi** [comment]
@anand-harsh Could you help me find more plagarised PRs

**Comment by anand-harsh** [comment]
> @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues


> @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues

Can I open the same issues u closed whose PR was not yet reviewed?

**Comment by anand-harsh** [comment]
> @anand-harsh Could you help me find more plagarised PRs.

Yes sure

**Comment by Kumar-laxmi** [comment]
> > @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues
> 
> > @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues
> 
> Can I open the same issues u closed whose PR was not yet reviewed?

Leave those, you can open new ones and if you find it difficult with Intermediate or Advanced algos then please raise beginner issues only

**Comment by anand-harsh** [comment]
> > > @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues
> > 
> > 
> > > @anand-harsh But on a condition that you won't repeat this in future, because such violation can lead to ban from this event & if you can report such plagarism on algorithm channel then only I will assign you any more issues
> > 
> > 
> > Can I open the same issues u closed whose PR was not yet reviewed?
> 
> Leave those, you can open new ones and if you find it difficult with Intermediate or Advanced algos then please raise beginner issues only

Can I raise the issue on the plagarised issues of other users?

**Comment by Kumar-laxmi** [comment]
Yeah, but you need to prove it first. If you find such PRs report on discord's algorithm channel

**Comment by anand-harsh** [comment]
> Yeah, but you need to prove it first. If you find such PRs report on discord's algorithm channel

Okay Sir

**Pull request merged**
