### PR TITLE
Added cocktail sorting in cpp

### PR DESCRIPTION
**Pull request by ArgyPorgy**
Issue no #244 

## 👨‍💻 Changes proposed

Added the cocktail sorting 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi added the cocktail sorting, please do check it.

## 📷 Screenshots
Screenshot (1465)
Screenshot (1466)

### CODE REVIEW

**Review by siddhi-244 — APPROVED** [review]

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Mention it's time and space complexity at the beginning of the code inside comments

**Comment by ArgyPorgy** [comment]
done, please check now @Rancho2002

**Review by Rancho2002 — APPROVED** [review]
Perfect

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Take the array elements input from user, instead of giving directly in program

**Comment by ArgyPorgy** [comment]
done @Arun9739 please check now

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
