### PR TITLE
Extended Euclidean Algorithm in C, C++, Java and Python

### LINKED ISSUE #451: Extended Euclidean Algorithm
**Is your feature request related to a problem? Please describe.**
Extended Euclidean Algorithm is used to find modular multiplicative inverse of a number which is used in cryptography and network security.

**Describing the problem**
We know that,

Inverse of a number (A) will be = A^-1  or we can say that A * A^-1 will be equal to 1

but incase of modular multiplicative inverse of a number (A) is when the expression below is true

 (A*A^-1) mod (C) is equal to 1

from the expression we can say that A^-1 will be the inverse of A.
 
On top of that we have an important point that modular multiplicative inverse exists when A and C are **coprime**  to eachother or we can also say the gcd of A and C should be equal to **1**

**Additional context**
I will solve this issue in Java, C++, Python and C

### PR DESCRIPTION
**Pull request by Dharnish38**
`Closes #451`
## 🛠️ Issue (#451)

Issue no #451 ( Java, C++, Python, C)

## 👨‍💻 Changes proposed

Added the Extended Euclidean Algorithm which is used to calculate the modular multiplicative inverse in the languages of C, C++, Java, and Python

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi, since I have asked you to assign this task. I have completed implementing it using the languages of C, C++, Java and Python.

So, I request you to once review, my PR, and then merge it.

Thank you!!! for letting me contribute to the repo.
## 📷 Screenshots
C :
Screenshot (630)

C++ :
Screenshot (629)

Java :
Screenshot (628)

Python :
Screenshot (632)

I hope you will merge this PR, so that I can contribute to your other issues also 👍
Thank You !!!!!

### CODE REVIEW

**Review by Rancho2002 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Could you name all files as "Extended_Euclidean_Algorithm"

**Comment by Dharnish38** [comment]
@Kumar-laxmi I have changed the file name as per your suggestions.

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
The java & python file are not placed in their respective folders, kindly place them in their appropriate folders

**Comment by Dharnish38** [comment]
@Kumar-laxmi I have changed the java and python files to the appropriate locations, Please review it, Sorry for the inconvenience caused.

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
