### PR TITLE
Adding exp search

### PR DESCRIPTION
**Pull request by kritika2313**
## 🛠️ Issue (1097)

Issue no #1097 

## 👨‍💻 Changes proposed

Added Exponential searching algorithms

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@kritika2313 take input from user in program

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly resolve the **Merge Conflict**

**Comment by kritika2313** [comment]
could you explain me pls want else i have to do since i am new to open source .
i have deleted these chinese remainder  file from this pull request.

**Comment by Kumar-laxmi** [comment]
I think you need to upstream your branch to repo's ```main``` branch

**Review by zugzwang03 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
> then it will create another pull request so is it fine? since the merging command is showing already up to date.

While creating another pull request reference this PR so that it doesn't go another round of review process

**Comment by kritika2313** [comment]
i have made the changes

**Comment by Kumar-laxmi** [comment]
> i have made the changes

image
Still the conflict is there

**Comment by kritika2313** [comment]
i think i should close this pr and open a new one then

**Review by zugzwang03 — APPROVED** [review]

**Comment by kritika2313** [comment]
should i close this as i am not able to solve this conflicting file issue

**Comment by kritika2313** [comment]
i have  made a new pr pls see that

**Comment by Kumar-laxmi** [comment]
Then close this

**Pull request closed without merging**
