### PR TITLE
tower of hanoi

### PR DESCRIPTION
**Pull request by ADITYA0714**
I have uploaded the code of tower of hanoi.
my issue id is:#272
In tower of hanaoi rings/ disks are stack are one above the other placing the largest at bottom and increasing in order

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Move this program to ```Stack``` folder

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
move this file to the stack folder.

**Comment by ADITYA0714** [comment]
There is no stack folder in algorithm repository

**Comment by zugzwang03** [comment]
> There is no stack folder in algorithm repository

Check carefully 
There is stack folder in the C++ directory

**Comment by zugzwang03** [comment]
> There is no stack folder in algorithm repository

There is a stack folder in the C directory of the algorithms folder.

**Comment by ADITYA0714** [comment]
i have moved to stack folder in c directory

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@ADITYA0714  You can add comments explaining your approach.

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@ADITYA0714 kindly remove the fibborecursive.py program file from this PR

**Comment by Kumar-laxmi** [comment]
Due to inactivity, I am closing this PR

**Pull request closed without merging**
