### PR TITLE
BFS DFS in java Issue-186

### PR DESCRIPTION
**Pull request by MansiBhayade**
## 🛠️ Issue (Number)

Issue no #186 

## 👨‍💻 Changes proposed

Added bfs.java and dfs.java file

## ✔️ Check List (Check all the applicable boxes) 

- ✔️ My code follows the code style of this project.
- ✔️ This PR does not contain plagiarized content.
- ✔️ The title of my pull request is a short description of the requested changes.

### This program takes graph input in the form of adjacency list from user and states BFS & DFS for the graph.

BFS in java
image

DFS in java
image

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Add comments in the code

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add some comments to explain your logic.
Remove the .class files.

**Comment by MansiBhayade** [comment]
Added comments and removed .class file....please review

**Review by Rancho2002 — APPROVED** [review]
Great job

**Review by Rancho2002 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Good !

**Pull request merged**
