### PR TITLE
Add Valid Anagram Problem Solution

### PR DESCRIPTION
**Pull request by shubhanshurav**
## 🛠️ Issue (Number) : 

- Issue no [#788 ](https://github.com/Kumar-laxmi/Algorithms/issues/788#issue-1735510638)

## ✔️ Check List (Check all the applicable boxes) 

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title of my pull request is a short description of the requested changes.

## Ploblem Name: Valid Anagram
**Description**
- Given two strings s and t, return true if t is an anagram of s, and false otherwise.
- An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

 

- Example 1:

Input: s = "anagram", t = "nagaram"
Output: true
Example 2:

- Input: s = "rat", t = "car"
Output: false

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@shubhanshurav Kindly implement this algo in all four languages since it is easy algo

**Comment by shubhanshurav** [comment]
Hi @Kumar-laxmi, I have added the solution in C, C++, Java & Pyhton.

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
Is this code copied from LeetCode?

**Comment by Kumar-laxmi** [comment]
Most of the code are similar to code provided in https://leetcode.com/problems/valid-anagram/solutions/

And I think you are well aware that LeetCode problems are not accepted, in addition to that the codes are plagarised

**Pull request closed without merging**
