### PR TITLE
Algorithm for converting an Binary number to a Decimal number and Decimal number to Binary number

### PR DESCRIPTION
**Pull request by viveksondhiya**
## 🛠️ Issue (Number)

Issue no #270

## 👨‍💻 Changes proposed
Adding the Algorithms to convert binary numbers to decimal value and the decimal value to binary number

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Please explain your approach

**Review by viveksondhiya — COMMENTED** [review]
Added the Approach to solve the problem

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
Approved

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please mention the Issue no of LCS and Convertion.java & for Binary to decimal OR decimal to binary you can implement it in one file using menu driven approach

**Review by zugzwang03 — APPROVED** [review]

**Comment by viveksondhiya** [comment]
> Please mention the Issue no of LCS and Convertion.java & for Binary to decimal OR decimal to binary you can implement it in one file using menu driven approach
LCS is issue no is #286 
and 
Convertion.java & for Binary to decimal OR decimal to binary is #270

**Comment by viveksondhiya** [comment]
review please..

**Comment by Kumar-laxmi** [comment]
> review please.. @Kumar-laxmi

First resolve the CodeFactor issue

**Comment by viveksondhiya** [comment]
@Kumar-laxmi @Sanjanabharadwaj25 @zugzwang03 why it is not merged ..is there any problem

**Pull request merged**
