### PR TITLE
Added program for perfect number in all four languages

### PR DESCRIPTION
**Pull request by palaksinghania05**
## 🛠️ Issue #501 

Issue no #501 

## 👨‍💻 Changes proposed

Added perfect number program in C, C++, Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image
image
image
image

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your algorithm

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Explain approach in comments

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add a output screenshot

**Review by zugzwang03 — APPROVED** [review]

**Comment by palaksinghania05** [comment]
@072arushi done

**Comment by palaksinghania05** [comment]
@Arun9739 where to add screenshots

**Comment by Arun9739** [comment]
> ## 🛠️ Issue #501
> Issue no #501
> 
> ## 👨‍💻 Changes proposed
> Added perfect number program in C, C++, Java and Python
> 
> ## ✔️ Check List (Check all the applicable boxes)
> * [x]  My code follows the code style of this project.
> * [x]  This PR does not contain plagiarized content.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ## 📄 Note to reviewers
> ## 📷 Screenshots

@palaksinghania05 add here

**Review by 072arushi — APPROVED** [review]

**Comment by palaksinghania05** [comment]
@Arun9739 done

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
