### PR TITLE
Matrix Chain Multiplication C++ Code

### PR DESCRIPTION
**Pull request by shailja2727**
## 🛠️ Issue (Number)

Issue no #189 

## 👨‍💻 Changes proposed
Matrix Chain Multiplication C++ Code

## ✔️ Check List (Check all the applicable boxes) 

- [ ✅] My code follows the code style of this project.
- [✅ ] This PR does not contain plagiarized content.
- [ ✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi Please accept my pull request
## 📷 Screenshots

### CODE REVIEW

**Comment by shailja2727** [comment]
> Add comments to explain your approach

I have added the comments to explain the approach .Please respond if any further changes needed

**Comment by Kumar-laxmi** [comment]
@shailja2727 Why are you implementing Matrix chain in this PR and PR #331

**Comment by shailja2727** [comment]
> @shailja2727 Why are you implementing Matrix chain in this PR and PR #331

In PR #331 Activity Selection Greedy problem is being implemented

**Comment by Kumar-laxmi** [comment]
@shailja2727 Please don't open a PR for issues that haven't been assigned to you

**Pull request closed without merging**
