### PR TITLE
Create tower of hanoi in c++

### PR DESCRIPTION
**Pull request by Durgesh4993**
## 🛠️ Issue (Number)

Issue no #272 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

image

## 📷 Screenshots
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Place this file in folder named ```Stack```

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@Durgesh4993 Please write comments to explain the logic.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Move this file to stack folder, add some comments to the code explaining the approach and update the readme in stack file accordingly

**Review by Rishikavishnoi — COMMENTED** [review]
@Durgesh4993 move your program to the Stack folder

**Comment by Kumar-laxmi** [comment]
I am closing this PR due to inactivity

**Pull request closed without merging**
