### PR TITLE
Wave sort in C++ #225

### PR DESCRIPTION
**Pull request by atul1510**
## 👨‍💻 Changes proposed
Added wave sort algorithm in C++ 

## ✔️ Check List 
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes

## 📷 Screenshots
Screenshot (114)

### CODE REVIEW

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- Update the file name to ```Wave_Sort.cpp```
- Please include the output screen-shot

**Comment by atul1510** [comment]
Done with Changes.
And this is the output screenshot.
Screenshot (115)

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@atul1510 Please add comments to explain your approach.

**Comment by atul1510** [comment]
Added the comments that explains the approach of algorithm of wave sort

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Nice work

**Pull request merged**
