### PR TITLE
Added Bloom Filter Algorithm in C++ and Python

### PR DESCRIPTION
**Pull request by thakurdiwakar**
## 👨‍💻 Changes proposed

Added Bloom Filter Algorithm in C++ and Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (109)
Screenshot (110)

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add code in C and Java as well

**Comment by thakurdiwakar** [comment]
> Add code in C and Java as well

Another contributor has been assigned for C and Java. Please review issue #997 for more information.

**Comment by Kumar-laxmi** [comment]
> Add code in C and Java as well

@072arushi This issue is assigned to @thakurdiwakar only in C++ & Python, so kindly review

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
The code has been copied from https://www.geeksforgeeks.org/bloom-filters-introduction-and-python-implementation/

**Pull request merged**
