### PR TITLE
Adding Smith waterman Algorithm 

### PR DESCRIPTION
**Pull request by Mayureshd-18**
Issue no #1605 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Python - 
WhatsApp Image 2023-07-19 at 00 13 38

C-
WhatsApp Image 2023-07-19 at 00 18 59

C++ - 
WhatsApp Image 2023-07-19 at 00 20 08

Java - 
WhatsApp Image 2023-07-19 at 00 22 16

### CODE REVIEW

**Comment by Mayureshd-18** [comment]
@Kumar-laxmi  Please review this PR.

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Shift the programs to ```Dynamic Programming``` folder

**Review by Arun9739 — APPROVED** [review]

**Comment by Mayureshd-18** [comment]
@Kumar-laxmi I
 have shifted the files from string to Dynamic programming as requested.

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by Mayureshd-18** [comment]
@Kumar-laxmi Please review this PR and merge it

**Pull request closed without merging**
