### PR TITLE
Linear Regression in Java

### PR DESCRIPTION
**Pull request by sha0urya**
Create Linear Regression in Java.

## 🛠️ Issue (Number)

Issue no #681 

## 👨‍💻 Changes proposed

I have written the code for Linear Regression in Java.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Linear regression is related to machine learning. It is one of the fundamental and widely used techniques in machine learning and statistical modeling for predictive analysis.

Linear regression is a supervised learning algorithm that models the relationship between a dependent variable (also called the target variable) and one or more independent variables (also called features or predictors). The goal of linear regression is to find the best-fitting line or hyperplane that represents the relationship between the variables.

In machine learning, linear regression is often used for tasks such as:

> Predicting a numerical value based on given input features. For example, predicting house prices based on factors like size, number of rooms, and location.

> Analyzing the relationship between variables and understanding their influence on each other.

> Feature selection or dimensionality reduction by determining the significance of different features in predicting the target variable.

Linear regression is considered a simpler and more interpretable model compared to more complex machine learning algorithms. However, it forms the foundation for more advanced regression techniques and plays a crucial role in various machine-learning applications and pipelines.

## 📷 Screenshots

fe6f25eb9669e67aa5f87ae5454392a2e86b9dec

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
It was clearly informed not to use any ML Libraries, kindly use theory and logic to implement. Kindly do the following changes within 5 days or else the issue would be reassigned to some one else.

**Comment by sha0urya** [comment]
Apologies for the previous mistake.

1. Simple API: The implementation provides a simple API with train() and predict() methods to train the model and make predictions.

2. Training and Prediction Methods: The train() method trains the linear regression model using the provided input data, and the predict() method makes predictions for new input values.

3. Support for Multiple Variables: The implementation currently supports a single independent variable. To support multiple variables. This code allows you to provide a 2D array x with multiple variables, where each row represents a data point and each column represents a different variable. The train() method calculates the means of each variable in x, iterates over the variables to calculate the slopes, and stores them in the slopes array. The predict() method accepts an array x containing the values of the variables for prediction.

4. Performance Optimization: This basic implementation does not include specific performance optimization techniques. However, you can enhance the performance by employing techniques such as matrix operations or parallel computation for large datasets.
 
5. Flexibility and Extensibility: The code can be extended and customized according to your requirements. You can add additional methods or modify existing ones to suit your needs.

6. Documentation and Examples: The code includes comments to explain the purpose of each method and how they work. You can further enhance the documentation by adding comments to describe the class, methods, and parameters.

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please implement this on a bigger dataset with minimum 15-20 points for better validation of model

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@sha0urya Add a output screenshot

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
