### PR TITLE
 Feature : Morris Traversal #183

### LINKED ISSUE #183: Morris Traversal Algorithm
**Is your feature request related to a problem? Please describe.**
Morris traversal is an important algorithm in trees in O(n) time complexitiy.

**Describe the solution you'd like**
I will code it in c++ language in the efficient way.

**Additional context**
I will be providing screenshots of output as well as short notes on it.

### PR DESCRIPTION
**Pull request by Sachittarway**
## 🛠️ Issue (Number) `Closes #183 `

Issue no #183

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️ ] My code follows the code style of this project.
- [ ✔️ ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Added Morris Traversal algorithm for tree traversal with proper explanation in it 

Programmed in C++ 
## 📷 Screenshots
image

### CODE REVIEW

**Comment by Sachittarway** [comment]
@Kumar-laxmi Review Requested

**Comment by Kumar-laxmi** [comment]
@Sachittarway your codes match the codes given on website: _https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion-and-without-stack/_, could you justify

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please implement preorder and postorder (eg. in menu driven way)

**Comment by Sachittarway** [comment]
> @Sachittarway your codes match the codes given on website: _https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion-and-without-stack/_, could you justify

See logic can be same but the way I have done is unique for example like in line 30 the function I have created is using vector but in gfg it is not done by using vector so the implementation is totally different. Also if you see the explanations and variables , functions are totally different as it is all done by me. Also if we see the main function the printing process is also totally different form gfg.

**Comment by Sachittarway** [comment]
> Please implement preorder and postorder (eg. in menu driven way)

I will be doing it soon and will merge.

**Comment by Sachittarway** [comment]
image
Done with the changes @Kumar-laxmi

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove the ```.exe``` file

**Comment by Sachittarway** [comment]
@Kumar-laxmi Changes done || Merge Requested

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
