### PR TITLE
Intersection of two linked list in C++ and Matrix chain Multiplication in C++

### PR DESCRIPTION
**Pull request by NikitaGupta-17**
✔️ Check List (Check all the applicable boxes)

 My code follows the code style of this project.

 This PR does not contain plagiarized content.

 The title of my pull request is a short description of the requested changes.

📄 Note to reviewers
Issue no #189
Issue no #190

In this we take 2 linked input from user and the elements which are common to them are printed.
The time complexity of the code in O(n^2)
The user can enter the linked in any order ( i.e. sorted order is not required)

I consider the first element of first linked list and compare it with all elements of second linked if it is present then the element is printed. The process is repeated for all the elements of first linked list.
#Screenshots
s1

In matrix chain multiplication me are given no of matrices and we have to multiply matrices such that the total cost is minimum i.e. we have to find the order of matrix multiplication.
This problem can be solved by the following process-
1) M i..j=M i.. k * M K+1..j ,i<=K<=j-1
1)Find min[i,j] = min[I,K] + min[K+1,j] + Multiplication cost of Mi...K and MK+1...j
Mi =Di-1 Di
Mk = D k-1 Dk
Mj= Dj-1 Dj
min[i,j] =min[I,k]+min[k+1,j]+Di-1*Dk*Dj where i<j
min[I,j]=0 when i=j
Screenshot_20230116-212119_Chrome

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@NikitaGupta-17 If your PR is trying to solve two or more issues please mention their issue number and update the title accordingly

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Try to add comments explaining your approach

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add a screenshot for the Matrix chain multiplication

**Comment by Arun9739** [comment]
@NikitaGupta-17 Plz add a screenshot of the output run by your code(for matrix chain multiplication), not the manual calculation.

**Comment by NikitaGupta-17** [comment]
Now added the screenshot of the output.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add comments explaining the logic.
See other codes in the repo for example.

**Comment by siddhi-244** [comment]
> Try to add comments explaining your approach

Please do the needful @NikitaGupta-17

**Comment by NikitaGupta-17** [comment]
@siddhi-244 Please review I have added the comments now.

**Review by siddhi-244 — APPROVED** [review]

**Comment by NikitaGupta-17** [comment]
@Arun9739 @072arushi 
Please review I have added the comments now.

**Review by 072arushi — APPROVED** [review]

**Comment by NikitaGupta-17** [comment]
@Arun9739 Please review the code.

**Review by Arun9739 — APPROVED** [review]
Approved !

**Comment by NikitaGupta-17** [comment]
@Kumar-laxmi Please merge this pull request.

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
