### PR TITLE
Quick sort in C

### PR DESCRIPTION
**Pull request by Abhilash1781**
## 🛠️ Issue (120)

Issue no #120

## 👨‍💻 Changes proposed
Uploaded the Quick_Sort.c file
Updated the Readme file
Updated the Quick_Sort.c based on the suggestions provided  by @Arun9739 sir

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Actually the clock() function returns the number of clock ticks since passed since the program is executed . 
It has no parameters . 
In order to return the value of clock() function in "SECONDS" , I have used CLOCKS_PER_SEC . It defines the number of clock ticks per second . There are total of 10,00,000 clock ticks per second . 

The formula -->   **seconds = clockticks/CLOCKS_PER_SECOND**

## 📷 Screenshots
Screenshot from 2023-01-13 20-48-08

### CODE REVIEW

**Comment by Abhilash1781** [comment]
@Arun9739 @zugzwang03

**Review by Arun9739 — APPROVED** [review]
Very nice 
Approved

**Review by siddhi-244 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please add Quick Sort to ```Sorting``` folder

**Comment by Abhilash1781** [comment]
@Kumar-laxmi  sir I have deleted the file in Divide and conquer folder and uploaded it in Sorting folder . Please check

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please update your branch to upstream

**Comment by Abhilash1781** [comment]
@Kumar-laxmi

**Comment by Abhilash1781** [comment]
@Kumar-laxmi Could you please merge the pull request  .

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Abhilash1781 Please tell your name on discord along with your GitHub username and this PR so that I can forward your score to SWOC team

**Comment by Kumar-laxmi** [comment]
> @Abhilash1781 Please tell your name on discord along with your GitHub username and this PR so that I can forward your score to SWOC team

DM me

**Pull request merged**
