### PR TITLE
Least Recently Used (LRU) | Caching in C, C++, PYTHON, JAVA

### PR DESCRIPTION
**Pull request by anand-harsh**
## 🛠️ Issue (Number)

Issue no #1277 

## 👨‍💻 Changes proposed

Added Least Recently Used (LRU) in C, C++, PYTHON, JAVA

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

In Least Recently Used (LRU) algorithm is a Greedy algorithm where the page to be replaced is least recently used. The idea is based on locality of reference, the least recently used page is not likely

## 📷 Screenshots

leastRecentlyUsed.c

image

leastRecentlyUsed.cpp

image

leastRecentlyUsed.py

image

leastRecentlyUsed.java

image

### CODE REVIEW

**Comment by anand-harsh** [comment]
@Kumar-laxmi please review this PR

**Comment by anand-harsh** [comment]
@Kumar-laxmi kindly review this PR please

**Comment by anand-harsh** [comment]
@Kumar-laxmi please review the PR

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Just name the files as LRU

**Review by zugzwang03 — APPROVED** [review]

**Comment by anand-harsh** [comment]
@Kumar-laxmi changes made

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Pull request closed without merging**
