### PR TITLE
Added Linear Regression (Machine Learning) implementation in Python

### LINKED ISSUE #68: Implement Linear Regression (without Library)
Implement Linear Regression in the following languages:
- C
- C++
- Java
- Python

### PR DESCRIPTION
**Pull request by stiwari-ds**
## 🛠️ Issue (Number)
Issue no #68

## 👨‍💻 Changes proposed
1. Added linear regression implementation (using closed-form solution) in Python
2. Added dataset and README to demonstrate usage.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Code:
code1
code2
code3

Outputs:
help_output
demo_output

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please include the scatter plot and its regression line

**Comment by stiwari-ds** [comment]
> Please include the scatter plot and its regression line

Sure, I can add another demo dataset with only one independent variable so that it can be visualised as a scatter plot and regression line.

But the algorithm extends to multiple independent variables, so adding a common visualization function for n-dimensions will not be possible.

**Comment by Kumar-laxmi** [comment]
> > Please include the scatter plot and its regression line
> 
> Sure, I can add another demo dataset with only one independent variable so that it can be visualised as a scatter plot and regression line.
> 
> But the algorithm extends to multiple independent variables, so adding a common visualization function for n-dimensions will not be possible.

You can work on dataset with 2 independent and 1 dependent variable and visualise in 3D

**Comment by stiwari-ds** [comment]
> > > Please include the scatter plot and its regression line
> > 
> > 
> > Sure, I can add another demo dataset with only one independent variable so that it can be visualised as a scatter plot and regression line.
> > But the algorithm extends to multiple independent variables, so adding a common visualization function for n-dimensions will not be possible.
> 
> You can work on dataset with 2 independent and 1 dependent variable and visualise in 3D

Yes, I will do that. Can include visualization for 2D as well as 3D.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi I have added the requested feature for visualizing regression fit. Rearranged the folder structure to incorporate the new feature. Updated README to include screenshots of demo usage.

Code snippet for the new feature:
code4

Please review the same and let me know if any changes are required.

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by stiwari-ds** [comment]
@Kumar-laxmi @Arun9739 @zugzwang03 Please review. Thanks.

**Review by Arun9739 — APPROVED** [review]
Wonderful !
Approved

**Comment by zugzwang03** [comment]
> @Kumar-laxmi @Arun9739 @zugzwang03 Please review. Thanks.

Well drafted!
Approved.

**Comment by stiwari-ds** [comment]
> > @Kumar-laxmi @Arun9739 @zugzwang03 Please review. Thanks.
> 
> Well drafted! Approved.

Thank you.
Could you please check if your review went through? From my side it doesn't show you as a reviewer.

**Comment by zugzwang03** [comment]
> > > @Kumar-laxmi @Arun9739 @zugzwang03 Please review. Thanks.
> > 
> > 
> > Well drafted! Approved.
> 
> Thank you. Could you please check if your review went through? From my side it doesn't show you as a reviewer.

You tagged me to review, so I did so.

**Comment by stiwari-ds** [comment]
> > > > @Kumar-laxmi @Arun9739 @zugzwang03 Please review. Thanks.
> > > 
> > > 
> > > Well drafted! Approved.
> > 
> > 
> > Thank you. Could you please check if your review went through? From my side it doesn't show you as a reviewer.
> 
> You tagged me to review, so I did so.

Yes, thank you for the review. But I think it was not counted as a review in the PR.

review

No issue if it is not formally required. I just thought it might be needed before merging the PR.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi @Rancho2002 @Rishikavishnoi Requesting a review. Thanks.

**Review by siddhi-244 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
