### PR TITLE
Rabin Karp, Back Tracking Algorithm (P1, P2, P3, P4, P5, P6, P7, P8, P9)

### PR DESCRIPTION
**Pull request by Priyanshu-Singh-1**
## 🛠️ Issue (Number)

Issue no #96 (Java)
Issue no #181 (C++ Problem Statement - 1)
Issue no #181 (C++ Problem Statement - 2)
Issue no #181 (C++ Problem Statement - 3)
Issue no #181 (C++ Problem Statement - 4)
Issue no #181 (C++ Problem Statement - 5)
Issue no #181 (C++ Problem Statement - 6)
Issue no #181 (C++ Problem Statement - 7)
Issue no #181 (C++ Problem Statement - 8)
Issue no #181 (C++ Problem Statement - 9)

## ✔️ Check List (Check all the applicable boxes) 

- ✔️My code follows the code style of this project.
- ✔️ This PR does not contain plagiarized content.
- ✔️ The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi 
I have made this OR for the given respective issue.

## 📷 Screenshots
Issue no #96 
image

Issue no #181 - Problem Statement - 1
image

Issue no #181 - Problem Statement - 2
image

Issue no #181 - Problem Statement - 3
image

Issue no #181 - Problem Statement - 4
image

Issue no #181 (C++ Problem Statement - 5)
image

Issue no #181 (C++ Problem Statement - 6)
image

Issue no #181 (C++ Problem Statement - 7)
image

Issue no #181 (C++ Problem Statement - 8)
image

Issue no #181 (C++ Problem Statement - 9)
image

### CODE REVIEW

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

I have made the contribution for the respective issue. And there are no conflicts as of now. Hope you review it and merge the file. I have also attached the screenshot of the above code in java

**Review by Kumar-laxmi — COMMENTED** [review]
Could you explain what changes are you doing apart from backtracking and rabin karp in your commit

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes required:
- Remove folder ```.vscode```
- Please try to implement all Backtracking problems
- And mention all changes in you description along with their output screen-shot so that it can be easy to review

**Comment by Priyanshu-Singh-1** [comment]
> Could you explain what changes are you doing apart from backtracking and rabin karp in your commit

@Kumar-laxmi 

The changes that you are seeing in files changed section, is caused because I have synched the repo to its latest version. So before making this PR, I have done this, due to which it is showing like that.

If you believe there is some error, you can see any of the respective file in your repo, it is present there. It is showing changes in mine due to synching and nothing else.

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
contributing
Actually, my exams are going on, so I will not be able to contribute these days. So, I request you to not un-assign me this issue, and all the other issues that have been assigned to me.

I will again start contributing once my exams end!

Hope you consider this! Thank you!

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi @072arushi @Sanjanabharadwaj25 I have added the remaining backtracking algorithms, Please have a look

**Comment by Priyanshu-Singh-1** [comment]
@Sanjanabharadwaj25 @072arushi @zugzwang03  Why its showing a codefactor issue, in that it is showing a Complexity factor:

image

What does that mean, Is it related to something?

**Comment by Sanjanabharadwaj25** [comment]
> @Sanjanabharadwaj25 @072arushi @zugzwang03 Why its showing a codefactor issue, in that it is showing a Complexity factor:
> 
> image
> 
> What does that mean, Is it related to something?

It means that the method you have defined is complex and can be simplified. For example, in isSafe method, you don't need to pass variables 'top' and 'left', 'bottom' and 'right' arrays. It has no usage in the method.

**Comment by Priyanshu-Singh-1** [comment]
> > @Sanjanabharadwaj25 @072arushi @zugzwang03 Why its showing a codefactor issue, in that it is showing a Complexity factor:
> > image
> > What does that mean, Is it related to something?
> 
> It means that the method you have defined is complex and can be simplified. For example, in isSafe method, you don't need to pass variables 'top' and 'left', 'bottom' and 'right' arrays. It has no usage in the method.

Okay I will make the necessary changes, and will update the PR

**Comment by Priyanshu-Singh-1** [comment]
@Sanjanabharadwaj25 I have rechecked the code, the point that you have mentioned is not valid here, because the arrays that I have declared here are being used out in both the function.

Also, this is the low complexity level issue, and it is not related to any branch/PR related issue. It showing that the method have been used is complex.

But for the Magnet Puzzle Solution, using backtracking is already a very complex task to do. It is not like basic backtracking.

So, @Sanjanabharadwaj25 what should I do now?

**Comment by Sanjanabharadwaj25** [comment]
> @Sanjanabharadwaj25 I have rechecked the code, the point that you have mentioned is not valid here, because the arrays that I have declared here are being used out in both the function.
> 
> Also, this is the low complexity level issue, and it is not related to any branch/PR related issue. It showing that the method have been used is complex.
> 
> But for the Magnet Puzzle Solution, using backtracking is already a very complex task to do. It is not like basic backtracking.
> 
> So, @Sanjanabharadwaj25 what should I do now?

Oh yeah, my bad! Sorry, I was mistaken.  As it involves backtracking some methods are bound to be complex. 
@Priyanshu-Singh-1 you can proceed with this PR.

**Comment by Priyanshu-Singh-1** [comment]
Thank you @Sanjanabharadwaj25 for your review!

@Kumar-laxmi you can merge the PR as the code have been reviewed

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1 Resolve the merge conflict

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi  I have resolved the merge conflicts. I request you to kindly merge it!

Thank you!

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
You have mentioned issue number for **Backtracking algorithm** & **Rabin Karp** but instead made changes to multiple files, so kindly close this PR and open a separate fresh PR for individual issues so that it is easy to evaluate code and keep track of changes

**Comment by Kumar-laxmi** [comment]
It is very difficult to review such a big PR

**Comment by Priyanshu-Singh-1** [comment]
> It is very difficult to review such a big PR

@Kumar-laxmi for me also it is very difficult to do so again because there are many changes already made in this repo.

I hope you merge this PR

**Comment by Priyanshu-Singh-1** [comment]
> It is very difficult to review such a big PR

Also @Kumar-laxmi all PRs have been already reviewed by other reviewers. You can look into the previous chats for the references

**Comment by Priyanshu-Singh-1** [comment]
> You have mentioned issue number for **Backtracking algorithm** & **Rabin Karp** but instead made changes to multiple files, so kindly close this PR and open a separate fresh PR for individual issues so that it is easy to evaluate code and keep track of changes

I have done this similarly for the previous time also therefore, there are changes reflected being reflected in this PR. Also, the files that yous see have changed, are my old PRs only. These are all the changes that I have done in my previous issues. Therefore you are seeing this lot of file changes

**Pull request closed without merging**
