### PR TITLE
Added Implement Trie

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

Issue no #529 

## 👨‍💻 Changes proposed

Hey, @Kumar-laxmi I have added the Implement Trie Algorithm to this repo. Please review y pr and merge it. Thank you!

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Screenshot (586)

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Take input from user, instead of giving it in program

**Review by 072arushi — APPROVED** [review]

**Comment by sumitkr2000** [comment]
Done bro @Arun9739

**Review by Arun9739 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
@Kumar-laxmi Please merge my pr. Thank you!

**Comment by sumitkr2000** [comment]
@Kumar-laxmi Please merge my pr. Thank you!

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Place the program file in ```Tree``` folder

**Comment by sumitkr2000** [comment]
@Kumar-laxmi Bro its the implementation of trie so I have created another folder named Trie.

**Comment by sumitkr2000** [comment]
Bro its the implementation of trie so I have created another folder named Trie.

**Comment by sumitkr2000** [comment]
@Kumar-laxmi  it's the implementation of Trie, not tree. Still, do you want me to add this to the tree folder?

**Comment by sumitkr2000** [comment]
@Kumar-laxmi it's the implementation of Trie, not tree. Still, do you want me to add this to the tree folder?

**Comment by sumitkr2000** [comment]
@Kumar-laxmi it's the implementation of Trie, not tree. Still, do you want me to add this to the tree folder?

**Comment by zugzwang03** [comment]
> @Kumar-laxmi it's the implementation of Trie, not tree. Still, do you want me to add this to the tree folder?

Trie is a prefix tree, so add it there.

**Pull request merged**
