### PR TITLE
Grundy num

### PR DESCRIPTION
**Pull request by patnaikankit**
## 🛠️ Issue (826)

Issue no #826

## 👨‍💻 Changes proposed
In this repo, I added grundy numbers in C, C++, Python, and Java.

## ✔️ Check List (Check all the applicable boxes) 

- [ +] My code follows the code style of this project.
- [ +] This PR does not contain plagiarized content.
- [ +] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@patnaikankit Add a output screenshots

**Comment by patnaikankit** [comment]
C Output - 
Screenshot (38)

C++ Output - 
Screenshot (37)

Java Output - 
Screenshot (40)

Python Output -

**Review by Kumar-laxmi — APPROVED** [review]
Please remove Program files other than Grundy number from this PR, kindly raise one PR per issue for easy evaluation and scoring

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please remove Program files other than Grundy number from this PR, kindly raise one PR per issue for easy evaluation and scoring

**Review by zugzwang03 — APPROVED** [review]

**Comment by patnaikankit** [comment]
@Kumar-laxmi I have removed the program files other than grundy numbers from this PR with the latest commit.

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
