### PR TITLE
Added Pigeonhole sort

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## 🛠️ Issue number #1229 

Issue no #

## 👨‍💻 Changes proposed
Added all files in all laguages.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

python
image
Java
image
C
image
C++
image

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please review PR @Kumar-laxmi

**Review by zugzwang03 — APPROVED** [review]

**Comment by Abhinavcode13** [comment]
@Arun9739 @072arushi please review pr and add ready to merge label

**Review by Arun9739 — APPROVED** [review]

**Comment by Abhinavcode13** [comment]
@072arushi please add ready to merge label after approving

**Comment by Abhinavcode13** [comment]
@072arushi please review this

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
