### PR TITLE
Diffie Hellman in Java

### LINKED ISSUE #552: Diffie-Hellman Algorithm
**Is your feature request related to a problem? Please describe.**
Elliptic Curve Cryptography (ECC) is an approach to public-key cryptography, based on the algebraic structure of elliptic curves over finite fields. 
**Describe the solution you'd like**
Diffie-Hellman Algorithm is a solution for Elliptic curve cryptography. An elliptic curve is a planar algebraic curve defined by an equation of the form

y^2 = x^3 + ax + b           
 
Where ‘a’ is the co-efficient of x and ‘b’ is the constant of the equation  

The curve is non-singular; that is, its graph has no self-intersections 

# Diffie-Hellman algorithm

The Diffie-Hellman algorithm is being used to establish a shared secret that can be used for secret communications while exchanging data over a public network using the elliptic curve to generate points and get the secret key using the parameters.  

For the sake of simplicity and practical implementation of the algorithm, we will consider only 4 variables, one prime P and G (a primitive root of P) and two private values a and b.
P and G are both publicly available numbers. Users (say Alice and Bob) pick private values a and b and they generate a key and exchange it publicly. The opposite person receives the key and that generates a secret key, after which they have the same secret key to encrypt

# Example:

Step 1: Alice and Bob get public numbers P = 23, G = 9

Step 2: Alice selected a private key a = 4 and
        Bob selected a private key b = 3

Step 3: Alice and Bob compute public values
Alice:    x =(9^4 mod 23) = (6561 mod 23) = 6
        Bob:    y = (9^3 mod 23) = (729 mod 23)  = 16

Step 4: Alice and Bob exchange public numbers

Step 5: Alice receives public key y =16 and
        Bob receives public key x = 6

Step 6: Alice and Bob compute symmetric keys
        Alice:  ka = y^a mod p = 65536 mod 23 = 9
        Bob:    kb = x^b mod p = 216 mod 23 = 9

Step 7: 9 is the shared secret.

### PR DESCRIPTION
**Pull request by Ananta-Vaishnavi**
## 🛠️ Issue #552

Issue no #552

## 👨‍💻 Changes proposed

Created a file under java for the algorithm

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please rename the file with proper extension.

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@Ananta-Vaishnavi Add screenshots of the output in the PR description.

**Comment by Ananta-Vaishnavi** [comment]
> Please rename the file with proper extension.

Yes, I have renamed

**Comment by Ananta-Vaishnavi** [comment]
> @Ananta-Vaishnavi Add screenshots of the output in the PR description.

Yeah, completed

**Comment by Ananta-Vaishnavi** [comment]
Hello! I was hoping to make some contributions under SWOC, but I noticed that this issue doesn't have a SWOC label. Could you possibly guide me and let me know if this repository falls under SWOC? I'd really appreciate your help!

**Comment by Arun9739** [comment]
> Hello! I was hoping to make some contributions under SWOC, but I noticed that this issue doesn't have a SWOC label. Could you possibly guide me and let me know if this repository falls under SWOC? I'd really appreciate your help!

Yes, it's under swoc, label will be added later.

**Comment by Ananta-Vaishnavi** [comment]
> Plz add a output screenshot, not the code's screenshot.

Yes completed

**Comment by Ananta-Vaishnavi** [comment]
# Checklist for Updating File Name, Adding Screenshot, Time Complexity and Space Complexity Details

- [x] Change the name of the file.
- [x] Add appropriate screenshot(s) to show output.
- [x] Include details about the time complexity of any algorithms or functions in the file.
- [x] Include details about the space complexity of any algorithms or functions in the file.

**Review by Arun9739 — APPROVED** [review]

**Comment by Ananta-Vaishnavi** [comment]
> Please rename the file with proper extension.

I have completed can you pls check

**Comment by Kumar-laxmi** [comment]
@siddhi-244 Kindly review this PR

**Comment by Kumar-laxmi** [comment]
@siddhi-244 Kindly review this PR

**Review by siddhi-244 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
All SSoC'23 PRs will be accepted after 1st June 2023

**Pull request closed without merging**
