### PR TITLE
Length of a linked list

### PR DESCRIPTION
**Pull request by MrKoshens**
## 🛠️ Issue (#584 )

Issue no #584 

## 👨‍💻 Changes proposed
Python code for length of linked list is added

## ✔️ Check List (Check all the applicable boxes) 

- [* ] My code follows the code style of this project.
- [* ] This PR does not contain plagiarized content.
- [* ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by atul1510** [comment]
@Kumar-laxmi, @072arushi  I already raised this issue before.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi, @072arushi I already raised this issue before.

Issue number?

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
There is no issue for ```secure hash algorithm```

**Comment by atul1510** [comment]
> > @Kumar-laxmi, @072arushi I already raised this issue before.
> 
> Issue number?

#584

**Comment by atul1510** [comment]
> There is no issue for the `secure hash algorithm`


I am talking about this #584 issue which is related to this PR.

**Comment by MrKoshens** [comment]
> There is no issue for `secure hash algorithm`

I accidentally added the files for secure hash algorithm. I have deleted them now. please review

**Review by 072arushi — CHANGES_REQUESTED** [review]
Can you code this in Java and C as well?

**Comment by MrKoshens** [comment]
> Can you code this in Java and C as well?
> 

Yes i can code this in C and java

**Review by Arun9739 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@MrKoshens This issue is assigned to @atul1510 because he requested to work on this issue first, so kindly close this PR

**Comment by MrKoshens** [comment]
> @MrKoshens This issue is assigned to @atul1510 because he requested to work on this issue first, so kindly close this PR

Okay sir

**Pull request closed without merging**
