### PR TITLE
added dutch national flag algorithm

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

issue no. #193

## 👨‍💻 Changes proposed

I added the Dutch national flag algorithm, an efficient algorithm to sort 0s, 1s, and 2s in an array. It is added in the C++ folder under sorting folder.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@sumitkr2000 Please resolve **CodeFactor** issues

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove the exe file

**Comment by sumitkr2000** [comment]
Bro check now @Kumar-laxmi

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@sumitkr2000 Please attach a screen shot of your output

**Comment by sumitkr2000** [comment]
Screenshot (524)

**Pull request merged**
