### PR TITLE
Added the code for Shell sort in python

### LINKED ISSUE #263: Shell Sort Algorithm
**Is your feature request related to a problem? Please describe.**
shell sort is a sorting algorithm that is an extended version of insertion sort. Shell sort has improved the average time complexity of insertion sort.

**Describe the solution you'd like**
Algorithms in C, C++, Python

please assign this to me @Kumar-laxmi

### PR DESCRIPTION
**Pull request by Kinshuk2003**
## 🛠️ Issue (Number)

Issue no #263 

## 👨‍💻 Changes proposed

- Added the program for Shell Sort in python
- Modified README.md File to include shell sort in the available resources table

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

kindly review by code and let me know if any changes are required

## 📷 Screenshots
image

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Explain your approach

**Comment by Kumar-laxmi** [comment]
@Kinshuk2003 Please resolve the **MERGE CONFLICT** in **README.md**

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
@Kinshuk2003 Kindly resolve the repetition in **README.md**
image

**Comment by Kinshuk2003** [comment]
> @Kinshuk2003 Kindly resolve the repetition in **README.md** image

can you explain a bit more exactly which repetion you are talking about ?

**Review by 072arushi — APPROVED** [review]
Approved

**Review by siddhi-244 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Don't update ```README.md```

**Comment by Kinshuk2003** [comment]
ok will revert all the changes in the readme

**Comment by Kumar-laxmi** [comment]
@Kinshuk2003 Kindly reopen a fresh PR where there is no updation in README.md or else **Merge Conflict** won't resolve

**Pull request closed without merging**
