### PR TITLE
Pull request. Code for RSA algorithm

### LINKED ISSUE #416: RSA algorithm
Not a bug or problem. I want to add the RSA algorithm which is often used in cryptography.

RSA (Rivest-Shamir-Adleman) is a widely used public-key encryption algorithm in cryptography. It is based on the properties of very large prime numbers, and it is considered very secure.
I want to provide code for RSA algorithm in python

### PR DESCRIPTION
**Pull request by MrKoshens**
## 🛠️ Issue (#416 )

Issue no #

## 👨‍💻 Changes proposed

RSA (Rivest-Shamir-Adleman) is a widely used public-key encryption algorithm that
is based on the mathematical properties of large prime numbers.  The security of the 
RSA algorithm is based on the fact that it is very difficult to factorize large prime
numbers, making it computationally infeasible for an attacker to determine the private 
key from the public key. 

In this PR, a detailed code for the RSA algorithm is given along with the output. The code takes input 2 prime numbers which are different, and a message that you want to encrypt. Then it returns the public and the private key along with the cipher text and the decrypted plaintext.

## ✔️ Check List (Check all the applicable boxes) 

- [ *] My code follows the code style of this project.
- [ *] This PR does not contain plagiarized content.
- [ *] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
@MrKoshens Please include some description with screen shots or output

**Comment by Kumar-laxmi** [comment]
And for what have you included ```math``` file

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
Please add screenshots in the problem description. Also, it is not necessary to have the math package file in your commit.

**Comment by MrKoshens** [comment]
> @MrKoshens Please include some description with screen shots or output

I have done the necessary changes. Please check

**Comment by MrKoshens** [comment]
> Please add screenshots in the problem description. Also, it is not necessary to have the math package file in your commit.

I have removed the math file and added a description in the problem and a screenshot of the output in the problem description. please check

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Don't push the screenshot in the Folder & it is enough in PR description

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove jpg file

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@MrKoshens You have added job sequencing algorithm in this PR. Link the issue number for the same. Otherwise create a new PR for merging it.

**Review by 072arushi — APPROVED** [review]

**Comment by MrKoshens** [comment]
> @MrKoshens You have added job sequencing algorithm in this PR. Link the issue number for the same. Otherwise create a new PR for merging it.

I have removed the job sequencing code. please check

**Comment by MrKoshens** [comment]
> Don't push the screenshot in the Folder & it is enough in PR description

I have done the necessary changes as requested. please check

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
