### PR TITLE
Implemented (Python) Doubly Linked List

### PR DESCRIPTION
**Pull request by stiwari-ds**
## 🛠️ Issue (Number)

Issue no #51 

## 👨‍💻 Changes proposed

Added implementation for doubly linked list operations in Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Code:
code1
code2
code3
code4
code5
code6
code7
code8

Output:

output1
output2

output3
output4
output5
output6
output7
output8
output9
output10
output11

### CODE REVIEW

**Comment by stiwari-ds** [comment]
@Kumar-laxmi @072arushi @siddhi-244 @Sanjanabharadwaj25 
Requesting a review. Thank you.

**Review by Sanjanabharadwaj25 — APPROVED** [review]
LGTM!

**Review by 072arushi — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by stiwari-ds** [comment]
Thank you. Is it ready to merge then?

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@stiwari-ds Next time add only output screen shot in PR description, please don't include the screen shot of code

**Pull request merged**
