### PR TITLE
adding morse code

### PR DESCRIPTION
**Pull request by kritika2313**
## 🛠️ Issue (1390)

Issue no #1390 

## 👨‍💻 Changes proposed

Added morse code in c c++ java and python

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot 2023-06-19 153550

### CODE REVIEW

**Comment by kritika2313** [comment]
i am not clear with the fact that why there are some issues with codefactor . style and complexities i have updated to best of my knowledge.

**Comment by Kumar-laxmi** [comment]
> i am not clear with the fact that why there are some issues with codefactor . style and complexities i have updated to best of my knowledge.

image

The solution to CODEFACTOR issues are provided when you click on the arrow

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
Why does the codes look similar to the codes provided in https://www.geeksforgeeks.org/morse-code-implementation/

**Comment by kritika2313** [comment]
It seems so as i have learnt this form  https://www.geeksforgeeks.org/morse-code-implementation/  however there was no such intension to put some plagiarized code .I apologize for this.
Should i try to code this with some different approach and then open a new pr?

**Comment by Kumar-laxmi** [comment]
Sorry @kritika2313, this issue will be re-assigned to someone else

**Pull request closed without merging**
