### PR TITLE
Kandane Algorithm Using Python

### PR DESCRIPTION
**Pull request by vijay-kumar-yadav**
## 🛠️ Issue (#95 )

Issue no #95

## 👨‍💻 Changes proposed
Added Kandane algorithm using Python in Subarray section
Update readme.md for same

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly update your branch to upstream & don't update the ```README.md``` (it might cause merge conflict)

**Comment by vijay-kumar-yadav** [comment]
> Kindly update your branch to upstream & don't update the `README.md` (it might cause merge conflict)

@Kumar-laxmi  I have cleared all conflicts please review and merge it asap!

**Review by zugzwang03 — APPROVED** [review]

**Comment by vijay-kumar-yadav** [comment]
> > Kindly update your branch to upstream & don't update the `README.md` (it might cause merge conflict)
> 
> @Kumar-laxmi I have cleared all conflicts please review and merge it asap!

@Kumar-laxmi  what changes are you requesting

**Comment by vijay-kumar-yadav** [comment]
> Kindly update your branch to upstream & don't update the `README.md` (it might cause merge conflict)

@Kumar-laxmi I have fixed those merge conflict

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please don't update the README.md

**Comment by vijay-kumar-yadav** [comment]
> Please don't update the README.md

@Kumar-laxmi Now check I have set to origional state

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Could you upstream your branch

**Comment by vijay-kumar-yadav** [comment]
> Could you upstream your branch

image
it is already upstream @Kumar-laxmi

**Comment by vijay-kumar-yadav** [comment]
> > Could you upstream your branch
> 
> image it is already upstream @Kumar-laxmi

@Kumar-laxmi please review this

**Review by 072arushi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@vijay-kumar-yadav Could you close this PR and re-open a new PR, because still some updation in README.md is visible

**Comment by Kumar-laxmi** [comment]
In the new PR don't update README.md

**Pull request closed without merging**
