### PR TITLE
Added Camel Case Problem

### PR DESCRIPTION
**Pull request by atul1510**
## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Program to convert text sentences in CamelCase format.
Examples:
 1] INPUT: "this is camel case"
    OUTPUT "thisIsCamelCase"

 2] INPUT: "Hi Atul here"
   OUTPUT: "HiAtulHere"

## 📷 Screenshots

Screenshot (125)

### CODE REVIEW

**Comment by atul1510** [comment]
> @atul1510 Could you implement this algorithm in all four languages

Yes, Sure I Can implement this algorithm in all four languages.
@Kumar-laxmi  sir , You can assign me in C/C++/Java/Python languages.

**Comment by Kumar-laxmi** [comment]
After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

**Comment by atul1510** [comment]
> After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

Ok Got it, sir

**Comment by atul1510** [comment]
@072arushi @Kumar-laxmi @zugzwang03 Please review this.

**Comment by atul1510** [comment]
Done with all changes requested.

**Review by 072arushi — APPROVED** [review]
Great work

**Review by zugzwang03 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by atul1510** [comment]
@Kumar-laxmi ?? still in review ??

**Pull request merged**
