### PR TITLE
Banker's Algorithm in Java

### PR DESCRIPTION
**Pull request by Dharnish38**
## 🛠️ Issue (#151)

Issue no #151 (Java)

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi, since I have asked you to assign this task. I have completed implementing it using the language Java.

So, I request you to once review, my PR, and then merge it.

Thank you!!! for letting me contribute to the repo.

## 📷 Screenshots
Java :
Bank_1
Bank_2
Bank_3
Bank_4

I hope you will merge this PR, so that I can contribute to your other issues also 👍
Thank You !!!!!

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
mention time and space complexity inside comments

**Review by zugzwang03 — APPROVED** [review]

**Comment by Dharnish38** [comment]
> mention time and space complexity inside comments

Sorry I forgot it, Thanks @Rancho2002 for saying it. Now I have mentioned the time and space complexities of the algorithm in the comments. Please look into it.

**Review by Arun9739 — APPROVED** [review]
Good one !

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Dharnish38** [comment]
@Sanjanabharadwaj25 , @Arun9739 , @Rancho2002 , @zugzwang03 Can anyone of the mentors please make this PR ready to merge.

**Comment by Kumar-laxmi** [comment]
@Dharnish38 Please resolve the **CodeFactor** issue

**Comment by Dharnish38** [comment]
> @Dharnish38 Please resolve the **CodeFactor** issue


@Kumar-laxmi Sorry to say this, Bankers Algorithm's time complexity is BigO(n^3) that's why the code factor is showing complex method. I tried on my own and searched even on the internet too, to reduce the complexity of the algorithm but that doesn't work.

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
