### PR TITLE
Diffie-Hellman Algorithm in Python

### PR DESCRIPTION
**Pull request by Abhilash1781**
## 🛠️ Issue (#552 )

Issue no #552

## 👨‍💻 Changes proposed
Uploaded Diffie_Hellman.py file to Cryptography Folder

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
The example I used is same as the one mentioned in the issue . 

## 📷 Screenshots
diffie

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
Mention time and space complexity inside comments

**Review by zugzwang03 — APPROVED** [review]

**Comment by Abhilash1781** [comment]
@Rancho2002 I have mentioned time & space complexity in comments .

**Review by Rancho2002 — APPROVED** [review]
Perfect

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please also include the Encryption and Decryption

**Comment by Abhilash1781** [comment]
Sir I will update by today night or tomorrow morning

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
