### PR TITLE
Added reverse a singly linked list

### LINKED ISSUE #340: Reverse a singly linked list in python
**Is your feature request related to a problem? Please describe.**
No, it is not a problem. I want to write an algorithm to reverse a singly linked list in python

**Describe the solution you'd like**
I will create a linked list first and then reverse it using the iterative approach.

**Describe alternatives you've considered**
No.

**Additional context**

### PR DESCRIPTION
**Pull request by papri24majumder**
## 🛠️ Issue (Number)

Closes #340 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
1) output in c:

img_c

2) output in c++:

img_c++

3) output in java:

img_java

4) output in python:

img_py

### CODE REVIEW

**Comment by papri24majumder** [comment]
Can anyone tell me what changes should I make in line 10?

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@papri24majumder Good
There is a issue in codefactor saying that line 10 has redundant line. Try to remove that and see.

**Comment by papri24majumder** [comment]
@Arun9739 Thanks. Issue Resolved.

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add time complexity and explain your algorithm

**Comment by papri24majumder** [comment]
@072arushi done

**Review by 072arushi — APPROVED** [review]
Nice!!

**Review by Arun9739 — APPROVED** [review]
Good work !

**Comment by papri24majumder** [comment]
@Rishikavishnoi please review.

**Comment by papri24majumder** [comment]
@Rishikavishnoi Please review this pr

**Review by Rishikavishnoi — APPROVED** [review]

**Pull request merged**
