### PR TITLE
Added Rain Water Problem

### PR DESCRIPTION
**Pull request by atul1510**
## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Program to solve rainwater problem using stack
Input[] = {1, 1, 5, 2, 1, 8, 1, 0, 2, 1, 2, 6};
Output = 31
It returns the maximum water that can be stored.

## 📷 Screenshots
Screenshot (126)

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@atul1510 Could you implement this algorithm in all four languages

**Comment by atul1510** [comment]
> @atul1510 Could you implement this algorithm in all four languages
Yes, Sure I Can implement this algorithm in all four languages.
@Kumar-laxmi  sir, You can assign me in C/C++/Java/Python languages.

**Comment by Kumar-laxmi** [comment]
After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

**Comment by atul1510** [comment]
> After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

Ok Got it, sir

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by atul1510** [comment]
All changes requested have been made successfully. 
@Kumar-laxmi @072arushi please review it.

**Review by siddhi-244 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
good contribution

**Pull request merged**
