### PR TITLE
aostar program of AI in JAVA,Python.

### PR DESCRIPTION
**Pull request by SimranLahrani842**
## 🛠️ Issue (Number)
Issue no #1102 
AO star-The AO* method divides any given difficult problem into a smaller group of problems that are then resolved using the AND-OR graph concept. AND OR graphs are specialized graphs that are used in problems that can be divided into smaller problems. The AND side of the graph represents a set of tasks that must be completed to achieve the main goal, while the OR side of the graph represents different methods for accomplishing the same main goal.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Output in java:
ss1
output in python:
ss2

### CODE REVIEW

**Comment by SimranLahrani842** [comment]
please review my PR updated readme.md also @Arun9739 , @Kumar-laxmi , @072arushi

**Comment by SimranLahrani842** [comment]
> Thanks for your contribution we will soon check your PR @SimranLahrani842 :)
please review my PR updated readme.md also @Arun9739 , @Kumar-laxmi , @072arushi

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes to be done:
- Include C & C++ Programs
- Do not update the README.md

**Comment by SimranLahrani842** [comment]
> Changes to be done:
> 
> * Include C & C++ Programs
> * Do not update the README.md

I know Java and python and hence added both these..

**Comment by Kumar-laxmi** [comment]
> > Changes to be done:
> > 
> > * Include C & C++ Programs
> > * Do not update the README.md
> 
> I know Java and python and hence added both these..There are many PRs which are merged and have only two/three languages ...so please merge..Thankyou @Kumar-laxmi

In those PR, the implementation has been already done or the level of algorithm chosen is of higher logic

**Comment by SimranLahrani842** [comment]
> > > > Changes to be done:
> > > > 
> > > > * Include C & C++ Programs
> > > > * Do not update the README.md
> > > 
> > > 
> > > I know Java and python and hence added both these..There are many PRs which are merged and have only two/three languages ...so please merge..Thankyou @Kumar-laxmi
> > 
> > 
> > In those PR, the implementation has been already done or the level of algorithm chosen is of higher logic
> 
> Yes AO* also has a higher logic to understand as it is advanced version of A star .. and topic of trees.Please merge my pr 
I have 0 PR's merged yet

**Comment by Kumar-laxmi** [comment]
> > > > Changes to be done:
> > > > 
> > > > * Include C & C++ Programs
> > > > * Do not update the README.md
> > > 
> > > 
> > > I know Java and python and hence added both these..There are many PRs which are merged and have only two/three languages ...so please merge..Thankyou @Kumar-laxmi
> > 
> > 
> > In those PR, the implementation has been already done or the level of algorithm chosen is of higher logic
> 
> Yes AO* also has a higher logic to understand .. As it is a topic of trees

No Problem, but you could have told this while issue was assigned to you so that other two languages could be tried by other contributors

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Do not update the README.md

**Comment by SimranLahrani842** [comment]
> Do not update the README.md (you might face merge conflict if you do so)

Done sir removed changes in readme.md

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
Kindly resolve the Merge Conflict

image

**Comment by SimranLahrani842** [comment]
> Kindly resolve the Merge Conflict
> 
> image

That is because i changed the readme.md file ...but later I deleted kindly add in readme.md and merge.

**Comment by Kumar-laxmi** [comment]
I think you need to close this PR and open a new one

**Comment by SimranLahrani842** [comment]
> I think you need to close this PR and open a new one (if you do so mention this PR)

I ll do this today itself..
So will u directly merge this PR or I need to review again?

**Comment by Kumar-laxmi** [comment]
> > I think you need to close this PR and open a new one (if you do so mention this PR)
> 
> I ll do this today itself.. So will u directly merge this PR or I need to review again?

I will directly merge, but do referrence this PR

**Comment by SimranLahrani842** [comment]
> > > I think you need to close this PR and open a new one (if you do so mention this PR)
> > 
> > 
> > I ll do this today itself.. So will u directly merge this PR or I need to review again?
> 
> I will directly merge, but do referrence this PR Better close this PR and delete the branch. Open a new PR from a new branch to avoid merge conflct

Got it thankyou sir 💙

**Pull request closed without merging**
