### PR TITLE
Vignere cipher in python

### PR DESCRIPTION
**Pull request by MrKoshens**
Vigenere cipher uses a keyword to encrypt a message by replacing each letter of the message with a letter that is shifted a certain number of places down the alphabet based on the corresponding letter of the keyword. The same keyword is used for each letter of the message, but shifted to a different position for each letter of the message. This makes the Vigenère cipher much more secure than simple substitution ciphers, such as the Caesar cipher.

## 🛠️ Issue (516)
Issue no #516 

Issue no #516 

## 👨‍💻 Changes proposed
Complete code For vigenere cipher is given. with screenstot and output.

## ✔️ Check List (Check all the applicable boxes) 

- [ *] My code follows the code style of this project.
- [ *] This PR does not contain plagiarized content.
- [ *] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Change the PR title to "Vignere Cipher in Python"

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]
LGTM🎉

**Review by Rancho2002 — APPROVED** [review]
Perfect

**Review by siddhi-244 — APPROVED** [review]

**Comment by MrKoshens** [comment]
@Kumar-laxmi Please check This PR so I can make a different PR for a different issue. Its almost done

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
