### PR TITLE
added multistage graph

### PR DESCRIPTION
**Pull request by tarunvyshnav777**
## 🛠️ Issue (Number)

Issue no #1196 

## 👨‍💻 Changes proposed

The code to calculate minimum cost (shortest path) in a Multistage Graph is added in all 4 languages.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

 
Screenshot (34)

## 📷 Screenshots 
Screenshot (32)
Screenshot (30)
Screenshot (31)

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by tarunvyshnav777** [comment]
@zugzwang03 i accidently tapped on review again can you again approve

**Comment by tarunvyshnav777** [comment]
@072arushi please review and approve this.

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by tarunvyshnav777** [comment]
@Kumar-laxmi this pr is ready to merge

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Resolve the **CodeFactor** issues

**Comment by tarunvyshnav777** [comment]
> Resolve the **CodeFactor** issues

Done!

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
