### PR TITLE
Added Implementation of Next fit Algorithm in C, C++, Java & Python Closes #1495

### LINKED ISSUE #1495: Next Fit Memory Allocation Algorithm in C, C++, Java & Python
**Is your feature request related to a problem? Please describe.**
Memory allocation techniques are an important part of the operating systems. Next fit is one of them. It is just a modified version of first fit, where you are allocating the first suitable block of memory, but for next request, you start from the block that was previously alloted.

**Describe the solution you'd like**
I would add C, C++, Java & Python Implementation of the algorithm

Please assign me this issue

### PR DESCRIPTION
**Pull request by ranjanmangla1**
## 🛠️ Issue #1495 
Added Implementation of Next fit Algorithm (for fixed size Memory Blocks) in C, C++, Java & Python

Issue no #1495

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### C++
image

### Java
image

### Python
image

### C
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
remove ```.vscode/tasks.json```

**Comment by ranjanmangla1** [comment]
> remove `.vscode/tasks.json`

@Kumar-laxmi I have deleted the .vscode/tasks.json directory

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@ranjanmangla1 Add output screenshots

**Comment by ranjanmangla1** [comment]
> @ranjanmangla1 Add output screenshots

Done @Arun9739 

Please review this pr @Kumar-laxmi @072arushi

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
