### PR TITLE
Create Add2LinkedList.java

### LINKED ISSUE #770: Addition of two Linked List in Java
I did not found Addition of two Linked List in Java . I can do this with proper implementation.
please assign this to me @Kumar-laxmi  as a part of SSOC'23

### PR DESCRIPTION
**Pull request by SivaHarshith1303**
## 🛠️ Issue #770
Screenshot (37)

Issue no #770 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by SivaHarshith1303** [comment]
@Kumar-laxmi  can you please check this once

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Add C and Python programs too

**Comment by SivaHarshith1303** [comment]
For python i have already raised another pull request and it has been accepted

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please do not open multiple PRs for same issue, kindly close other two PRs and include all three programs in one PR

**Comment by Kumar-laxmi** [comment]
> For python i have already raised another pull request and it has been accepted

@SivaHarshith1303 In that PR you have been asked to remove all other program files, kindly check

**Comment by sha0urya** [comment]
@Kumar-laxmi can i work on this under ssoc'23

**Pull request closed without merging**
