### PR TITLE
Adding of new Algo PollardRhoAlgorithm

### PR DESCRIPTION
**Pull request by Aarsh30**
Pollard’s Rho Algorithm for Prime Factorization #1269

## 🛠️ Issue (#1269)

Issue no #1269 

## 👨‍💻 Changes proposed

Implement the algorithm in all 4 language that is java,c++,C and Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

What is Algorithm means 

Pollard’s Rho is a prime factorization algorithm, particularly fast for a large composite number with small prime factors. The Rho algorithm’s most remarkable success was the factorization of eighth Fermat number

Here is a Algorithm of Pollard's Rho algorithm:

1.Choose a random number 'x' and a function 'f(x)' that generates a sequence of values.
2.Initialize two variables, 'y' and 'd', to 1.
3.Repeat the following steps until a factor of the number is found:
a. Update 'x' by applying the function: x = f(x).
b. Update 'y' by applying the function twice: y = f(f(y)).
c. Calculate the absolute difference between 'x' and 'y': d = abs(x - y).
d. Find the greatest common divisor (GCD) of 'd' and the number being factorized.
e. If the GCD is a non-trivial factor (not 1 or the number itself), return it as a prime factor.
f. If the GCD is 1, continue to the next iteration.
4.If no factor is found after a certain number of iterations, choose a different random 'x' and repeat the process.

## 📷 Screenshots
c
c++1
java
python

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Aarsh30 Add comments explaining your approach

**Comment by Aarsh30** [comment]
> @Aarsh30 Add comments explaining your approach

yaa i had added in comment once have a look at it

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by Aarsh30** [comment]
@Arun9739  i had made changes can you review it and merge the pr it is pending from manys days

**Comment by Arun9739** [comment]
@Aarsh30 You have not yet added any comments.
The changes requested is to add some comments

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
Code has been plagarised from: https://www.geeksforgeeks.org/pollards-rho-algorithm-prime-factorization/, do you have any explanation for this

**Pull request closed without merging**
