### PR TITLE
Bankers Algorithm added in c #151

### LINKED ISSUE #151: Bankers Algorithm
**Is your feature request related to a problem? Please describe.**
Bankers algorithm is one of the important algorithm in Operating systems which decides which task is to be executed first in os level. Also it is one of the most common problem asked in interviews

**Describe the solution you'd like**
I will code in c language where multiple request will be made by user and which request will be considered on prior basis will be decided by the algorithm and that same model is followed in os level.

**Describe alternatives you've considered**
I have considered a user input values which is the same model which is performed in os level for application

**Additional context**
I will provide the screenshots of the outputs and a detail explaination of it .Also I will provide code on resource request algorithm code which is one of the important part of bankers algorithm.

Please assign me this task @Kumar-laxmi

### PR DESCRIPTION
**Pull request by Sachittarway**
## 🛠️ Issue (Number) 151

Issue no #151 

## 👨‍💻 Changes proposed

Added bankers safety state alogrithm in c.
## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

This algorithm checks whether the system is in safe state or not.
## 📷 Screenshots
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi Please review it. I am not able to resolve code factor. Whats the problem. Code is running perfectly fine.

Click on ```details``` on the right

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly enter appropriate PR Title

**Comment by Sachittarway** [comment]
> Kindly enter appropriate PR Title

Done

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Sachittarway Codefactor is howing one issue. Plz check the deatils and resolve it !

**Comment by Sachittarway** [comment]
@Arun9739 @siddhi-244 @Sanjanabharadwaj25 Please review and accept it.

**Review by siddhi-244 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Sachittarway** [comment]
@Arun9739 please review and merge it.

**Review by Arun9739 — APPROVED** [review]
@Sachittarway Good !
Approved !

**Comment by Sachittarway** [comment]
@Kumar-laxmi please merge it

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
