### PR TITLE
Add Brian Kerningham's Algorithm in all 4 languages

### PR DESCRIPTION
**Pull request by MisterMickey**
## 🛠️ Issue 

Issue no #1230 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Screenshot from 2023-06-11 20-06-37
Screenshot from 2023-06-11 20-08-07
Screenshot from 2023-06-11 20-13-08
Screenshot from 2023-06-11 20-13-36

## 📷 Screenshots

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please don't update README.md

**Comment by MisterMickey** [comment]
@Kumar-laxmi Done.

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@072arushi Kindly review this PR

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please provide the screen shot of the output not the code (code is already visible in the CodeSpace)

**Comment by MisterMickey** [comment]
@Kumar-laxmi Sure, I'll attach the screenshots.

**Comment by MisterMickey** [comment]
@Kumar-laxmi Output is on the right pane of the screenshot(i.e. 4)

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
