### PR TITLE
depth first search algorithm

### PR DESCRIPTION
**Pull request by 96vksingh**

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@96vksingh  Please close another duplicate PR

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please close the spam PR

**Comment by 96vksingh** [comment]
> Please close the spam PR

Closed

**Comment by Kumar-laxmi** [comment]
@96vksingh 🤩 Do star this repository !!!!

**Pull request merged**
