### PR TITLE
Fractional Knapsack, 0/1 Knapsack and Karatsuba Algorithm

### LINKED ISSUE #71: Karatsuba Algorithm
Karatsuba Algorithm is available in the following languages:
- C
- C++
- Java 
- Python

Please include this in folder named: **Divide-and-Conquer**

### LINKED ISSUE #72: 0/1 Knapsack - Dynamic Programming approach
0/1 Knapsack is available in the following languages:
- C
- C++
- Java
- Python

### Kindly include this project in **Dynamic Programming** folder

### LINKED ISSUE #73: Fractional Knapsack - Greedy approach
Fractional Knapsack is available in the following languages:
- C
- C++
- Java
- Python

### Kindly include this project in **Greedy Programming** folder

### PR DESCRIPTION
**Pull request by Priyanshu-Singh-1**
## 🛠️ Issue (Number)

Closes #71 (C++)
Closes #72 (C, C++)
Closes #73 (C++)

## ✔️ Check List (Check all the applicable boxes) 

- ✔️ My code follows the code style of this project.
- ✔️ This PR does not contain plagiarized content.
- ✔️ The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
@Kumar-laxmi 
Since, in the due time, a lot of PRs have been merged, there were some merge conflicts in that readme file. Due to this, when I synched your repo, the conflict occurred to me also. So, to resolve that I have closed the previous PR, and have made a new one consisting of all the issues in this PR.

So, I request you to once review, my PR.

### CODE REVIEW

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

for the following issue, I have made a new PR and have closed the old PR, since it consisted of merge conflicts due to syncing.

These are the issues  for this PR:

1. Fractional Knapsack - Greedy approach #73  (C++)
2. 0/1 Knapsack - Dynamic Programming approach #72  (C and C++)
3.  Karatsuba Algorithm - Divide and Conquer #71 (C++)

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1  For now please don't update the README.md, there are some changes going on, rest every thing is ready to be merged

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 
So is there anything I have to do now?

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

As per your suggestion, I have undone the contents that I have put in the readme file. So, this PRs only contains the issues and not any other updation of the readme file.

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1 Please resolve merge conflict

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

There were no conflicts in this PR earlier. Might be caused after you have merged some PR that have made changes in readme file

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

What should I do, please tell

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi
> 
> What should I do, please tell

For now please remove the updation in **README.md** from this PR

**Comment by Priyanshu-Singh-1** [comment]
@Kumar-laxmi 

I have reverted out the readme PR.

**Comment by Kumar-laxmi** [comment]
@Priyanshu-Singh-1 Do one think open a fresh PR without disturbing **README.md**

**Comment by Priyanshu-Singh-1** [comment]
> @Priyanshu-Singh-1 Do one think open a fresh PR without disturbing **README.md**

okay will do it now

**Pull request closed without merging**
