### PR TITLE
Added prim's algorithm in java issue no#61

### PR DESCRIPTION
**Pull request by ManavLohia945**
I have added the code for prim's algorithm in java that was assigned to me.Issue no #61

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please save this program under Graphs folder and you haven't named the file with '.java'

**Comment by ManavLohia945** [comment]
ok I will do these changes and commit again

**Comment by ManavLohia945** [comment]
Sir, I have made the changes kindly check

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please update the **README.md**

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 There has been minor update in **README.md**, please so the changes accordingly

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 Please resolve the **Merge Conflict**

**Comment by ManavLohia945** [comment]
Yes I will update the readme file and also resolve the merge conflict by today itself.

**Comment by ManavLohia945** [comment]
I have done the changes.. I have updated the readme file and also solved the merge conflicts

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Change file name to 'Prims.java'

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 I think you need to update your branch to the upstream

**Comment by ManavLohia945** [comment]
Ok will do that

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 Please resolve the **MERGE CONFLICT**

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 For now could you remove the updation of README.md from this PR

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@ManavLohia945  You can add the time and space complexities for the  program.

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by ManavLohia945** [comment]
@Kumar-laxmi If you could tell me exactly what to include in the README.md file it would be appreciated.

**Comment by zugzwang03** [comment]
> @Kumar-laxmi If you could tell me exactly what to include in the README.md file it would be appreciated.

There is a conflict in the README.md file of your branch with the updated version's branch of this repo, kindly work on removing that conflict. Like some serial numbers got intertwined in the process.

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 Better create a new PR and don't update the **README.md**

**Comment by Kumar-laxmi** [comment]
> @ManavLohia945 Better create a new PR and don't update the **README.md**

And to mention this PR number in that

**Comment by Kumar-laxmi** [comment]
@ManavLohia945 Kindly resolve the problems in next 2 days or else this PR will be marked ```Stale``` and closed

**Comment by ManavLohia945** [comment]
I am so sorry for the delay. I was caught up on some other work lately. Will do the needful by tomm

**Comment by Kumar-laxmi** [comment]
> I am so sorry for the delay. I was caught up on some other work lately. Will do the needful by tomm

To get free of Merge Conflict try to remove any updation done by you in README.md

**Comment by ManavLohia945** [comment]
Okay so by not updating the README.md file you mean I should just do a pull req in my local system to get up to date with all the latest merges and not add anything new in the prim's algo row right?

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
image
@ManavLohia945  The README is not correct.  Do the necessary changes.

**Comment by ManavLohia945** [comment]
Done plz check @Sanjanabharadwaj25

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please include the screen-shot of you output

**Comment by ManavLohia945** [comment]
Input given to the program:
image
Output:
image

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
