### PR TITLE
Fixes Issue #50 

### LINKED ISSUE #50: Add Info about available algorithms in main Readme
- I think it becomes easier for the community to use the repository if we add the available algorithms across languages in `Readme`.
- Further, it would be good if we ask the new contributors to add their implementation in `Readme` alongside their contributions
  - It ensures automatic update of `Readme` with the available resources

### PR DESCRIPTION
**Pull request by rohitbabugaddeti**
## Below are the additions in this PR
- Added explanation for directory structure in the repository
- Added table with available algorithms in the repo with programming languages and category
    - Hyper-Linked the algorithm of each programming language to it's source code in the repo
- Added note in contribution section asking contributors to update the available resources section
- Renamed files to bring symmetry in filenames pattern (relates to issue #60 )

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@rohitbabugaddeti Could you update README.md in language sub folders also

**Comment by rohitbabugaddeti** [comment]
@Kumar-laxmi  I could. But I feel it becomes redundant. And the issue #50 also highlights about adding it in main `Readme`

**Comment by Kumar-laxmi** [comment]
@rohitbabugaddeti Or do one thing that in **Available Languages** each language could be a Hyperlink to the the program file in repository.
Example: In Huffman Coding -> In available language you can make: 
<a href="https://github.com/Kumar-laxmi/Algorithms/blob/main/C/Data%20Compression/huffmanCoding.c">C</a>
<a href="https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Data%20Compression/huffmanCoding.cpp">C++</a>
<a href="https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Data%20Compression/huffmanCoding.py">Python</a>

**Comment by rohitbabugaddeti** [comment]
> @rohitbabugaddeti Or do one thing that in **Available Languages** each language could be a Hyperlink to the the program file in repository. Example: In Huffman Coding -> In available language you can make: [C](https://github.com/Kumar-laxmi/Algorithms/blob/main/C/Data%20Compression/huffmanCoding.c), [C++](https://github.com/Kumar-laxmi/Algorithms/blob/main/C%2B%2B/Data%20Compression/huffmanCoding.cpp), [Python](https://github.com/Kumar-laxmi/Algorithms/blob/main/Python/Data%20Compression/huffmanCoding.py)

Yeah, this makes sense. Will try to do it.

**Comment by rohitbabugaddeti** [comment]
@Kumar-laxmi  Please check now

I identified issue #60  while doing this and hence renamed files to fix it

**Comment by Kumar-laxmi** [comment]
@rohitbabugaddeti Also include Kadane's Algorithm, Red-Black Tree in the table and Depth First Search in the README.md table.

**Comment by rohitbabugaddeti** [comment]
> @rohitbabugaddeti Also include Kadane's Algorithm, Red-Black Tree in the table and Depth First Search in the README.md table.


@Kumar-laxmi  please ask other contributors to add them. Possibly the one's who contributed those algorithms. If I do this now, by the time we merge it, someone might add something else and it goes on. Let's not get into that loop.

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
