### PR TITLE
Added Random Forest Classifier to Machine Learning using Python

### LINKED ISSUE #1570: [SSOC'23] Random Forest Algorithm in python - Machine Learning
**Is your feature request related to a problem? Please describe.**
There's no algorithm for Random Forest in Machine Learning Directory using python.

**Describe the solution you'd like**
Implemented Random Forest Algorithm in Python from Scratch.

### PR DESCRIPTION
**Pull request by manishkumar00208**
Implementation of Random Forest Algorithm (from scratch) using Python - A Machine Learning Model/Algorithm.

## 🛠️ Issue (Number)

Issue no #1570 

## 👨‍💻 Changes proposed

Implemented Random Forest Classifier for Machine Learning using Python (No Libraries are used).

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Directly run the program for the execution. It provides the robust functionality of RandomForest Classifier. This program will build 10 decision tree models to use as a ensemble in RandomForest classifer, and is tested with all 3 datasets provided. The accuracy of the classifier is almost same (sometimes a bit high, sometimes a bit low) as we obtain from the Weka toolkit.

## 📷 Screenshots
Output

### CODE REVIEW

**Comment by manishkumar00208** [comment]
@Kumar-laxmi Please review my PR and Merge it to the main repo.

**Review by zugzwang03 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by manishkumar00208** [comment]
@Arun9739 @072arushi Review my PR and Merge it!!

**Review by Arun9739 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@072arushi Kindly review it and mark in "Ready to merge"

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
Is this code ChatGPT generated?

**Comment by manishkumar00208** [comment]
@Kumar-laxmi No at all!!
It's my previous assignment/work assigned to me in college, not from chatgpt.

**Comment by manishkumar00208** [comment]
@Kumar-laxmi Why is this PR not yet merged?

**Pull request closed without merging**
