### PR TITLE
Added KMP Algorithm in C++

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

Issue no #138 

## 👨‍💻 Changes proposed

Hey, @Kumar-laxmi I have added the KMP Algorithm in Pattern matching in C++. Please review my PR and merge it. Thank you!

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot (617)

### CODE REVIEW

**Review by Rancho2002 — CHANGES_REQUESTED** [review]
The time and space complexity must be included inside comments

**Comment by sumitkr2000** [comment]
Done @Rancho2002 . Check it now.

**Review by Rancho2002 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@sumitkr2000 Include the complete checklist in the PR description.

**Comment by sumitkr2000** [comment]
Done @Sanjanabharadwaj25. Approve it now.

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@siddhi-244 Kindly review this PR and mark it ```Ready to Merge``` if it is approved from your side

**Comment by sumitkr2000** [comment]
After tagging also she is not replying!!!

**Comment by sumitkr2000** [comment]
Please merge my pr @Kumar-laxmi. Thank you!

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
