### PR TITLE
Longest Common Subsequence in c

### PR DESCRIPTION
**Pull request by diyagoyal98**
## 🛠️ Issue (Number) 286

Issue no #286 

## 👨‍💻 Changes proposed
I have made all the changes as proposed by respected reviewers

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I have made this fresh new pull request and made all the changes like added all the comments and also change he file name.
These all changes you have suggested me in my pull request #361 

## 📷 Screenshots
image

image

### CODE REVIEW

**Review by Arun9739 — APPROVED** [review]
Good !

**Comment by diyagoyal98** [comment]
sir please merge this.

**Review by Arun9739 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Rancho2002 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@diyagoyal98 Kindly mention issue number as hyperlink to your issue

**Comment by diyagoyal98** [comment]
#286

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
