### PR TITLE
added merge two sorted linked list

### PR DESCRIPTION
**Pull request by khushigarg1**
## 🛠️ Issue (#309 )

Issue no #309 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@khushigarg1 The code is good.
But add some comments explaining the approach.

**Comment by khushigarg1** [comment]
> @khushigarg1 The code is good. But add some comments explaining the approach.

Done!

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add a screenshot of output. 
Also codefactor is showing one issue. see it!
Try to fix it.

**Comment by khushigarg1** [comment]
> Add a screenshot of output. Also codefactor is showing one issue. see it! Try to fix it.

Done please check

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Can you take the input from user instead of giving directly in program.
It makes user friendly program.

**Comment by khushigarg1** [comment]
> Can you take the input from user instead of giving directly in program. It makes user friendly program.

Okay sure

**Comment by khushigarg1** [comment]
> Can you take the input from user instead of giving directly in program. It makes user friendly program.

Done!

**Comment by khushigarg1** [comment]
Screenshot (73)
Screenshot (74)
Screenshot (75)
Screenshot (76)

**Comment by khushigarg1** [comment]
> Can you take the input from user instead of giving directly in program. It makes user friendly program.

Done please check

**Review by Arun9739 — APPROVED** [review]
Approved !

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Remove .class and .exe files
They are binary files, not necessary

**Comment by khushigarg1** [comment]
@Arun9739  please approve!

**Review by Arun9739 — APPROVED** [review]

**Pull request merged**
