### PR TITLE
Added Binary Search Tree in Java & Python

### LINKED ISSUE #1480: Binary Search Tree in Java and Python
**Is your feature request related to a problem? Please describe.**
Binary Search Tree is a node-based binary tree data structure which has the following properties:
- The left subtree of a node contains only nodes with keys lesser than the node’s key.
- The right subtree of a node contains only nodes with keys greater than the node’s key.
- The left and right subtree each must also be a binary search tree.

**Additional context**
image

### PR DESCRIPTION
**Pull request by Shankhadweep**
Issue no #1480 

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
BinarySearchTree_SS

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Python implementation is missing

**Comment by Pranjal-Kri** [comment]
> Python implementation is missing

I can do the python implementation of binary search tree . Can you assign this to me!

**Comment by Shankhadweep** [comment]
> Python implementation is missing
I will be upload that too in the python folder

**Review by Shankhadweep — COMMENTED** [review]
Completed the python implementation of Binary Search Tree

**Review by zugzwang03 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Shankhadweep Add output screenshots

**Comment by Shankhadweep** [comment]
> @Shankhadweep Add output screenshots
Here are the output screenshots of the program. The first one is for the java implementation and the second one is the python implementation.

Output_BST
Output_BST_Python

**Comment by Shankhadweep** [comment]
> @Shankhadweep Add output screenshots

@Arun9739 Here are the output screenshots. The first one is the java implementation and the second one is the python implementation
Output_BST
Output_BST_Python

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Screen shot of your output is required

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
All operations such as: insert, search, update and delete are required

**Pull request closed without merging**
