### PR TITLE
Infix expression to postfix/prefix, prefix expression to infix/postfix, postfix expression to infix/prefix

### PR DESCRIPTION
**Pull request by Lakshita2**
## 🛠️ Issue (Number)

Close Issue no #287

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (804)
Screenshot (805)
Screenshot (806)

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Could you put this in ```Maths``` folder

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@Lakshita2 Please add screenshots of the output in the PR description.

**Review by siddhi-244 — APPROVED** [review]

**Comment by Lakshita2** [comment]
@Sanjanabharadwaj25  I have added the screenshots of the output, please have a look

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Lakshita2** [comment]
@Kumar-laxmi please review this

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
