### PR TITLE
Create Implement Linear Regression (without Library) in c++

### PR DESCRIPTION
**Pull request by Durgesh4993**

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please program using a data-set

**Comment by Durgesh4993** [comment]
Ok sir, can i further change in this code

**Comment by Kumar-laxmi** [comment]
> Ok sir, can i further change in this code

Yes

**Comment by Durgesh4993** [comment]
now i fully change and explain with example

**Comment by Durgesh4993** [comment]
it wright or not could you check

**Comment by Kumar-laxmi** [comment]
@Durgesh4993 Is it possible if you can **graph** it since then only the results can be verified easily & please update the **README.md**

**Pull request closed without merging**
