### PR TITLE
Next Greater Element using java

### PR DESCRIPTION
**Pull request by viveksondhiya**
## 🛠️ Issue (Number)

Issue no #376 
Issue no #270 
Issue no #286  

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Give proper PR Title, mention all issue numbers & resolve your **CodeFactor** issues

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@viveksondhiya, don't modify the check list. Mention the name of all the algorithms in the PR title and add screenshots of the output for all the programs.

**Review by viveksondhiya — COMMENTED** [review]
listed the all pr

**Comment by viveksondhiya** [comment]
image
but this is already merged in your repo no option for editing... how can I edit this again 
@Kumar-laxmi @Sanjanabharadwaj25  
should I make another pr for this ..?

**Review by 072arushi — APPROVED** [review]

**Comment by Sanjanabharadwaj25** [comment]
> image but this is already merged in your repo no option for editing... how can I edit this again @Kumar-laxmi @Sanjanabharadwaj25 should I make another pr for this ..?


The PR has not been merged. You can still edit and resolve the issue.

**Comment by viveksondhiya** [comment]
> > image but this is already merged in your repo no option for editing... how can I edit this again @Kumar-laxmi @Sanjanabharadwaj25 should I make another pr for this ..?
> 
> The PR has not been merged. You can still edit and resolve the issue.

for edit this I have to make another pr there is no option for edit this @Sanjanabharadwaj25 @Kumar-laxmi 
image

**Pull request closed without merging**
