### PR TITLE
This the program for Circular Link List

### PR DESCRIPTION
**Pull request by iianuragii**
## 🛠️ Issue (Number)

Issue No. #265 

## 👨‍💻 Changes proposed

I have submitted the code for Circular Link List in java which was assigned to me.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

This is the code for Circular Link list in java where the address of the last node is connected or link to the first node.
OUTPUT:-
image

## 📷 Screenshots

image

### CODE REVIEW

**Review by siddhi-244 — APPROVED** [review]

**Comment by iianuragii** [comment]
Hiii, if possible can I get all the approvals or rejections if any before 30th because I have to submit my project before 31st January else SWOC '23 will not be able to give my scores

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@iianuragii Add screenshots of the output for the program.

**Comment by iianuragii** [comment]
> @iianuragii Add screenshots of the output for the program.

Hiii, I have added it at the issues.

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by iianuragii** [comment]
> @iianuragii Add screenshots of the output for the program.

Done

**Comment by Kumar-laxmi** [comment]
@iianuragii Kindly make program dynamic with all features of circular linked list

**Pull request closed without merging**
