### PR TITLE
Added bloom-filter algorithm implementation of c and java

### PR DESCRIPTION
**Pull request by Jagan-45**
### Issue (997)

issue no #997

### Changes Proposed 

Hello , I just added bloom filter algorithm implementation in c and java in hashing directory . 

### Check List (Check All Applicable boxes)

- [x]  My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
### screenshots

Screenshot from 2023-06-08 21-18-55

Screenshot from 2023-06-08 21-26-23

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
Please complete the issue description according to the template given

**Comment by Jagan-45** [comment]
sir ,  I created the bloom filter of m size . Then I inserted by hashing them . Then I checked the element with th same hash function . And returned the result of boolean whether element is in the set or not . Only thing is I feel wrong is I used only one hash function . 
What I should update sir . Kindly guide me  sir .

**Comment by Kumar-laxmi** [comment]
> sir , I created the bloom filter of m size . Then I inserted by hashing them . Then I checked the element with the same hash function . And returned the result of boolean whether element is in the set or not . What I should update sir . Kindly guide me sir . should I want to update the pr description ? @Kumar-laxmi

Kindly mention the issue number in the PR description; you have referenced this PR itself in the PR description

**Comment by Jagan-45** [comment]
> > sir , I created the bloom filter of m size . Then I inserted by hashing them . Then I checked the element with the same hash function . And returned the result of boolean whether element is in the set or not . What I should update sir . Kindly guide me sir . should I want to update the pr description ? @Kumar-laxmi
> 
> Kindly mention the issue number in the PR description; you have referenced this PR itself in the PR description

Sorry for the confusion sir  . . .  I updated it

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Pull request merged**
