### PR TITLE
Circular Linked List in C++

### PR DESCRIPTION
**Pull request by Paritosh-J**
## 🛠️ Issue (Number)

Issue no #265 

## ✔️ Check List 

- My code follows the code style of this project.
- This PR does not contain plagiarized content.
- The title of my pull request is a short description of the requested changes.

### Definition
A Circular Linked List has the last node pointing to its first node.

### Implementation
This code sees the Circular Linked List **implemented in C++**. Following are functionalities of the code :
- Insertion
- Deletion
- Searching
- Printing

### Screenshots
cll 1
cll 2
cll 3
cll 4
cll 5

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Paritosh-J** [comment]
> Add 2 or 3 lines explaining your approach to solving the problem of circular linked list, which is basically the algorithm.

Made the required changes. Please review the changes.

**Comment by Paritosh-J** [comment]
> Add comments to explain your approach

@072arushi I've made the required changes. Please review the same.

**Review by 072arushi — APPROVED** [review]
Approved

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
