### PR TITLE
Karatsuba Algorithm

### PR DESCRIPTION
**Pull request by Dharnish38**
🛠️ Issue (Number)

Issue no #71 ( Java & Python )

## 👨‍💻 Changes proposed

Implemented Karatsuba Algorithm in Java and Python

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
@Kumar-laxmi, since I have asked you to assign this task. I have completed implementing it using the languages of java and python.

So, I request you to once review, my PR, and then merge it.

Thank you!!! for letting me contribute to the repo.

📷 Screenshots

I hereby attach the screenshots of the karatsuba algorithm implementation in java and python.

JAVA : 

Screenshot (599)

Python : 

Screenshot (598)

I hope you will merge this PR, so that I can contribute in your other issue also 👍
Thank You !!!!!

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Well organized code !
Approved !

**Comment by Dharnish38** [comment]
Thanks @Arun9739 and other mentors for accepting my pull request. I would like to hear comments from you like where I have to improve because this is my first contribution if anything I have to improve please tell so that I would avoid that mistake for next contribution.

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Dharnish38 Kindly DM me your name(used for registration), github username and this PR number on discord so that I can forward your score

**Comment by Dharnish38** [comment]
@Kumar-laxmi  I messaged you on discord

**Pull request merged**
