### PR TITLE
Counting Sort using Java

### PR DESCRIPTION
**Pull request by Harshit-Raj-14**
## 👨‍💻 Changes proposed
Added counting sort in java section

Issue No.:  #121 

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (46)

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- Remove the ```.class``` file
- Update the README.md

**Comment by Harshit-Raj-14** [comment]
@Kumar-laxmi I have done the following changes asked. And there are no conflicts. I hop you can merge it now.

**Comment by Harshit-Raj-14** [comment]
@Kumar-laxmi I have done the following changes asked. And there are no conflicts. I hop you can merge it now.

**Comment by Harshit-Raj-14** [comment]
@Kumar-laxmi I have solved the conflict issue. I hope that it gets merged now.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts !

**Comment by Harshit-Raj-14** [comment]
@siddhi-244 Hello I have fixed the conflict. Please merge.
Thank you.

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Rishikavishnoi — CHANGES_REQUESTED** [review]
@Harshit-Raj-14 resolve merge conflicts

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@Harshit-Raj-14 Link the PR with the issue.

**Comment by Harshit-Raj-14** [comment]
Issue - #247 
@Rishikavishnoi @Sanjanabharadwaj25 
I have resolved the conflict and linked it to issue.
I hope it gets merged now. 
Thank you.

**Review by Rancho2002 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Harshit-Raj-14 Resolve the conflict

**Comment by Harshit-Raj-14** [comment]
@Kumar-laxmi I have fixed the conflict issue. please merge

**Review by Kumar-laxmi — COMMENTED** [review]
@Harshit-Raj-14 You haven't imported any library/module

**Comment by Harshit-Raj-14** [comment]
@Kumar-laxmi I have added the import library.
Hole it gets merged now.

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
> Issue - #247 @Rishikavishnoi @Sanjanabharadwaj25 I have resolved the conflict and linked it to issue. I hope it gets merged now. Thank you.

You have mention this PR number instead of issue number, kindly mention the issue number in the PR description

**Comment by Kumar-laxmi** [comment]
@Harshit-Raj-14 Kindly do the required changes within a week

**Comment by Harshit-Raj-14** [comment]
@Kumar-laxmi I have added the Issue No.:  #623 

Please kindly merge.

**Comment by Kumar-laxmi** [comment]
@Harshit-Raj-14 The issue number #623 is a duplicate issue, please reference to origin issue

**Comment by Kumar-laxmi** [comment]
the actual issue number is #121

**Comment by Kumar-laxmi** [comment]
From next time first get assigned to the issue then open the PR

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
