### PR TITLE
Added Job Sequencing to C++ Greedy algorithms

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

Issue no #282 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (555)

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
Please merge my pr @Kumar-laxmi !

**Comment by sumitkr2000** [comment]
Please merge my pr @Kumar-laxmi !

**Comment by sumitkr2000** [comment]
Please merge my pr @Kumar-laxmi !

**Comment by sumitkr2000** [comment]
Please merge my pr @Kumar-laxmi !

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
This PR was merged by mistake

**Comment by sumitkr2000** [comment]
Why did u revert it bro @Kumar-laxmi ??

**Comment by Kumar-laxmi** [comment]
> Why did u revert it bro @Kumar-laxmi ??

#478

**Pull request merged**
