### PR TITLE
Added Coin Change Problem

### PR DESCRIPTION
**Pull request by sshiwangi**
## 🛠️ Issue (Number)

Fixes Issue no #359 

## 👨‍💻 Changes proposed

1. Added coin change problem in all four languages c, c++, java and python with proper comments.
2. Added a Readme file containing the problem statement, Intuition, dry run and time complexity.

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@sshiwangi You have to add C Python and Java files in their respective folders. All the files are currently in C++ folder.

**Comment by sshiwangi** [comment]
> @sshiwangi You have to add C Python and Java files in their respective folders. All the files are currently in C++ folder.

Ok got it.

**Review by zugzwang03 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Add screen shot of output in PR description

**Comment by sshiwangi** [comment]
> Add screen shot of output in PR description

Done

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Don't create a separate folder for each algorithm

**Comment by sshiwangi** [comment]
> Don't create a separate folder for each algorithm

Ok then should i add readme file of each problem in the main readme file?

**Comment by Kumar-laxmi** [comment]
You can the README in the Dynamic Programming Folder's README.md

**Comment by sshiwangi** [comment]
> You can the README in the Dynamic Programming Folder's README.md

Done.

**Comment by sshiwangi** [comment]
@Kumar-laxmi can u please review and merge it so that i can work on another issues.

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
