### PR TITLE
Longest Common Subsequence

### PR DESCRIPTION
**Pull request by viveksondhiya**
## 🛠️ Issue (Number)

Longest_Common_Subsequence : Issue no #286 

## 👨‍💻 Changes proposed
LongestCommonSubsequence using java 

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️ ] My code follows the code style of this project.
- [✔️  ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by viveksondhiya** [comment]
@Kumar-laxmi @khushigarg1 y code factor issue mujhse solve nhi ho rha h .... edit krne ka option nhi h kahi ...mene phle wali pull ko close krke dobara pull ki h fir bhi yahi issue aa rha h...  please help me out

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly mention the issue number for ```NextGreater.java```

**Comment by viveksondhiya** [comment]
> Kindly mention the issue number for `NextGreater.java`

Done

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@viveksondhiya Kindly resolve your **CodeFactor** issues

**Comment by viveksondhiya** [comment]
@Kumar-laxmi y code factor issue mujhse solve nhi ho rha h .... edit krne ka option nhi h kahi ...mene phle wali pull ko close krke dobara pull ki h fir bhi yahi issue aa rha h...  please help me out

**Comment by Arun9739** [comment]
@viveksondhiya Look for the reason of the codefactor issue by clicking at 'details'. Try to resolve that.

**Review by viveksondhiya — COMMENTED** [review]
Cofactor issue solved

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
