### PR TITLE
Added Partition Problem in java and C++ under Dynamic Programming

### LINKED ISSUE #704: Add Partition Problem using Dynamic Programming in java and c++ .
I want to add Partition Problem using Dynamic Programming in java and c++.

Screenshot 2023-05-30 234922

Please assign me this issue.

### PR DESCRIPTION
**Pull request by Aishjahan**
## 🛠️ Issue (Number)

Issue no #704 

## 👨‍💻 Changes proposed

Added Partition Problem in java and C++ under Dynamic Programming

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Please review my PR

Screenshot 2023-06-01 174806

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@Aishjahan Please add screen shot of your output

**Comment by Aishjahan** [comment]
Screenshot 2023-06-01 174806

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add screenshots and complete the description

**Comment by Aishjahan** [comment]
> Add screenshots and complete the description

Added screenshot

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Aishjahan take input from user

**Comment by Aishjahan** [comment]
> @Aishjahan take input from user

I have completed the requested changes , here are the screenshots : 

Screenshot 2023-06-11 182214
Screenshot 2023-06-11 182542

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
