### PR TITLE
Implementation of XGboost algorithm in Python, Java, C++, C

### PR DESCRIPTION
**Pull request by derphalesh**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Please review the changes in each implementation and provide feedback on the code structure, algorithm implementation, and any potential improvements.
Thank you for your time and valuable feedback.

Best regards,
Phalesh Kolpe

## 📷 Screenshots
image

image

image

image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
remove ```.vscode/tasks.json``` & ```Java/Machine_Learning/README.md```

**Comment by derphalesh** [comment]
> remove `.vscode/tasks.json` & `Java/Machine_Learning/README.md`

removed the asked files.

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
@derphalesh Is this code generated by ChatGPT?

Because the same code got generated for me:
image

And, a human programmer would never type ```std::``` so many times, instead he/she would prefer ```using namespace std``` in C++ codes

**Comment by Kumar-laxmi** [comment]
image

**Comment by derphalesh** [comment]
> @derphalesh Is this code generated by ChatGPT?
> 
> Because the same code got generated for me: image
> 
> And, a human programmer would never type `std::` so many times, instead he/she would prefer `using namespace std` in C++ codes

Sorry for that sir I wanted to raise pr as soon as possible as I got the deadline that's why I used gpt code in my code for Java and cpp I will do the code for that again. Please give me 5-6 days  as I am new to cpp and Java.

**Pull request closed without merging**
