### PR TITLE
Added edit distance in dynamic programming in C++ 

### PR DESCRIPTION
**Pull request by sumitkr2000**
## 🛠️ Issue (Number)

issue no #293

## 👨‍💻 Changes proposed

I have added the famous algorithm in dynamic programming to find the minimum number of operations required to convert one word to another word. Please accept my PR. Thank you!

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot (528)

### CODE REVIEW

**Comment by sumitkr2000** [comment]
@Rishikavishnoi already mentioned it

**Review by Rancho2002 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
approve @Rishikavishnoi

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Comment by sumitkr2000** [comment]
@Kumar-laxmi merge

**Comment by sumitkr2000** [comment]
someone merge my pr very careless

**Comment by Kumar-laxmi** [comment]
> someone merge my pr very careless

What do you mean?

**Comment by sumitkr2000** [comment]
My pr is approved from 2 days now and still you are not merging

**Comment by sumitkr2000** [comment]
merge it so that I can raise new issue

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
