### PR TITLE
Tree Traversal in C++

### PR DESCRIPTION
**Pull request by Gaurav-8604**
## 🛠️ Issue (Number)
Issue no #177 

## 👨‍💻 Changes proposed
Tree Traversals of Inorder, Preorder and Postorder with pseudocodes.
Also added README.md file

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image
image
image

image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Things to change:
- Please don't create sub folder for algorithm
- Instead implement the algorithm in one single file (Eg. Menu driven)
- Remove _a.exe_

**Comment by Kumar-laxmi** [comment]
@Gaurav-8604 Implement the algorithm in all four languages

**Comment by Gaurav-8604** [comment]
@Kumar-laxmi  Please check my PR?

**Comment by Gaurav-8604** [comment]
@Kumar-laxmi Please check my Pr

**Comment by Gaurav-8604** [comment]
@Kumar-laxmi Please check my PR?

**Review by Rancho2002 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Approved !

**Review by 072arushi — APPROVED** [review]
Approved

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
