### PR TITLE
String Pattern matching-Zalgorithm

### PR DESCRIPTION
**Pull request by Ayatisonkar**
## 🛠️ Issue (Number)

Issue no #461

## 👨‍💻 Changes proposed
Added pattern-matching problem which helps in finding position of occurrence of given pattern in given string.
Solved problem in all four languages c,c++,java and python with proper comments.

## ✔️ Check List (Check all the applicable boxes) 

- [  ✔️ ] My code follows the code style of this project.
- [  ✔️ ] This PR does not contain plagiarized content.
- [  ✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
1)In C++
image
2)In C
image
3)In java
image
4)In Python
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please change file names to ```Z_Algorithm```

**Comment by Ayatisonkar** [comment]
@Kumar-laxmi sir I have changed the file names to Z_Algorithm

**Comment by Ayatisonkar** [comment]
@Rancho2002, @siddhi-244 , @Kumar-laxmi and @Rishikavishnoi please review my request.

**Review by Rancho2002 — APPROVED** [review]

**Comment by Ayatisonkar** [comment]
@siddhi244 , @Kumarlaxmi and @Rishikavishnoi please review my request.

**Comment by Ayatisonkar** [comment]
@siddhi-244 maam and @Kumar-laxmi sir

**Review by Rishikavishnoi — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Comment by Ayatisonkar** [comment]
@Kumar-laxmi sir please review my request I have made the necessary changes.

**Review by Kumar-laxmi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Ayatisonkar Kindly dm me your name, discord id and this PR number on discord so that I can update your scores

**Pull request merged**
