### PR TITLE
Create KMP Algorithm.c

### PR DESCRIPTION
**Pull request by MaYaNkKashyap681**
KMP Algorithm code in C

## 👨‍💻 Changes proposed

Added a C file for KMP Algorithm code

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

Problem Statement ->
Given a string text and pattern string, you need to tell whether a pattern exists in the text or not.
Example -> 
Input->
text = "aabababaabba", pattern = "ababaa" 
Output ->
Pattern Found in the Text!

Screenshot (127)

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]
Kindly add comments to explain your algorithm

**Review by Rancho2002 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
**COMPLETE YOUR DESCRIPTION**

**Comment by MaYaNkKashyap681** [comment]
> Kindly add comments to explain your algorithm

Is it ok now.

**Comment by MaYaNkKashyap681** [comment]
> **COMPLETE YOUR DESCRIPTION**

Is it fine now, or still there is some issue?

**Comment by Kumar-laxmi** [comment]
> > **COMPLETE YOUR DESCRIPTION**
> 
> Is it fine now, or still there is some issue?

Checkboxes are incomplete

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by MaYaNkKashyap681** [comment]
> > > **COMPLETE YOUR DESCRIPTION**
> > 
> > 
> > Is it fine now, or still there is some issue?
> 
> Checkboxes are incomplete

What is missing?

**Comment by Sanjanabharadwaj25** [comment]
> > > > **COMPLETE YOUR DESCRIPTION**
> > > 
> > > 
> > > Is it fine now, or still there is some issue?
> > 
> > 
> > Checkboxes are incomplete
> 
> What is missing?
Check the boxes in the description that applies to your PR.

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please make the program user input driven

**Comment by Kumar-laxmi** [comment]
@MaYaNkKashyap681 Kindly make the required changes within one week or else the PR will be closed as ```Stale``` PR

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
