### PR TITLE
Detect loop in a linked list in cpp #122

### PR DESCRIPTION
**Pull request by Vyshnavi21504**
# 🛠️ Issue (Number)
Issue no #122

## 👨‍💻 Changes proposed
Detect loop in a linked list in cpp 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
ss

### CODE REVIEW

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Write approach in comment lines

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your algorithm

**Review by 072arushi — APPROVED** [review]

**Comment by Vyshnavi21504** [comment]
I have done the changes. pls check once

**Review by 072arushi — COMMENTED** [review]
Can you implement this algorithm in python and java as well?

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove binary_search.exe file

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@Vyshnavi21504 Add screenshots of the program in the PR description.

**Comment by Vyshnavi21504** [comment]
Yes, I can implement this algorithm in python and java .

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Mention the issue number of Binary Search also & change the file name from ```index.cpp``` to ```Detect_loop_Linked_List.cpp```

**Comment by Kumar-laxmi** [comment]
And also include the screen shot of binary search

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please mention the issue number of ```Binary Search``` & please use appropriate file name instead of ```index.cpp```

**Comment by Vyshnavi21504** [comment]
I have done the changes. pls check once

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Vyshnavi21504 Kindly resolve the merge conflict

**Comment by Kumar-laxmi** [comment]
@Vyshnavi21504 Kindly resolve the **Merge Conflict** within one week or else this PR will be marked ```Stale``` and will be closed

**Comment by Vyshnavi21504** [comment]
I have done the changes . please check

**Pull request closed without merging**
