### PR TITLE
Ternary search and binet formula

### PR DESCRIPTION
**Pull request by sinhasaurabh079**
## 🛠️ Issue (Number) 

Issue no #484 #485 

## 👨‍💻 Changes proposed

I have added the following code in c, c++, java, python
   -> Ternary Search 
   -> Binet Formula
All the codes are explained well in comments

## ✔️ Check List (Check all the applicable boxes) 

- [ ✅] My code follows the code style of this project.
- [✅ ] This PR does not contain plagiarized content.
- [ ✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
* Some information related to ternary search like application, when to use, benefits  are taken from the internet source
* I have only included the screenshot of one code 

## 📷 Screenshots
carbon(1)

carbon(6)

# Output
## Binet Formula
Screenshot from 2023-02-04 22-00-17
## Ternary Search
Screenshot from 2023-02-04 22-01-48

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]
Good contribution

**Review by siddhi-244 — APPROVED** [review]

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@sinhasaurabh079 please do include the screenshot of the outputs too.

**Comment by sinhasaurabh079** [comment]
> @sinhasaurabh079 please do include the screenshot of the outputs too.

I have attached the screenshot of output.
Note : The output is same for each language code.

**Review by zugzwang03 — APPROVED** [review]

**Comment by sinhasaurabh079** [comment]
> Good contribution

Thanks

**Review by Arun9739 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@sinhasaurabh079 The screenshots of output is enough, please don't post the screen shot of code

**Pull request merged**
