### PR TITLE
Next Greater Element

### PR DESCRIPTION
**Pull request by viveksondhiya**
## 🛠️ Issue (Number)

Issue no #376

## 👨‍💻 Changes proposed
   Next Greater Element in java

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- Add C file alse
- In Java Folder upload a ```.java``` file

**Review by 072arushi — CHANGES_REQUESTED** [review]
Can you implement this in other languages as well?

**Comment by viveksondhiya** [comment]
Yup .. I am working on c language as well

**Review by zugzwang03 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@viveksondhiya Kindly include the implementation in ```C``` in this PR

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@viveksondhiya Take input from user, instead of giving directly in a program.
Add a 'java' file here. The file added here doesn't contains the '.java' extension.

**Comment by viveksondhiya** [comment]
done ..please check it

**Comment by Arun9739** [comment]
@viveksondhiya Plz add a java file here

**Comment by viveksondhiya** [comment]
> @viveksondhiya Plz add a java file here You have added a file which doesn't has any extension

deleting this pull request and again creating pull request for this issue

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi  I can implement this in python. Can you please assign?

**Pull request closed without merging**
