### PR TITLE
CircularLinkedList in C language

### PR DESCRIPTION
**Pull request by Mridul-2003**
## 🛠️ Issue (Number)

Issue no #

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by zugzwang03** [comment]
> ## 🛠️ Issue (Number)
> Issue no #
> 
> ## 👨‍💻 Changes proposed
> ## ✔️ Check List (Check all the applicable boxes)
> * [ ]  My code follows the code style of this project.
> * [ ]  This PR does not contain plagiarized content.
> * [ ]  The title of my pull request is a short description of the requested changes.
> 
> ## 📄 Note to reviewers
> ## 📷 Screenshots

Kindly link your issue with the PR

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Comment by Kumar-laxmi** [comment]
Inactive PR

**Comment by Mridul-2003** [comment]
In this program I have created a structure node which takes data and pointer names as next. 
In which head nodes points to second node,  second node points to third node and third node points to head node.  And traversing is done until ptr! =head.

**Comment by Mridul-2003** [comment]
Plz open this pull request again.

**Comment by zugzwang03** [comment]
> Plz open this pull request again.

you can reopen it, or create another PR

**Comment by Arun9739** [comment]
@Mridul-2003 Please create a new proper PR by following the contributing guidelines

**Pull request closed without merging**
