### PR TITLE
sha-256 in C, C++, python, java

### PR DESCRIPTION
**Pull request by MrKoshens**
## 🛠️ Issue (#563 )

Issue no #563 

## 👨‍💻 Changes proposed

Added complete python code for SHA-256.

## ✔️ Check List (Check all the applicable boxes) 

- [* ] My code follows the code style of this project.
- [* ] This PR does not contain plagiarized content.
- [* ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
The pr title is SHA alho in c,c++,Python and Java but I can't see c and c++ files

**Comment by MrKoshens** [comment]
> The pr title is SHA alho in c,c++,Python and Java but I can't see c and c++ files

I will add the C and C++ files today. They are still unfinished.

**Review by zugzwang03 — APPROVED** [review]

**Review by Rancho2002 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Rishikavishnoi — COMMENTED** [review]
@MrKoshens add the C and C++ files also

**Comment by MrKoshens** [comment]
> 

I added all the codes. Please check

**Review by Rishikavishnoi — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Change the file names to ```SHA256```

**Comment by MrKoshens** [comment]
> Change the file names to `SHA256`

I have changed the names to SHA256. Please check

**Pull request merged**
