### PR TITLE
First In First Out (FIFO) | Caching in C, C++, PYTHON, JAVA

### PR DESCRIPTION
**Pull request by anand-harsh**
## 🛠️ Issue (Number)

Issue no #1278 

## 👨‍💻 Changes proposed

First In First Out (FIFO) in C, C++, PYTHON, JAVA

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

In this algorithm, operating system keeps track of all pages in the memory in a queue, oldest page is in the front of the queue. When a page needs to be replaced page in the front of the queue is selected for removal.

## 📷 Screenshots

firstInFirstOut.c

image

firstInFirstOut.cpp

image

firstInFirstOut.py

image

firstInFirstOut.java

image

### CODE REVIEW

**Comment by anand-harsh** [comment]
@Kumar-laxmi kindly review it please

**Comment by anand-harsh** [comment]
@Kumar-laxmi please review this PR

**Comment by anand-harsh** [comment]
@Kumar-laxmi kindly review this PR please

**Comment by anand-harsh** [comment]
@Kumar-laxmi please review the PR

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Just name the files as "FIFO"

**Review by zugzwang03 — APPROVED** [review]

**Comment by anand-harsh** [comment]
@Kumar-laxmi Changes made

**Comment by anand-harsh** [comment]
@Kumar-laxmi Changes made

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Pull request closed without merging**
