### PR TITLE
Added Pascal Triangle in C,C++,Python, Java

### LINKED ISSUE #812: ADD Pascal's Triangle in C++
The **Pascal's Triangle** is a triangular array of binomial coefficients. Each number in the triangle is the sum of the two numbers directly above it.
for example-
        1
      1   1
    1   2   1
  1   3   3   1
1   4   6   4   1

Feature:
Add Pascal's Triangle Algorithm in C++.

Can you please assign me this issue under SSoC'23.

### PR DESCRIPTION
**Pull request by Sh4dab**
## 🛠️ Issue (Number)
`Closes #812`

Issue no #812 

## 👨‍💻 Changes proposed
Added the Pascal's Triangle code in C,C++,Python and Java

Added 4 new code files.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Put the program file inside maths folder

**Comment by Sh4dab** [comment]
Done moved the files to maths folder

**Review by zugzwang03 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Share the output screen shots

**Comment by Sh4dab** [comment]
Output ss-
C
image
C++
image
Python
image
Java
image

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add comments explaining your approach

**Comment by Sh4dab** [comment]
Done, I have added the comments.

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
