### PR TITLE
Spiral Print Matrix in C

### PR DESCRIPTION
**Pull request by VaibhavArora314**
## 🛠️ Issue 466

Issue no #466 

## 👨‍💻 Changes proposed

In this pr, I have added an algorithm for spiral print on a matrix in C.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

image
image
image

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
Please review my pr @Kumar-laxmi @072arushi @zugzwang03 @Arun9739.

**Review by 072arushi — CHANGES_REQUESTED** [review]
Can you code this in python and Java as well

**Comment by VaibhavArora314** [comment]
> Can you code this in python and Java as well

I can do that but they are currently assigned to someone else. If that is not a problem then I will add them.

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Place this file in ```arrays``` folder

**Comment by VaibhavArora314** [comment]
> Place this file in `arrays` folder

Done

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
