### PR TITLE
Adding KNN algorithm in Python 

### LINKED ISSUE #961: Adding Euler’s Totient function
Euler’s Totient function Φ (n) for an input n is the count of numbers in {1, 2, 3, …, n-1} that are relatively prime to n, i.e., the numbers whose GCD (Greatest Common Divisor) with n is 1.
Φ(1) = 1  
gcd(1, 1) is 1

Φ(2) = 1
gcd(1, 2) is 1, but gcd(2, 2) is 2.

Φ(3) = 2
gcd(1, 3) is 1 and gcd(2, 3) is 1

Φ(4) = 2
gcd(1, 4) is 1 and gcd(3, 4) is 1

i can code this in c++,java and python with prorper documentation.
@Kumar-laxmi can you assign this to me unders ssoc23?

### PR DESCRIPTION
**Pull request by ayan-joshi**
## 🛠️ Issue (Number)

Issue no #929 

## 👨‍💻 Changes proposed

As said in the issue I added the KNN algorithm in Python without using ML libraries also provided the readme file for proper explaination , I was not able to do for the java.
As my machine not supporting java files 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

@Kumar-laxmi please look out my pull request will be thankful to you

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please include Java file and please test it on bigger dataset

**Comment by ayan-joshi** [comment]
okay I'll test on bigger data set but can't add the java file as my machine's not supporting  java 
will it be ok @Kumar-laxmi

**Comment by ayan-joshi** [comment]
I did the change in python file and took a bigger dataset Iris , and as I explained cant commit for java as my machine is not supporting java please review my changes @Kumar-laxmi

**Comment by ayan-joshi** [comment]
@Kumar-laxmi sir please review my work and comment

**Comment by Kumar-laxmi** [comment]
Then you can try it on Virtual Machine

**Comment by ayan-joshi** [comment]
Yes sir tried in last 2 days but was not able to apply it in java but completed in python as you requested @Kumar-laxmi

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- Put the program file inside ```Machine Learning``` folder
- No need to create separate folder for KNN
- Remove README.md
- Instead add the README.md content into the program as comment

**Comment by ayan-joshi** [comment]
@Kumar-laxmi did the following changes u requested

**Review by Kumar-laxmi — COMMENTED** [review]
image

Does it mean that this PR doesn't comply with any of these?

**Comment by Kumar-laxmi** [comment]
@Arun9739 @072arushi @zugzwang03 Kindly review this PR

**Review by zugzwang03 — APPROVED** [review]

**Comment by ayan-joshi** [comment]
> image
> 
> Does it mean that this PR doesn't comply with any of these?

sorry for mistake I updated it now @Kumar-laxmi

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@ayan-joshi Add output screenshot

**Comment by ayan-joshi** [comment]
> Please include Java file and please test it on bigger dataset

Screenshot (187)

**Review by Arun9739 — APPROVED** [review]

**Comment by ayan-joshi** [comment]
@Kumar-laxmi got approvals please merge the request

**Pull request closed without merging**
