### PR TITLE
Beautiful string Algorithm

### PR DESCRIPTION
**Pull request by atul1510**
## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Atul has been given a binary string ‘STR’ containing either ‘0’ or ‘1’. A binary string is called beautiful if it contains alternating 0s and 1s.
For Example:‘0101’, ‘1010’, ‘101’, and ‘010’ are beautiful strings.
## 📷 Screenshots
Screenshot (116)

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]

**Comment by 072arushi** [comment]
Approved

**Comment by Kumar-laxmi** [comment]
@atul1510 Please mention the issue number of Wave sort if you are adding the code

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
@atul1510 Please mention the issue number of Wave sort if you are adding the code & implement Beautiful string algorithm in all four languages

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Add a few comment lines explaining your approach

**Comment by atul1510** [comment]
I'm creating a new PR for Beautiful String because I had wrongly added Wave Sort in this PR

**Pull request closed without merging**
