### PR TITLE
Implementation of Fibonacci Series

### PR DESCRIPTION
**Pull request by sitamgithub-MSIT**
## 🛠️ Issue (#409)

Issue no #409

## 👨‍💻 Changes proposed
Implemented the fibonacci series in all 4 languages both recursive and dynamic ways. 

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

> ## 📄 Note to reviewers
In the code both recursive and dynamic methods are done. Also both finding nth term in the series as well the entire sequence up to that term are done.

> ## 📷 Screenshots
Screenshot (150)
Screenshot (151)
Screenshot (152)
Screenshot (145)

### CODE REVIEW

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Now can you please check? Hope it is clear now.

**Comment by Kumar-laxmi** [comment]
@sitamgithub-MSIT I will review it but it won't be scored under SWOC

**Comment by sitamgithub-MSIT** [comment]
> @sitamgithub-MSIT I will review it but it won't be scored under SWOC

Why? You said that PR has to be under the timeline you gave earlier and I did that way before!!!

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
All the files are placed in the ```C```, please place them in the respective folders

**Pull request closed without merging**
