### PR TITLE
Adding longest common subsequence in c language

### PR DESCRIPTION
**Pull request by diyagoyal98**
## 🛠️ Issue (Number) 286

Issue no #286

## 👨‍💻 Changes proposed
Implemented Longest Common subsequence in c language.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
#Code small part screenshot

# output
image

### CODE REVIEW

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@diyagoyal98 Add some comments in the code explaining your approach
Correct the spelling of a filename

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your approach

**Comment by diyagoyal98** [comment]
I have added the comments now review it please.

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
Explain approach in comment lines

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Change the filename Longest_comon_subsequence.c  to Longest_common_subsequence.c
It was mistyped, correct it!

**Review by 072arushi — APPROVED** [review]

**Comment by diyagoyal98** [comment]
sir please check #545  I have made all the changes.
1->Added Comments
2->Changed file name

**Comment by Arun9739** [comment]
@diyagoyal98 If you have created new PR for the same issue, then just close this.

**Pull request closed without merging**
