### PR TITLE
Red black tree in java 

### PR DESCRIPTION
**Pull request by ManavLohia945**
## 🛠️ Issue (Number)

Issue no #91 

## 👨‍💻 Changes proposed

I am creating this new Pull request as requested by you referencing the old closed PR #220 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by zugzwang03 — APPROVED** [review]

**Comment by ManavLohia945** [comment]
okay will do it right away !!

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Take input from user instead of giving it in program.

**Review by 072arushi — CHANGES_REQUESTED** [review]
The user should give inputs instead of default input

**Comment by ManavLohia945** [comment]
Done Pasting ss below 
image
image
image

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
