### PR TITLE
Added logistic Regression in C and Java

### PR DESCRIPTION
**Pull request by Khushi-74**
I have added implementation of logistic regression algorithm in java and c please review it

## 🛠️ Issue (Logistic regression in java)

Issue no #892 

## 👨‍💻 Changes proposed

I have added the implementation of logistic regression in java

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

*Screenshot*
JAVA Output
java ss

C Output
c screenshot

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@Khushi-74 Please raise one single PR for Logistic Regression, kindly close either of the PR

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
You can add your C program in this PR

**Comment by Khushi-74** [comment]
I have added

**Review by zugzwang03 — APPROVED** [review]

**Comment by mrigankabrahma** [comment]
assign me this issue

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove the space from the name of program file in C

**Review by 072arushi — APPROVED** [review]

**Comment by Khushi-74** [comment]
> Remove the space from the name of program file in C

done @Kumar-laxmi

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Khushi-74 Add output screenshot

**Comment by Khushi-74** [comment]
> @Khushi-74 Add output screenshot

Sure I am on it

**Comment by Khushi-74** [comment]
> @Khushi-74 Add output screenshot

I have added output screenshot

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
