### PR TITLE
hammingDistance theorem codded in c++ , c,  java and python

### LINKED ISSUE #896: Hamming Distance
**Is your feature request related to a problem? Please describe.**
I would like to work on this feature where we can find the hamming distance

**Describe the solution you'd like**
I would like to implement this feature using cpp as i was not able to find one under math category ...

Please assign it to me @Kumar-laxmi under SSOC 2023

### PR DESCRIPTION
**Pull request by rakshitdabral**
`Closes #896 `
## 🛠️ Issue (Number)

Issue no #896 

## 👨‍💻 Changes proposed

added code for hamming distance theorem in c++ , java, c and python 
## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by rakshitdabral** [comment]
> @rakshitdabral Add output screenshot

done

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Take input from user, remove .exe files

**Comment by rakshitdabral** [comment]
> Take input from user, remove .exe files

done

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please place the programs in ```binary``` folder

**Comment by rakshitdabral** [comment]
> Please place the programs in `binary` folder

done

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
