### PR TITLE
Converting binary to decimal and decimal to binary equivalent in C and Python

### PR DESCRIPTION
**Pull request by Abhilash1781**
## 🛠️ Issue (270)

Issue no #270 

## 👨‍💻 Changes proposed
Uploaded the file binary_to_decimal_&_decimal_to_binary.c in the maths folder  (C)
Uploaded bin_to_dec_&_dec_to_bin.py file in maths folder (Python)
Previously I updated Readme file but @Kumar-laxmi sir suggested to not update the file as it may cause branch conflicts . 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
C and python programs to convert binary to decimal and decimal to binary 
(Explicit input )

## Output for C Program
d_b_b_d

 ## Output for Python Program 

Algorithms_ github at main · Kumar-laxmi_Algorithms - Google Chrome 26-01-2023 13_48_24

### CODE REVIEW

**Comment by Abhilash1781** [comment]
@Kumar-laxmi

**Comment by Abhilash1781** [comment]
@zugzwang03 @072arushi

**Review by 072arushi — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Abhilash1781 Is it possible for you to implement this in Python too

**Comment by Abhilash1781** [comment]
@Kumar-laxmi Sure sir .

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Pull request merged**
