### PR TITLE
Added Fisher-Yates Algorithm In C++ , C, Python and Java

### PR DESCRIPTION
**Pull request by shravanii2308**
## 🛠️ Issue (#1093 )

Issue no #1093 

## 👨‍💻 Changes proposed
Added Fisher-Yates Algorithm in C++, C, Python, and Java under arrays.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Please review my PR.

## 📷 Screenshots
In C++
[
image
](url)

In C
[
image
](url)

In Java
[
image
](url)

In Python
[
image
](url)

### CODE REVIEW

**Comment by MisterMickey** [comment]
Looks Good Now!✌

**Comment by shravanii2308** [comment]
@Kumar-laxmi review my PR

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by shravanii2308** [comment]
@Kumar-laxmi i dont know how skip list got added in this PR what should i do now

**Review by zugzwang03 — APPROVED** [review]

**Comment by shravanii2308** [comment]
> @shravanii2308 Take input from user in the program

@Arun9739 done!! please review my PR

**Review by zugzwang03 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
