### PR TITLE
Algorithm to convert Binary Tree into Binary Search Tree in c++

### PR DESCRIPTION
**Pull request by Durgesh4993**
## 🛠️ Issue (Number)

Issue no #250 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

image

image

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Aaditya1612** [comment]
@Durgesh4993 This issue was created by me and has not yet been assigned. You cannot make PR referencing this Issue #250

**Comment by Durgesh4993** [comment]
@Aaditya1612 you can also work in java, Pythan also if you have any related issue then i will try to our help

**Comment by Durgesh4993** [comment]
if you want may i close this PR then tell me i deffinetly close

**Comment by Aaditya1612** [comment]
@Durgesh4993 No need to close your PR. You have worked for it. Let's wait for project owner's reply if he will accept or not.
@Kumar-laxmi please have a look in matter.

**Comment by Kumar-laxmi** [comment]
@Durgesh4993 Please don't open a PR without getting the issue assigned to you

**Comment by Kumar-laxmi** [comment]
Since this issue was opened by @Aaditya1612 and C++ language was requested by him, I can only approve this PR if he allows to give you the C++ part. Till then this PR would remain in ```STAND BY```

**Pull request closed without merging**
