### PR TITLE
Perceptron Learning Boolean And , OR functions

### PR DESCRIPTION
**Pull request by Harikaraja**
## 🛠️ Issue (Number) 

Issue no #441 , #530

## 👨‍💻 Changes proposed

Added perceptron learning  boolean function

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly mention the issue number for ```Railfence Cipher```

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please don't create separate folder for each algorithm

**Comment by Harikaraja** [comment]
Ok Sir . Do I need to add Railfence Cipher directly in c++ -> Cryptography ? 

How to add readme file sir

**Comment by Kumar-laxmi** [comment]
> Ok Sir . Do I need to add Railfence Cipher directly in c++ -> Cryptography ?
> 
> How to add readme file sir

Add the readme content as comment in the beginning of program file

**Comment by Kumar-laxmi** [comment]
And you need to add directly to C++ -> Cryptography

**Comment by Harikaraja** [comment]
Ok sir

**Review by Rancho2002 — APPROVED** [review]

**Pull request closed without merging**
