### PR TITLE
Implementation of Dutch National Flag Algorithm in C

### PR DESCRIPTION
**Pull request by sitamgithub-MSIT**
## 🛠️ Issue (#193 )

Issue no #193 

## 👨‍💻 Changes proposed
Implemented and uploaded Dutch National Flag algorithm in C. 

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I have given a description about the algo and then the coding part done in C language with proper commenting of the code. 

## 📷 Screenshots
Screenshot (143)

### CODE REVIEW

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Please review the PR.

**Comment by sitamgithub-MSIT** [comment]
> @Kumar-laxmi Please review the PR.

@072arushi @Arun9739 @siddhi-244 please review the PR.

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by sitamgithub-MSIT** [comment]
@Kumar-laxmi Now can it be merged?

**Comment by Kumar-laxmi** [comment]
All SSoC'23 PRs will be accepted after 1st June 2023

**Pull request closed without merging**
