### PR TITLE
#Issue 768 - Implementation of Binary Tree Transversal in all Four Languages

### PR DESCRIPTION
**Pull request by AnubhaSharma2709**
## 🛠️ Issue 768
issue no. #768 

## 👨‍💻 **Implementation of Binary Tree Traversal in Java, C, C++ and Python**

#The Approach followed by me is as followed:-
#1. The user can dynamically input the binary tree and perform the Traversal.
#2. I have used linked list for implementation of the program.
#3. I have used recursion in the program to perform Traversal.

Please Review my Code under SSOC-2023

## Java Output
Java Output

## C Output
c output

## Python Output
python output

## C++ Output
C++ output

### CODE REVIEW

**Comment by AnubhaSharma2709** [comment]
> Thanks for your contribution we will soon check your PR @AnubhaSharma2709 :)

I am really not understanding the issue created by CodeFactor in Java Program.
Please Help
Thankyou

**Comment by Kumar-laxmi** [comment]
> > Thanks for your contribution we will soon check your PR @AnubhaSharma2709 :)
> 
> I am really not understanding the issue created by CodeFactor in Java Program. Please Help Thankyou

**CodeFactor** is just a Bot which analyzes your code

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove .class files

**Comment by AnubhaSharma2709** [comment]
@zugzwang03 
@Kumar-laxmi 
Sorry for suddenly closing the pull request. I have removed the .class files and made the changes. 
Kindly review my code. 
There are total four files.
Thankyou!

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@AnubhaSharma2709 Add output screenshot

**Review by 072arushi — APPROVED** [review]

**Comment by AnubhaSharma2709** [comment]
> @AnubhaSharma2709 Add output screenshot

Sir I have added the output screenshot 
Kindly Review the same
Thankyou

**Review by Arun9739 — APPROVED** [review]

**Pull request closed without merging**
