### PR TITLE
Added Morris Preorder Traversal in Trees under C++

### PR DESCRIPTION
**Pull request by dhruti26**
## 👨‍💻 Changes proposed

Added the code of Morris preorder Traversal in C++

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

please review my PR

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by dhruti26** [comment]
please review my PR @Kumar-laxmi

**Comment by dhruti26** [comment]
Please review my PR @Kumar-laxmi , i have added Morris Traversal (Preorder) code and it is working!!

**Comment by dhruti26** [comment]
Please review my PR @072arushi and tell me if some changes needed

**Comment by dhruti26** [comment]
Please review my PR @Kumar-laxmi @072arushi and tell me if some changes needed

**Review by 072arushi — CHANGES_REQUESTED** [review]
you need to provide code in java, C and python as well

**Pull request closed without merging**
