### PR TITLE
 Added Shortest common Supersequence problem in java , C ,C++ an Python.

### LINKED ISSUE #705: Add Shortest Common Supersequence Problem using Dynamic Programming in java .
I want to add Shortest Common Supersequence Problem using Dynamic Programming in java .

Screenshot 2023-05-30 235150

Please assign me this issue.

### PR DESCRIPTION
**Pull request by Aishjahan**
Issue no #705

## 👨‍💻 Changes proposed

Added Shortest common Supersequence problem in:
1. JAVA
2. C++
3. C
4. PYTHON

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot 2023-05-31 125215

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
Kindly sort **CodeFactor** issues

**Comment by Aishjahan** [comment]
I have resolved the codeFactor issue, please review it.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Is task.json really needed ? If it's not please remove it.

**Comment by Aishjahan** [comment]
> Is task.json really needed ? If it's not please remove it.

Sorry for the inconvenience but I cannot find any task.json file on my local vs code environment.

**Comment by Aishjahan** [comment]
> Is task.json really needed ? If it's not please remove It.

Removed it , please review.

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove .exe files

**Comment by Aishjahan** [comment]
> remove .exe files

Removed .exe files.

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
