### PR TITLE
DFS BFS Issue-186

### PR DESCRIPTION
**Pull request by Gaurav-8604**
## 🛠️ Issue (Number)

Issue no #186 

## 👨‍💻 Changes proposed
Added dfs.cpp and bfs.cpp file.

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by Gaurav-8604** [comment]
@Kumar-laxmi  Please check my PR?

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by Gaurav-8604** [comment]
@siddhi-244  and @Arun9739  Please check??

**Review by siddhi-244 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Approved

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
