### PR TITLE
Added implementation for Reverse Integer algorithm (Maths) in Python

### LINKED ISSUE #239: Reverse integer Algorithm in C++
I want to add a Reverse integer algorithm and for this, I would like to code the solution for this problem in C++ language.
Problem Description 
You are given an integer N and the task is to reverse the digits of the given integer. Return 0 if the result overflows and does not fit in a 32-bit signed integer.
@Kumar-laxmi sir please assign me this issue.

### PR DESCRIPTION
**Pull request by stiwari-ds**
## 🛠️ Issue (Number)

Issue no #239

## 👨‍💻 Changes proposed

Added implementation for reverse integer algorithm (Maths folder) in Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Code:
code1

code2

Outputs:
output1
output2
output3
output4
output5
output6

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by stiwari-ds** [comment]
@Rishikavishnoi Please review.

**Comment by stiwari-ds** [comment]
@Arun9739 @zugzwang03 @Kumar-laxmi Requesting a review. Thank you.

**Comment by stiwari-ds** [comment]
@Kumar-laxmi Since there are 3 reviews done already, can this PR be merged now? Thanks.

**Review by Rishikavishnoi — APPROVED** [review]

**Pull request merged**
