### PR TITLE
Prims Algorithm

### PR DESCRIPTION
**Pull request by ayushete02**
## 🛠️ Issue (Number)

Issue no #61 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot 2023-02-14 184855

### CODE REVIEW

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Add some comments explaining your approach

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
add comments

**Review by Rishikavishnoi — COMMENTED** [review]
@ayushete02 Any Update ..? Just add some comments

**Comment by ayushete02** [comment]
> @ayushete02 Any Update ..? Just add some comments

Done

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by ayushete02** [comment]
@Kumar-laxmi Update and Merge

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Move this file to ```Graphs``` folder

**Comment by ayushete02** [comment]
Check @Kumar-laxmi

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
