### PR TITLE
Added Peterson Algorithm in C , C++, Python, Java

### PR DESCRIPTION
**Pull request by kamalyash2002**
## 🛠️ Issue (#1253)

Issue no #1253 

## 👨‍💻 Changes proposed

Added Peterson Algorithm in C , C++, Python, Java

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Please review my PR and any constructive changes are welcome.

## 📷 Screenshots
C Code
Screenshot 2023-06-14 at 3 53 51 PM

C++ Code
Screenshot 2023-06-14 at 3 54 31 PM

Python Code
Screenshot 2023-06-14 at 3 56 20 PM

Java Code
Screenshot 2023-06-14 at 3 57 51 PM

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove ```C/Concurrent Algorithms/peterson_algo```

**Review by zugzwang03 — APPROVED** [review]

**Comment by kamalyash2002** [comment]
> Remove `C/Concurrent Algorithms/peterson_algo`

Deleted the above mentioned file @Kumar-laxmi
Please review the changes.
Thanks.

**Review by Arun9739 — APPROVED** [review]

**Comment by kamalyash2002** [comment]
Please review my PR @Kumar-laxmi  . I have done the changes suggested by the you. 
Thanks.

**Comment by kamalyash2002** [comment]
Please review my PR @072arushi thanks !!

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by kamalyash2002** [comment]
Please review my PR @Kumar-laxmi thanks !!

**Comment by kamalyash2002** [comment]
Please review my PR @Kumar-laxmi thanks !!

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
