### PR TITLE
Added Merge_Interval Algorithm

### PR DESCRIPTION
**Pull request by atul1510**
## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Problem Statement: Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, 
and return an array of the non-overlapping intervals that cover all the intervals in the input.

## 📷 Screenshots

Screenshot (127)

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@atul1510 Could you implement this algorithm in all four languages

**Comment by atul1510** [comment]
> @atul1510 Could you implement this algorithm in all four languages

Yes, Sure I Can implement this algorithm in all four languages.
@Kumar-laxmi  sir, You can assign me in C/C++/Java/Python languages.

**Comment by Kumar-laxmi** [comment]
After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

**Comment by atul1510** [comment]
> After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

Ok Got it, sir

**Comment by atul1510** [comment]
> After implementation in all four languages the PR will be reviewed, till then it will be in **standby**

Done with all changes requested, @Kumar-laxmi @zugzwang03 @072arushi @Arun9739 Please review it

**Review by Rishikavishnoi — APPROVED** [review]
@atul1510  approved 👍

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
Approved

**Review by Arun9739 — APPROVED** [review]
Approved !

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
