### PR TITLE
M-Coloring Algorithm in C,C++, Java and python

### PR DESCRIPTION
**Pull request by dhruti26**
issue No #1192

## 🛠️ Issue (Number)

Issue no #1192

## 👨‍💻 Changes proposed

The code for M-Coloring Algorithm in C,C++,Java and python added

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Output of C++ : 
image

Output of C : 
image

Output of Java :
image

Output of Python : 
image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes to be done:
- Remove the Exe file
- Remove Morris Traversal's programs
- Give a uniform name to all program files

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove .exe files

**Comment by dhruti26** [comment]
@zugzwang03 @Kumar-laxmi changes are done please check it.

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by dhruti26** [comment]
@Kumar-laxmi Please review my PR

**Comment by dhruti26** [comment]
@Kumar-laxmi Please review my changes and approved my PR

**Comment by Kumar-laxmi** [comment]
Still Morris Traversal file is visible in the CodeSpace

image

**Comment by dhruti26** [comment]
@Kumar-laxmi In Morris Traversal file, my added code is already deleted, this file just contain the code which was contributed  by other contributor before.

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi In Morris Traversal file, my added code is already deleted, this file just contain the code which was contributed by other contributor before.

That's what I am implying, if I merge this PR then it would delete that file or may lead to other inconsistencies. Basically the changes in your PR has most probably created inconsistency in your branch.

Kindly close this PR & delete the branch. Create a new branch and a PR from that and ensure only these 4 files are added to it and then in PR description give reference to this PR so that PR gets merges ASAP without any mentor approval

**Pull request closed without merging**
