### PR TITLE
Power set of a set of elements in C, C++, Java and Python #1339

### PR DESCRIPTION
**Pull request by VISHALGUPTA100803**
Power set of a set of elements in C, C++, Java, and Python Issue number #1339
C++
Screenshot (20)

Python
Screenshot (21)

C
Screenshot (22)

Java
Screenshot (16)

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Place these programs in Maths folder, remove the folder ```Power Set``` & include the issue number in the PR description

**Comment by VISHALGUPTA100803** [comment]
I have made the changes @Kumar-laxmi

**Comment by VISHALGUPTA100803** [comment]
made the changes you can check @Kumar-laxmi

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Comment by VISHALGUPTA100803** [comment]
@072arushi @Kumar-laxmi please check my PR

**Review by 072arushi — APPROVED** [review]

**Comment by VISHALGUPTA100803** [comment]
@Kumar-laxmi please review my PR

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
