### PR TITLE
Fractional Knapsack in C

### PR DESCRIPTION
**Pull request by khushigarg1**
## 🛠️ Issue (Number)

Issue no #73 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (77)

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove ```.exe``` file from the PR

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove the binary file

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@khushigarg1 Check the boxes in the PR description that apply to your PR.

**Comment by khushigarg1** [comment]
> remove the binary file

I am not able to delte bianry file whenever my previous pr dont get merge otherwise there will be branch conflicts, so I am making new pr

**Pull request closed without merging**
