### PR TITLE
Disjoint Set Union

### PR DESCRIPTION
**Pull request by SPARSH1608**
## 🛠️ Issue (Number)
Issue no #684

## 👨‍💻 Changes proposed
Add Finding Components in graph using Disjoint Set Union in C, C++ and Python.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code contains C, C++ , python and Java implementation to find Components in graph using Disjoint Set Union
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

c++1
c11
java11
python11

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
Kindly include screen shot of your output

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@SPARSH1608 Add output screnshot and resolve codefactor issues.

**Comment by SPARSH1608** [comment]
> @SPARSH1608 Add output screnshot and resolve codefactor issues.

in codefactor issues it says line 44 contain a blank line but in my code it contains a closing bracket , any way to solve this issue?

**Comment by Kumar-laxmi** [comment]
> > @SPARSH1608 Add output screnshot and resolve codefactor issues.
> 
> in codefactor issues it says line 44 contain a blank line but in my code it contains a closing bracket , any way to solve this issue?

Don't worry if it is so then ignore it

**Comment by Arun9739** [comment]
@SPARSH1608 Just add the output ss

**Review by 072arushi — APPROVED** [review]

**Review by 072arushi — CHANGES_REQUESTED** [review]
add screenshots

**Comment by SPARSH1608** [comment]
@Arun9739  @072arushi updated the code to solve all codefactor conflicts and added screenshots as well

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@SPARSH1608 Take input from user, instead of giving it in program.

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
You can make your output more presentable by adding print statements such that your output shows what is your input as well as output

**Comment by SPARSH1608** [comment]
@Kumar-laxmi taken input from user and printed it in an appropriate format .

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
