### PR TITLE
Added M-Coloring Algorithm in C,C++,Java and Python

### PR DESCRIPTION
**Pull request by dhruti26**
issue #1192

## 🛠️ Issue (Number)
Issue no #1192

## 👨‍💻 Changes proposed
New branch created and added all files, PR Reference #1208

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Please check PR reference #1208

### CODE REVIEW

**Comment by dhruti26** [comment]
@Kumar-laxmi Changes done as per your advice, please review it

**Review by Kumar-laxmi — APPROVED** [review]

**Review by Kumar-laxmi — COMMENTED** [review]
@dhruti26 It seems that your code is plagarised from https://www.geeksforgeeks.org/m-coloring-problem/, do you have any justification for this?

**Comment by dhruti26** [comment]
@Kumar-laxmi I was scared before as it was my first time, I will close this PR and if you allow me 1 day I can write my own code and submit it

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi I was scared before as it was my first time, I will close this PR and if you allow me 1 day I can write my own code and submit it

That is not required, kindly next time do not repeat such thing

**Pull request closed without merging**
