### PR TITLE
[SSoC 2.0] Number to Words Convertor Code Ready

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## 🛠️ Issue (Number) - 1043

Issue no #1043 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi Sir, please review this pr and requested to merge it into the main branch of this repository for a valuable contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please review this pr. I have created this pr last week but still no action is takes place on this pull request.

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi @zugzwang03 @Arun9739 @072arushi sir, i have created this pr last week but no action has done on this pr.
Please review this pr

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by Avdhesh-Varshney** [comment]
@Kumar-laxmi please review this pr and requested to merge this pr

**Pull request closed without merging**
