### PR TITLE
Intersection of two linked list in C, Java & Python

### PR DESCRIPTION
**Pull request by Rahulkottak**
## 🛠️ Issue (1404)

Issue no #1404 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
All your program files are missing the extension & allow user input instead of explicit linked list declaration

**Review by zugzwang03 — APPROVED** [review]

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
change the name of your files.
Don't put space in between

**Review by Rahulkottak — COMMENTED** [review]
File names have been changed to the correct format and also extensions have been added

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Rahulkottak Add output screenshot

**Pull request closed without merging**
