### PR TITLE
Caesar Cipher in java and C

### PR DESCRIPTION
**Pull request by MrKoshens**
Caesar Cipher is a simple substitution cipher that replaces each letter in the plaintext with a letter shifted a certain number of places down the alphabet. For example, with a shift of 1, A would be replaced by B, B would become C, and so on

## 🛠️ Issue (#497 )

Issue no #497 

## 👨‍💻 Changes proposed

Java code for Ceasar Cipher

## ✔️ Check List (Check all the applicable boxes) 

- [* ] My code follows the code style of this project.
- [* ] This PR does not contain plagiarized content.
- [* ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@MrKoshens Is it possible for you to implement this algo in ```C```

**Comment by MrKoshens** [comment]
> @MrKoshens Is it possible for you to implement this algo in ```C```

Yes i can implement it in C

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add comments to explain your algorithm. Also, can you code this in other languages as well?

**Comment by Kumar-laxmi** [comment]
> > @MrKoshens Is it possible for you to implement this algo in `C`
> 
> Yes i can implement it in C

You can include it as well then

**Comment by MrKoshens** [comment]
> > > @MrKoshens Is it possible for you to implement this algo in `C`
> > 
> > Yes i can implement it in C
> 
> You can include it as well then

I can do it in C and C++

**Comment by MrKoshens** [comment]
> Add comments to explain your algorithm. Also, can you code this in other languages as well?
> 

Yes i can do it in C and c++

**Comment by MrKoshens** [comment]
> Add comments to explain your algorithm. Also, can you code this in other languages as well?

I have made the changes. Please see the code

**Review by 072arushi — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changed to be done:
- Don't create addition folder for the algorithm
- Add the algorithm in ```C```

**Comment by MrKoshens** [comment]
> Changed to be done:
> 
>     * Don't create addition folder for the algorithm
> 
>     * Add the algorithm in `C`

I have made the required changes. please review
also do I add the c algorithm in this same PR?

**Comment by MrKoshens** [comment]
> Changed to be done:
> 
>     * Don't create addition folder for the algorithm
> 
>     * Add the algorithm in `C`

Please check the changes. I have made all necessary changes

**Comment by MrKoshens** [comment]
Please assign me this issue in python as well

**Review by 072arushi — APPROVED** [review]

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
remove a.out file

**Comment by MrKoshens** [comment]
> remove a.out file

I removed a.out file please check

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]
Very Nice!

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
