### PR TITLE
Fixed README; added algorithms

### PR DESCRIPTION
**Pull request by maitri-vv**
Youtube link is now visible in README, added few OS Algorithms.

## 🛠️ Issue (Number)
#1633 

Issue no #1633 
Closes: #1633 
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Fixed README

## 📷 Screenshots
image

### CODE REVIEW

**Comment by maitri-vv** [comment]
please add labels of SSOC :)

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove Job Scheduling files from this PR and do not make any changes in README.md

**Comment by Kumar-laxmi** [comment]
Resolve the Merge Conflict

**Review by zugzwang03 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
Kindly sort out **Merge Conflict**

**Pull request closed without merging**
