### PR TITLE
Intro Sort in C++, Python, JAVA

### PR DESCRIPTION
**Pull request by anand-harsh**
## 🛠️ Issue (Number)

Issue no #1226 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Intro sort is a hybrid sorting algorithm that combines quicksort, heapsort, and insertion sort to achieve efficient sorting performance. Here's a brief overview of how it works:

1.  The algorithm starts with quicksort, which selects a pivot element and partitions the array into two sub-arrays.

2. If the recursion depth exceeds a predetermined threshold, indicating the potential for worst-case behavior, the algorithm switches to an alternative sorting algorithm (typically heapsort).

3. The alternative sorting algorithm is used to sort the remaining unsorted sub-arrays. Heapsort has a guaranteed worst-case time complexity of O(n log n).

4. For small sub-arrays, the algorithm may further switch to insertion sort, which is efficient for such cases.

By dynamically adapting between quicksort, heapsort, and insertion sort based on the input data and recursion depth, intro sort achieves a balance between quicksort's average-case performance and the worst-case performance guarantees of alternative sorting algorithms. This makes it a highly efficient sorting algorithm for a wide range of input scenarios.

## 📷 Screenshots

intro_sort.cpp

image

intro_sort.py

image

intro_sort.java

image

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
The program in C is missing

**Comment by anand-harsh** [comment]
@Kumar-laxmi I have updated code in C also. Kindly verify the change

**Review by zugzwang03 — APPROVED** [review]

**Comment by anand-harsh** [comment]
Checking left

**Comment by anand-harsh** [comment]
Checking left

**Comment by anand-harsh** [comment]
Checking left

**Comment by anand-harsh** [comment]
Checking left

**Comment by Kumar-laxmi** [comment]
@anand-harsh Why did you close the PR

**Comment by anand-harsh** [comment]
> @anand-harsh Why did you close the PR

By mistake the forked repo got deleted and PR got closed automatically

**Pull request closed without merging**
