### PR TITLE
Added Edmonds-karp Algorithm Successfully

### PR DESCRIPTION
**Pull request by neeraj542**
## 🛠 Issue (#718)

Issue no #718

## 👨‍💻 Changes proposed
This pull request aims to enhance the efficiency and broaden the applicability of the Edmonds-Karp algorithm implementation by adding support for C, Java, and Python programming languages. The proposed changes include optimized C++ code for improved performance, Java code for wider language compatibility, and Python code for greater versatility. Additionally, enhanced documentation has been included to aid developers in understanding and utilizing the algorithm in multiple programming languages. These updates aim to provide developers with efficient and accessible solutions for maximum flow problems in C++, Java, and Python environments.

Please review the changes and consider merging them into the main repository.

## ✔ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
In the pseudocode, 'V' represents the number of vertices in the graph, 'residualGraph' refers to the residual capacities of the graph, and the graph represents the original 'graph' with capacities.

Thank you for reviewing this pull request. The changes include optimizations to the Edmonds-Karp algorithm implementation and the addition of Python code for improved versatility. Your feedback and suggestions are valuable to us, and we welcome any recommendations to enhance the algorithm further. We appreciate your time and collaboration in making this implementation more efficient and scalable.

## 📷 Screenshots
Python
image

C++
image

C 
image

JAVA
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
image

I think there is a mistake from your side while pushing the files

**Comment by Kumar-laxmi** [comment]
You have pushed deleted files

**Comment by neeraj542** [comment]
please tell me the right steps for it so that I can move ahead. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
I think you have corrupted your main branch due to which children branch are creating same mistake again

**Comment by Kumar-laxmi** [comment]
Which probably means you need to close this PR again, delete the forked repo and re-fork this repo, create a new branch from main branch, push your files in new branch and open a fresh PR

**Pull request closed without merging**
