### PR TITLE
Added Travelling Salesman Problem

### PR DESCRIPTION
**Pull request by papri24majumder**
## 🛠️ Issue (Number)

Issue no #170 

## 👨‍💻 Changes proposed

Added traveling salesman problem under dynamic programming in C

## ✔️ Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

output

### CODE REVIEW

**Comment by papri24majumder** [comment]
@Kumar-laxmi due to too many issues in my previous pr, I have closed that and created this pr. Kindly check. Thank you.

**Review by Arun9739 — CHANGES_REQUESTED** [review]
Plz add some comments explaining your approach
Rename the file in proper way such as TravellingSalesman.c or Travelling_salesman.c

**Comment by papri24majumder** [comment]
@Arun9739 done

**Review by Arun9739 — APPROVED** [review]
Approved !

**Review by zugzwang03 — APPROVED** [review]

**Comment by papri24majumder** [comment]
@Sanjanabharadwaj25 please review my pr.

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Kindly include some indentation to make the code more readable

**Comment by papri24majumder** [comment]
@Kumar-laxmi done

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
