### PR TITLE
Bi section method is created

### PR DESCRIPTION
**Pull request by Anirudh3167**
## 🛠️ Issue (Number)
#1236 

## 👨‍💻 Changes proposed
- Creation of folder inside Maths with name `root finding methods`
- Bi section method is implemented
- Readme file for the folder is created

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
- Fully customizable code at every part for easy use and embedding at any other places
- A bit of request - response is there which allows it to work like REST API
- There is already `bisection.py` existing in the `Maths` folder but that is not actually the working. It is fixed for a specific equation with no modification allowance. So I thought to create a new folder for this root finding techniques and add the others methods like secant and Newton Raphson soon
- The code is in `Python`

## 📷 Screenshots
None

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Your implementation is incomplete

**Comment by Anirudh3167** [comment]
If possible can you provide some more details regarding this. So that I can know exactly what is expected

**Comment by Kumar-laxmi** [comment]
> If possible can you provide some more details regarding this. So that I can know exactly what is expected

The issue was assigned in four languages but you have only implemented it in one language

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- No need to create separate folder ```Root Finding Methods```
- Directly place the program file in ```Maths``` folder
- Do not create a separate README.md
- Instead add README.md content in program file as comment

**Comment by Anirudh3167** [comment]
I have updated the changes suggested.

**Comment by Anirudh3167** [comment]
There is a problem in coding it in other languages like C, C++ as the function cannot be evaluted.

Python has `eval()` to deal with it

**Comment by Kumar-laxmi** [comment]
> There is a problem in coding it in other languages like C, C++ as the function cannot be evaluted.
> 
> Python has `eval()` to deal with it

It is very much possible to code in any language unless you understand the algorithm, I suggest you to practice this on rough paper and then implement the recursive code of this logic

**Pull request closed without merging**
