### PR TITLE
Create BoyerMoore.java

### PR DESCRIPTION
**Pull request by swastik-akhil**
## 👨‍💻 Changes proposed

- [x] Added Boyer Moore Majority Voting algorithm.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (200)

### CODE REVIEW

**Comment by swastik-akhil** [comment]
@Kumar-laxmi, @zugzwang03 , @Arun9739 I've completed this one, kindly review and merge.

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by swastik-akhil** [comment]
@Kumar-laxmi Kindy merge as all approvals are there.

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Take the input from the user instead of defining it

**Comment by swastik-akhil** [comment]
It's juts the implementation of algorithm. Anyone working with this code can easily understand it. There is no big deal in doing that, but then I would have to change it in all 4 languages which becomes a very time taking task for me, as I would have to seek help from others to type code as I don't know all of them. It was not known to me that I've to take input from user that's why I  implemented it with an example. Kindly approve this code. It's my humble request to you @Kumar-laxmi .

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
