### PR TITLE
Addition of 2 linked list Python

### LINKED ISSUE #770: Addition of two Linked List in Java
I did not found Addition of two Linked List in Java . I can do this with proper implementation.
please assign this to me @Kumar-laxmi  as a part of SSOC'23

### PR DESCRIPTION
**Pull request by SivaHarshith1303**
## 🛠️ Issue 770

Issue no #770

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (36)

### CODE REVIEW

**Comment by SivaHarshith1303** [comment]
Addition of 2 linked list using python

**Review by 072arushi — CHANGES_REQUESTED** [review]
could you add code for Java and Cpp as well

**Comment by SivaHarshith1303** [comment]
Mam, CPP  is already present I think i  only need to add the code in java and C

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Remove Kadane's algo's program file from this PR

**Comment by SivaHarshith1303** [comment]
@Kumar-laxmi how to remove Kadane's algo's program file from this PR

**Comment by SivaHarshith1303** [comment]
@Kumar-laxmi  i have deleted Kadane's algo file could you please once check it

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please do not open multiple PRs for same issue, kindly close other two PRs and include all three programs in one PR

**Pull request closed without merging**
