### PR TITLE
Added AVL Tree Implementation and Doubly Linked List Implementation in C language

### LINKED ISSUE #11: AVL Trees
Implement AVL Tree using the following four languages:
- C
- C++
- Python
- Java

### PR DESCRIPTION
**Pull request by Sowham-3098**
## 🛠️ Issue (Number)

Issue no #11 
Issue no #51 _

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by Sowham-3098** [comment]
I have added AVL  Tree and Doubly LinkedList implementation in C language. @Kumar-laxmi plz check and sorry for the late.

**Review by zugzwang03 — APPROVED** [review]

**Review by Rancho2002 — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Comment by Kumar-laxmi** [comment]
@Sowham-3098 Kindly resolve issues raised by **CodeFactor**

**Comment by Sowham-3098** [comment]
Actually, I don't understand. what is the issue?

**Comment by Kumar-laxmi** [comment]
> Actually, I don't understand. what is the issue?

It is basically asking you to do some changes in code flow

**Comment by Sowham-3098** [comment]
I changed but it gives same issue..

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please don't update the README.md, it might cause Merge Conflict

**Comment by Sowham-3098** [comment]
@Kumar-laxmi please check

**Pull request closed without merging**
