### PR TITLE
Shell Sort In C

### PR DESCRIPTION
**Pull request by Mansiuniyal**
## 🛠️ Issue (Number)

Issue no #263

## 👨‍💻 Changes proposed

Added the program for sorting the elements using Shell Sort in C

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (1003)

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]
Approved

**Review by Kumar-laxmi — APPROVED** [review]

**Review by zugzwang03 — COMMENTED** [review]
Would have been more complete if you explained your gap concept in a few comment lines

**Comment by Mansiuniyal** [comment]
I have added some more comment lines for explanation of gap concept in the code.

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@Mansiuniyal  You can add the time and space complexities for the program.

**Review by zugzwang03 — APPROVED** [review]
Well drafted!

**Comment by Mansiuniyal** [comment]
@Sanjanabharadwaj25 Added the time and space complexity in the code.

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Mansiuniyal** [comment]
@Kumar-laxmi Please merge the pull request as it has got the approvals of all the reviewers

**Comment by Kumar-laxmi** [comment]
@Mansiuniyal Please don't add same algo. using two different PR

**Pull request closed without merging**
