### PR TITLE
Optimal merge pattern

### PR DESCRIPTION
**Pull request by NikitaGupta-17**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Optimal merge pattern
It is minimum no of moves req to merge files by Greedy Approach.
It is a process of merging 2 sorted files of different length into a single sorted file.
If length of sorted file is n and length of another sorted file is m then time complexity will be O(n+m).

Approach

sort files in ascending order of sizes.
Pick the files of smaller sizes and merge them.

For example
Q If there are 5 files apply optimal merge pattern.(20,30,10,5,30).
Ans
Step 1: Sort files in ascending order of their sizes.
x4 x3 x1 x2 x5
5 10 20 30 50
Step 2: Pick the files of smaller size and merge them
Merge x3 and x4 |z1|=5+10=15
Merge z1 and x1|z2|=35
Merge x2 and x5|z3|=60
Merge z3 and z2=60+35=95
Total no of moves= 205

205 is the minimum no of moves if we combine in different ways then moves will be greater than 205.

## 📷 Screenshots
Output for program in C++
op2

Output for program in C
op3

Output for program in Python
op1

Output for program in Java
op4

### CODE REVIEW

**Review by 072arushi — APPROVED** [review]
Good contribution

**Review by siddhi-244 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Comment by NikitaGupta-17** [comment]
@Kumar-laxmi Please merge this Pr.

**Review by Kumar-laxmi — APPROVED** [review]
Change the file name ```OMP.java``` to ```Optimal_Merge_Pattern.java```

**Comment by NikitaGupta-17** [comment]
@Kumar-laxmi I have change the filename. Now please review it.

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
