### PR TITLE
added scanline algorithm code in C++ and python

### LINKED ISSUE #862: Scanline algorithm in C++ and Python
### Is your feature request related to a problem? Please describe.
Yes, I would like to work on this algorithm.

### Describe the solution you'd like
I will add appropriate comments in the code and also properly explain the algorithm

@Kumar-laxmi  Kindly assign me with this task, I will do my best .
Under SSOC'23

### PR DESCRIPTION
**Pull request by shruti8302**
## 🛠️ Issue (Number)

Closes #862 

## 👨‍💻 Changes proposed
Added Scanline Algorithm in C++ and Python

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## Screenshots
C++ Ouput:
Screenshot (458)

Python Output:
Screenshot (460)

### CODE REVIEW

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@shruti8302 Add output screenshot

**Review by shruti8302 — COMMENTED** [review]
C++ Ouput:
Screenshot (458)

Python Output:
Screenshot (460)

**Review by 072arushi — CHANGES_REQUESTED** [review]
Add screenshots and complete the description

**Review by shruti8302 — COMMENTED** [review]
@072arushi  Could u tell me which description u are talking about?

**Comment by shruti8302** [comment]
@072arushi @Arun9739 @Kumar-laxmi I have added the screenshot and completed the description.

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Shift the programs to ```Graphics``` folder

**Comment by shruti8302** [comment]
> Shift the programs to `Graphics` folder

I have shifted the programs into "Graphics" folder.

**Review by zugzwang03 — APPROVED** [review]

**Pull request merged**
