### PR TITLE
Boyer Moore algorithm in c added 

### PR DESCRIPTION
**Pull request by Sachittarway**
## 🛠️ Issue (Number)  235

Issue no #235

## 👨‍💻 Changes proposed
Added program in c.

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️ ] My code follows the code style of this project.
- [ ✔️ ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Added Boyer Moore Algorithm which is the majority element problem in c.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Sachittarway** [comment]
@Kumar-laxmi @Arun973 Please review it.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add some comments in the code explaining your step by step approach

**Comment by Sachittarway** [comment]
@siddhi-244 @Rancho2002 @Sanjanabharadwaj25 Please review and approve it.

**Review by Sanjanabharadwaj25 — CHANGES_REQUESTED** [review]
@Sachittarway Remove the binary file from the commit.

**Comment by Sachittarway** [comment]
@siddhi-244 @Rancho2002 @Sanjanabharadwaj25 Please review and approve it.

**Review by siddhi-244 — APPROVED** [review]

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Sachittarway** [comment]
@Rancho2002 please approve it.

**Review by Rancho2002 — APPROVED** [review]
Perfect

**Comment by Sachittarway** [comment]
@Kumar-laxmi please merge it.

**Pull request merged**
