### PR TITLE
Counting Sort using C++

### PR DESCRIPTION
**Pull request by vijay-kumar-yadav**
## 🛠️ Issue (#121 )

Issue no. #121

## 👨‍💻 Changes proposed
Added counting sort in Cpp section
Updated readme for counting sort

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@vijay-kumar-yadav Please resolve MERGE CONFLICT

**Comment by vijay-kumar-yadav** [comment]
> @vijay-kumar-yadav Please resolve MERGE CONFLICT

Ok

**Comment by vijay-kumar-yadav** [comment]
> > @vijay-kumar-yadav Please resolve MERGE CONFLICT
> 
> Ok

@Kumar-laxmi  Merge conflict fixed

**Comment by vijay-kumar-yadav** [comment]
@Kumar-laxmi fixed merge conflicts

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
