### PR TITLE
Issue #178 -  Rabin Karp in c 

### LINKED ISSUE #96: Rabin Karp Algorithm
Rabin-Karp algorithm is an algorithm used for searching/matching patterns in the text using a hash function. Unlike Naive string matching algorithm, it does not travel through every character in the initial phase rather it filters the characters that do not match and then performs the comparison.

This algorithm is available in the following language:
- C
- C++
- Java
- Python

### LINKED ISSUE #178: Rabin Karp
**Is your feature request related to a problem? Please describe.**
As mentioned in Readme Rabin Karp is Done in C++ it can be also implemented in C prog as well as  java 

**Describe the solution you'd like**
Will provide clear and proper documented solution of it 

**Describe alternatives you've considered**
Can be solved in java script 

**Additional context**
Screenshot will be added of solution with the time complexity and other stuff

### PR DESCRIPTION
**Pull request by Abhinavkar**
## 🛠️ Issue (Number) ` Closes #96` 

Issue no #96  

## 👨‍💻 Changes proposed
Proposed `Rabin Karp`

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
As i have done the code my self i had just taken a reference from CLRS book 

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Abhinavkar** [comment]
@Kumar-laxmi  Review Requested

**Comment by Abhinavkar** [comment]
Add under Swoc

**Comment by Abhinavkar** [comment]
@Kumar-laxmi @072arushi @Sanjanabharadwaj25 guys merge in rabin one else all be get in the same commit

**Comment by Abhinavkar** [comment]
@072arushi

**Comment by Kumar-laxmi** [comment]
@Abhinavkar Update the issue no. for RABIN KARP

**Comment by Abhinavkar** [comment]
@Kumar-laxmi changes done merge requested

**Comment by Abhinavkar** [comment]
@072arushi Review Required !!

**Review by 072arushi — APPROVED** [review]
Approved

**Comment by Abhinavkar** [comment]
@072arushi Pls update the labels @Kumar-laxmi Merge Requested

**Review by Sanjanabharadwaj25 — COMMENTED** [review]
@Abhinavkar  Link the issue #96 for this PR. Also you have added/changed some problems in backtracking. Please look into that.

**Comment by Abhinavkar** [comment]
@Sanjanabharadwaj25 done as requested ya we already discussed in discord it happened due to late merging of pr

**Review by Sanjanabharadwaj25 — APPROVED** [review]

**Comment by Abhinavkar** [comment]
@Kumar-laxmi merge

**Comment by Kumar-laxmi** [comment]
@Abhinavkar You have mentioned a issue number which is closed

**Comment by Abhinavkar** [comment]
> @Abhinavkar You have mentioned a issue number which is closed
It is still open #96

**Comment by Kumar-laxmi** [comment]
@Abhinavkar Please update the issue no

**Comment by Abhinavkar** [comment]
image
see @Kumar-laxmi

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Please mention all issue numbers that you are resolving & implement all algorithms that are mentioned in the issue of Backtracking

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@Abhinavkar There are some binary files, which are not necessary.
Remove them.
Eg : Nqueenproblem

**Review by 072arushi — APPROVED** [review]

**Pull request closed without merging**
