### PR TITLE
Closes #1445 Added SJF implementation in C, C++, Java & Python

### LINKED ISSUE #1445: Shortest Job First [CPU Scheduling] in C, C++, Python and Java
**Is your feature request related to a problem? Please describe.**
Shortest job first (SJF) is a scheduling process that selects the waiting process with the smallest execution time to execute next. This scheduling method may or may not be preemptive. Significantly reduces the average waiting time for other processes waiting to be executed. The full form of SJF is Shortest Job First.

**Describe the solution you'd like**
```
- Retrieve the arrival time and burst time for each process.
- Sort the processes based on their burst time in ascending order.
- Initialize an empty ready queue to hold the processes that have arrived but not yet executed.
- Set the current time to 0.
- While there are processes in the ready queue or unprocessed processes:
   - Check for any arriving processes at the current time and add them to the ready queue. 
   - If the ready queue is empty, increment the current time.
   - If the ready queue is not empty:
     - Sort the ready queue based on the remaining burst time of each process (assuming the burst time decreases with each execution).
     - Select the process with the shortest burst time from the ready queue.
     - Execute the selected process for one time unit.
     - Update the remaining burst time for the executed process.
     - If the remaining burst time of the process is 0, calculate and store its turnaround time and waiting time.
     - Increment the current time by one unit.
- Calculate the average turnaround time and average waiting time for all executed processes.
- Display the average turnaround time and average waiting time.
```

**Additional context**
image

### PR DESCRIPTION
**Pull request by ranjanmangla1**
## 🛠️ Issue #1445 

Issue no #1445 

## 👨‍💻 Changes proposed
Added implementation of Shortest Job First Scheduling algo in C, C++, Python & Java

#### C++
image
#### C
image
#### Java
image
#### Python
image

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Put the file name as ```Shortest_Job_First.<extension>```

**Review by zugzwang03 — APPROVED** [review]

**Comment by ranjanmangla1** [comment]
@Kumar-laxmi changed the name of sjf to Shortest_Job_First

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — CHANGES_REQUESTED** [review]
@ranjanmangla1 Add output screenshots

**Comment by ranjanmangla1** [comment]
> @ranjanmangla1 Add output screenshots

Please review it again @Arun9739 @Kumar-laxmi  ,I have added Output Screenshots

**Review by Arun9739 — APPROVED** [review]

**Review by Kumar-laxmi — APPROVED** [review]

**Pull request merged**
