### PR TITLE
Added Kruskal Algorithm in  C, C++, Java & Python

### LINKED ISSUE #1459: Kruskal's Algorithm in C, C++, Java & Python
### Feature :
Kruskal's Algorithm is a greedy algorithm that is used to find the minimum spanning tree from a graph.
The idea is to sort all edges of given graph in increasing order, and then keep on adding new edges and nodes in the spanning tree if the added edge does not form a cycle. 

This will be added in C, C++, Java and Python.

### Description of solution :
- Will add Kruskal's Algorithm with adequate comments and proper documentation for readers to get a clear understanding.
- To be added in C, C++, Java and Python

**Additional context**
image

### PR DESCRIPTION
**Pull request by Viveksati5143**
## 🛠️ Issue (Number)

Closes #1459 

## 👨‍💻 Changes proposed

Added Kruskal Algorithm in  C, C++, Java & Python

## ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot 2023-06-21 182148

### CODE REVIEW

**Comment by Viveksati5143** [comment]
All set @Kumar-laxmi @Arun9739 @072arushi @zugzwang03

**Review by zugzwang03 — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by Viveksati5143** [comment]
@Kumar-laxmi let's goo

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
The code seems to be copied from https://www.javatpoint.com/kruskal-algorithm

**Comment by Viveksati5143** [comment]
No, It isn't copied. I learnt it about 2 weeks ago from the same javapoint. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
Why is the implementation exactly same with just names of functions changed?

**Comment by Viveksati5143** [comment]
Coz Its fresh for me as it is just around 2 weeks since i learnt it from there.
Also i have added extra caption to my above comment you can check please.

**Comment by Kumar-laxmi** [comment]
> Coz Its fresh for me as it is just around 2 weeks since i learnt it from there. Also i have added extra caption to my above comment you can check please.

You are supposed to understand the algorithm, but your implementation is just the copy of the code given

**Pull request closed without merging**
