### PR TITLE
added tim sort in the java sort folder

### LINKED ISSUE #987: Tim Sort in C, C++, Java & Python
'Im interested in contributing to your GitHub repository and would like to add Tim short with proper comments in the java short folder  to enhance its functionality. Please let me know if you would be open to accepting this addition. I believe it will benefit the community. Thank you for your consideration.
@Kumar-laxmi please assign this issue to me.

### PR DESCRIPTION
**Pull request by harshit7045**
Issue no #987 
## 👨‍💻 Changes proposed

I have successfully implemented the Tim Sort algorithm in C, C++, Java, and Python. Tim Sort is a highly efficient sorting algorithm that combines insertion sort and merge sort techniques, ensuring stable sorting with optimal performance for real-world data. Please review the commit for detailed code implementation. Thank you.
## 📄 Note to reviewers
hi this is my first contribution to any repo plz let me know if their are any isuees
**screenshots**-

C language-
image

JAVA language-
image

C++ language-
image

Python language-

WhatsApp Image 2023-06-10 at 22 13 55

### CODE REVIEW

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Changes:
- Add program in C, C++ & Python
- Complete the PR Description (give an elaborate explanation of what you did)
- Add screen shot of your output in all languages

**Comment by harshit7045** [comment]
plz review the request

**Review by Kumar-laxmi — CHANGES_REQUESTED** [review]
Your C++ program file is missing ```.cpp``` extension

**Review by zugzwang03 — CHANGES_REQUESTED** [review]
write tim_sort in cpp file

**Review by 072arushi — APPROVED** [review]

**Review by Arun9739 — APPROVED** [review]

**Review by zugzwang03 — APPROVED** [review]

**Pull request merged**
